### ISSUE TITLE
windRose; type="hour"; does not adjust for timezone or lat-lon

### ISSUE THREAD

**Issue by bgrumbine** [davidcarslaw/openair#10]
First off, I am new to both R and openair. I understand that openair is under heavy development. So far I like them. Thanks.

It seems to me that in the __windRose()__ function __type="hour"__ ought to behave like __type="daylight"__ and adjust with __latitude__ and __longitude__ , or perhaps pay attention to the __tzone__ parameter.

I have made a simplified test case below.

The only parameters that shift the plot are __latitude__ and __longitude__ when used with __type = "daylight"__.

Otherwise, data is plotted as though it were __UTC__, regardless of __import()__'s __tzone__ setting or __windRose()__'s __tzone__ setting.

test2.dat
```
"date","ws","wd"
"2015-02-04 00:00:00",0.5,0
"2015-02-04 01:00:00",1.0,15
"2015-02-04 02:00:00",1.5,30
"2015-02-04 03:00:00",2.0,45
"2015-02-04 04:00:00",2.5,60
"2015-02-04 05:00:00",3.0,75
"2015-02-04 06:00:00",3.5,90
"2015-02-04 07:00:00",4.0,105
"2015-02-04 08:00:00",4.5,120
"2015-02-04 09:00:00",5.0,135
"2015-02-04 10:00:00",5.5,150
"2015-02-04 11:00:00",6.0,165
"2015-02-04 12:00:00",6.5,180
"2015-02-04 13:00:00",7.0,195
"2015-02-04 14:00:00",7.5,210
"2015-02-04 15:00:00",8.0,225
"2015-02-04 16:00:00",8.5,240
"2015-02-04 17:00:00",9.0,255
"2015-02-04 18:00:00",9.5,270
"2015-02-04 19:00:00",10.0,285
"2015-02-04 20:00:00",10.5,300
"2015-02-04 21:00:00",11.0,315
"2015-02-04 22:00:00",11.5,330
"2015-02-04 23:00:00",12.0,345
```

test2.R
```
# Read the csv file:
require(openair)
test2_data <- import("~/R/fsa_wind/test2.dat",
 date.format = "%Y-%m-%d %H:%M:%S",
 tzone = "Etc/GMT-7")
# tzone = "Etc/GMT+7")
# tzone = "GMT")
# tzone = "UTC")

# type = "daylight"
png("test2_daylight1.png", width = 450, height = 300)
windRose(test2_data, angle = 15,
 type = "daylight", layout = c(2,1),
 main = "daylight")
dev.off()

png("test2_daylight2_tz.png", width = 450, height = 300)
windRose(test2_data, angle = 15,
 type = "daylight", layout = c(2,1),
 tzone = "Etc/GMT-7",
 main = "daylight, Etc/GMT-7")
dev.off()

png("test2_daylight3_lat-lon.png", width = 450, height = 300)
windRose(test2_data, angle = 15,
 type = "daylight", layout = c(2,1),
 latitude = 35.2, longitude = -112.1,
 main = "daylight, lat-lon")
dev.off()

png("test2_daylight4_tz_lat-lon.png", width = 450, height = 300)
windRose(test2_data, angle = 15,
 type = "daylight", layout = c(2,1),
 tzone = "Etc/GMT-7",
 latitude = 35.2, longitude = -112.1,
 main = "daylight, Etc/GMT-7, lat-lon")
dev.off()

# type = "hour"
png("test2_hour1.png", width = 1000, height = 750)
windRose(test2_data, angle = 15,
 type = "hour", layout = c(6,4),
 main = "hour")
dev.off()

png("test2_hour2_tz.png", width = 1000, height = 750)
windRose(test2_data, angle = 15,
 type = "hour", layout = c(6,4),
 tzone = "Etc/GMT-7",
 main = "hour, Etc/GMT-7")
dev.off()

png("test2_hour3_lat-lon.png", width = 1000, height = 750)
windRose(test2_data, angle = 15,
 type = "hour", layout = c(6,4),
 latitude = 35.2, longitude = -112.1,
 main = "hour, lat-lon")
dev.off()

png("test2_hour4_tz_lat-lon.png", width = 1000, height = 750)
windRose(test2_data, angle = 15,
 type = "hour", layout = c(6,4),
 tzone = "Etc/GMT-7",
 latitude = 35.2, longitude = -112.1,
 main = "hour, Etc/GMT-7, lat-lon")
dev.off()
```

**Comment by bgrumbine** [comment]
Further exploring these functions, I see that when __type = "daylight"__, cutDaylight() is called and __cutDaylight()__ is the function that ultimately uses __latitude__, __longitude__, and __local.hour.offset__.

So, even more confusing: 
The data is using __UTC__.
I set __local.hour.offset = -7__ (MST) and the __type = "daylight"__ plot shows up correctly.

I set __latitude = 35.2__ and __longitude = -112.1__, which should put me in the same time zone (MST), the plot graphs the data as __+7__ instead of __-7__.

__local.hour.offset__ has no effect on __type = "hour"__ plots.  At this point I am thinking this is to be expected as __type = "hour"__ likely needs special handling similar to  __cutDaylight()__.

New test script:
```
# Read the csv file:
require(openair)
test2_data <- import("~/R/fsa_wind/test2.dat",
 date.format = "%Y-%m-%d %H:%M:%S")

png("test2_daylight1.png", width = 450, height = 300)
windRose(test2_data, angle = 15,
 type = "daylight", layout = c(2,1),
 main = "daylight")
dev.off()

png("test2_daylight3_lat-lon.png", width = 450, height = 300)
windRose(test2_data, angle = 15,
 type = "daylight", layout = c(2,1),
 latitude = 35.2 longitude = -112.1,
 main = "daylight, lat-lon")
dev.off()

png("test2_daylight5_local-hour-offset.png", width = 450, height = 300)
windRose(test2_data, angle = 15,
 type = "daylight", layout = c(2,1),
 local.hour.offset = -7,
 main = "daylight, local.hour.offset")
dev.off()
```

**Comment by davidcarslaw** [comment]
Most of the time the time zone does not matter in openair - it will just plot the hour in whatever time zone the data are in. I strongly suggest importing the data in GMT or a fixed offset from GMT. I am not clear quite what you are trying to do with the data.

In openair the `type = "hour"` will just extract the hour component of the data it is presented with. So if you import data in R and set the tz to GMT it will just use that without correction. Similarly, if you import data with a fixed offset from GMT e.g. "Etc/GMT+7" the same will happen - you should get the same plot. Where things *do* change is where you want to redisplay original data *in a different time zone*. 

For example, if you import data assuming GMT but then want to make a plot based on the hours in "Etc/GMT+7", things will change. Take the following example based on the data above.

    dat <- import("~/temp/dat.csv") ## GMT by default
    windRose(dat, type = "hour")

This following should produce the same wind rose as above:

    dat <- import("~/temp/dat.csv", tz = "Etc/GMT-7") 
    windRose(dat, type = "hour")

**However** if I use the first example (GMT) and *then* change the time zone:

    attr(dat$date, "tzone") <- "Etc/GMT+7"
    windRose(dat, type = "hour")

it will shift the hours by 7 to the new time zone and produce a different plot i.e. it will display the data in the new time zone. That is the intended behaviour in openair. I will have a look at your other question shortly...

**Comment by bgrumbine** [comment]
Thank you, I appreciate your help.

> Most of the time the time zone does not matter in openair [...]

I think this is the source of my confusion. I need to understand when/where time zone matters.

> I strongly suggest importing the data in GMT or a fixed offset from GMT.

Am I doing this correctly?
* The site is in US/Arizona (GMT-7), Arizona does not observe DST, so DST is not a concern.
* Data is stored in sqlite, with a julianday() time stamp column.
* A CSV file is created from sqlite with the CSV's __date__ column in GMT such that a reading taken at 08:00 local time is in the CSV as 01:00.

Your examples are helpful.

I expected that passing __import()__ a __tzone__ parameter as in your second example `dat <- import("~/temp/dat.csv", tz = "Etc/GMT-7")`, would produce the same results as your third example `attr(dat$date, "tzone") <- "Etc/GMT+7"`.

If the __import()__ function's __tzone__ parameter does not change the data's tzone attribute, I see no reason to ever use it.


I am concerned that I will unwittingly produce graphs with an incorrect time zone offset.  
* Is it best to always work with data in __local__ time?

I could just as easily create my CSV with __date__ in local time and no offsets.

**Comment by bgrumbine** [comment]
OK, I'm still banging my head on this... now for an even more simplified example:

I take a data reading at 08:00 local time (GMT-7).

I export a CSV with __date__ in GMT (local + 7); dat.csv:
```
"date","ws","wd"
"24/04/2015 15:00",6,225
```

I __import()__ the data:
```
> dat <- import("~/temp/dat.csv") ## GMT by default
    date1     date2        ws        wd 
"POSIXct"  "POSIXt" "integer" "integer" 
> dat
                 date ws  wd
1 2015-04-24 15:00:00  6 225
```

I tell R the data's time zone:
```
> attr(dat$date, "tzone") <- "Etc/GMT-7"
> dat
                 date ws  wd
1 2015-04-24 22:00:00  6 225
```

I expected to go back to local time; __date__ - 7 hours:
__2015-04-24 08:00:00__

but time changed in the opposite direction; __date__ + 7 hours:
__2015-04-24 22:00:00__


*[... many hours later]*
Finally a break through.
```
> dat <- import("~/temp/dat.csv") ## GMT by default
    date1     date2        ws        wd 
"POSIXct"  "POSIXt" "integer" "integer" 
> attr(dat$date, "tzone") <- "US/Arizona"
> dat$date
[1] "2015-04-24 08:00:00 MST"
```

I checked this on my primary system OpenBSD, and a Debian Linux system, R acts the same on both. It appears to me that R's handling of __GMT-n__ and __GMT+n__ is broken. If I stick with named time zones such as "US/Arizona" or "America/Phoenix" the conversion works correctly.

**Comment by davidcarslaw** [comment]
Yes - I think that is confusing. It is covered in section 9.1 in the manual to some extent. Where time zones will matter more in general analysis is when combining data. For example, Hysplit will use UTC but your local measurement data may well be in a different time zone (such as GMT/Etc+7). In order to match the hours properly openair/R will need to know this - or the users needs to be aware of the potential pitfalls. However, like I say, the vast majority of analysis in openair can proceed without worrying about time zone - but do make sure to use GMT or GMT with fixed offsets when importing data. Daylight Savings Time can introduce a whole load of other issues that are probably best avoided!
