### ISSUE TITLE
Font type issue

### ISSUE THREAD

**Issue by yusriy** [davidcarslaw/openair#100]
Hi, I've tried searching online on how to change the font from what I think the default is Arial to Times New Roman in all of the plots in openair (such as windRose) but couldn't find any solution. Is there a simple method to accomplish this?

**Comment by jack-davison** [comment]
You should be able to specify the font when saving the plots to your graphics device of choice. For example:

```r
windowsFonts()

png(
  "myplot.png",
  family = "serif",
  width = 5,
  height = 5,
  units = "in",
  res = 300
)
openair::polarPlot(openair::mydata, "nox")
dev.off()
```
![myplot](https://user-images.githubusercontent.com/45171616/222969930-27161a95-745d-4c5f-b11f-60c06358de22.png)

Use `windowsFonts()` to see the fonts R currently "sees". There are many ways to import other fonts to R, e.g., <https://medium.com/analytics-vidhya/5-easy-steps-to-import-new-fonts-into-r-6651bf263a07>
