### ISSUE TITLE
scatterplot with variables from different datasets

### ISSUE THREAD

**Issue by kailas29** [davidcarslaw/openair#102]
Hi David,

Is it possible to make a scatterplot with 2 variables (without having a grouping variable) from multiple (2 or more) different stations in the same plot in order to compare the slopes? (e.g. OX-NOx plots for North Kensington and Marylebone Road)

Thank you very much in advance 
Bill

**Comment by jack-davison** [comment]
Closing this stale issue, but feel free to reopen if you are still having issues. I believe what you are asking for is partially answered in https://github.com/davidcarslaw/openair/issues/58.

``` r
dat <- openair::importAURN(c("kc1", "my1"))

openair::scatterPlot(
  dat, 
  avg.time = "day",
  group = "site",
  linear = TRUE,
  fill = c("hotpink", "darkgreen"),
  color = c("hotpink", "darkgreen"),
  cols = c("hotpink", "darkgreen")
)
```

![](https://i.imgur.com/hapgFqi.png)

<sup>Created on 2023-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
