### ISSUE TITLE
trajLevel

### ISSUE THREAD

**Issue by Homaghasemi** [davidcarslaw/openair#104]
I am using trajLevel based on HYSPLIT data to produce a map with pscf statics. 
input data frame has lon and lat columns and output data has a xgrid and ygrid. 
I am interested to use to output data coordinate (xgrid and ygrid) to merge it with a new data frame and generate new plot. 
would you please tell me how to transform this x and y grid to lat and lon? 

Best, 
Homa

**Comment by masabhathini** [comment]
Dear davidcarslaw,
I also facing the same problem.
**would you please tell me how to transform this x and y grid to lat and lon?**
Kindly guide for solution.
