### ISSUE TITLE
calcPercentile - 1 percentile number for the whole length of my data?

### ISSUE THREAD

**Issue by kailas29** [davidcarslaw/openair#105]
Hi david,

I am using it without avg.time option : calcPercentile(noxdata, pollutant = "nox", percentile = 10), but still it gives me monthly values. Is it possible to calculate the percentile for my whole dataframe , 1 percentile value for the whole length of nox data and not yearly or monthly etc?

Any suggestions?

Many thanks,

**Comment by davidcarslaw** [comment]
I probably need to take a look at that function again - it's rather long in the tooth. However, if you want the percentile to be calculated for all your data, you could just set the averaging time to "2 year" or some period longer than that of the data. 

If you can provide you can provide an example with some data and a comment on what is not working correctly, I can think about modifying the function...

**Comment by schonhose** [comment]
Leaving out the `avg.time` parameter will force the function to use the default setting, in this case `month`. See also `?calcPercentile`

**Comment by jack-davison** [comment]
Closing stale issue. For anyone searching, `avg.time` has a default value of "month". If you'd like to get percentiles for your whole dataset, I'd set `avg.time` to some high value longer than the period of the data, as David suggested.

``` r
openair::calcPercentile(
  openair::mydata,
  pollutant = "nox",
  percentile = 10,
  avg.time = "10 year"
)
#>         date percentile.10
#> 1 1998-01-01            47
```

<sup>Created on 2023-02-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
