### ISSUE TITLE
GoogleMapsFunction not working

### ISSUE THREAD

**Issue by agustinee** [davidcarslaw/openair#106]
Dear David.

First of all, I want to say that I am new to both openair and R software. I am a student of an university in Indonesia. Now, I am doing my research to finish my study for bachelor program using openair.
I have installed openair package and analysed using its functions such as theilSen, timeVariation and etc.
They all worked. Then, I started to load GoogleMapsPlot Function. 
This function (GoogleMapsPlot) doesn't work. I am a bit confused as it said that "Error: could not find function "GoogleMapsPlot""
Does it mean that GoogleMapsPlot Function doesn't include in openair package ?
I have tried to install other packages such as ropenaq , Rgooglemaps, but it still doesn't work.
May I know how can I solve this ?

Besides that, I would like to know how to import data from csv format in my computer to GoogleMapsPlot Function. As for what I have read in the OpeanAir Manual, it is using load(url). 
Is it okay for me to import just like I do in the other functions ? As for now I'm using "my data <- import()".

Thanks for your help.
Regards, 
Agustinee.

**Comment by kheaactua** [comment]
+1

**Comment by clarkdk** [comment]
Regarding importing csv data: There are several R functions to read csv files. I like the fread() function in the data.table package, as it often guesses the format without requiring additional parameters. Install the data.table package from CRAN [install.packages("data.table")], and then see the help ?fread. You can usually directly read from a url in fread, like fread("http://www.xyz.zz/mydat.csv"). If the csv file is reasonably standard, with a heading row with column names, it will guess the format and return a data.table (enhanced data.frame). However, dates in your csv file are usually imported as characters, so you will need to convert dates into an R date type after import (such as POSIXct) -- see the lubridate package for that. 
Another popular csv reader is the readr() function [install.packages("readr")].  [Or get the whole group of dplyr-related packages, including lubridate, with install.packages("tidyverse")]. If you use RStudio, it has a built-in feature to import csv data files for you, using readr. See the "Import dataset" button in the Environment tab.

**Comment by ClauGro** [comment]
Dear David,
I have used the GoogleMaps function in the past on others windows pcs.
However,now, when I tried to run it in my R 3.4.4  o 3.5 versions i get an error.
It does not find the function:"could not find function "GoogleMapsPlot"
I have not problem running others openair functions such as windrose,polarplots and so on.
Any help?
Thanks in advance
Claudia

**Comment by jack-davison** [comment]
Closing as `GoogleMapsPlot()` has not been in `openair` for a while now.

Consider [leaflet](https://rstudio.github.io/leaflet/), [ggmap](https://github.com/dkahle/ggmap) and the [openairmaps](https://github.com/davidcarslaw/openairmaps) package for creating maps. Any specific map-related feature requests may be best raised in the `openairmaps` repo.
