### ISSUE TITLE
run_hysplit problem

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#108]
Hey David,
I found you updated code for running hysplit from "procTraj" to "run_hysplit". 
When I am running run_hysplit function today, I get error message as figure I attached.

The code I use was as below:

```
library(devtools)
source_gist("https://gist.github.com/davidcarslaw/c67e33a04ff6e1be0cd7357796e4bdf5")
data_out <- run_hysplit(
  latitude = 32.6903,
  longitude = -114.6144,
  runtime = -96,
  start_height = 10,
  model_height = 10000,
  start = "2014-01-1",
  end = "2014-01-10",
  hysplit_exec = "c:/hysplit4/",
  hysplit_input = "C:/NARR/",
  hysplit_output = "J:/AQD/SIPS/TECHNICAL ANALYSIS UNIT/STAFF_FILES/Current_Staff/Yi Li/Ozone/HYSPLIT/Metdata/output/testforRyan",
  site = "Yuma")
saveRDS(data_out, file = "J:/AQD/SIPS/TECHNICAL ANALYSIS UNIT/STAFF_FILES/Current_Staff/Yi Li/Ozone/HYSPLIT/Metdata/output/testforRyan")

```
The Met data I used was NARR data download from NOAA ftp
Could you help me to figure out this problem ?
Thanks a lot!
Yi
![1](https://cloud.githubusercontent.com/assets/12972221/24733838/f04bde4a-1a2e-11e7-8971-c0ad6e5f315d.JPG)

**Comment by lyggd** [comment]
Hello David,
I still need your help on this issue.
Thanks a lot !
Yi

**Comment by schonhose** [comment]
@lyggd The function you probably found on Gist, is designed to handle only one sort of meteo files. I recently changed the function so it can handle GDAS1 meteo files. I can probably fix it so it can handle the NARR data as well. Shouldn't be much of a hassle since I have the addition of GDAS0.5 meteo files also on my todo list, kill two birds with one stone. Is the NARR filename still in the format of "NARRyyyymm"?

Let me know if you are still interested.

**Comment by lyggd** [comment]
@schonhose, Thank you very much for your help. Yes ,NARR filename is still in the format of "NARRyyyymm", Please help if you have time.
Best Regards,
Yi

**Comment by schonhose** [comment]
Haven't gotten around to it yet, but hopefully I have some spare time coming up.

**Comment by lyggd** [comment]
Hello there, I just want to know if there is any updates. I am still interested in this issue. 
Thank you very much.

**Comment by davidcarslaw** [comment]
It might be worth looking at [Splitr](https://github.com/rich-iannone/SplitR) that does a lot more than my code. My code only considers reanalysis met data and I have not managed to get around to making it more flexible...

**Comment by lyggd** [comment]
Thank you very much David. It is very helpful.
Best Regards,
Yi
