### ISSUE TITLE
GoogleMapsPlot ERROR

### ISSUE THREAD

**Issue by firafann** [davidcarslaw/openair#109]
Hey David,
I'm trying to use GoogleMapsPlot function by installed old version of openair package. But i get an error message like this:

> Error in if (ra[3] == 4 & attr(map$myTile, "type") == "rgb") { : argument is of length zero

I have installed all depedency packages for openair and try installing different old version but still get the same error. 
Could you help me to figure out this problem ?
Thanks a lot!

**Comment by jack-davison** [comment]
Closing as `GoogleMapsPlot()` has not been in `openair` for a while now and is no longer supported.

Consider [leaflet](https://rstudio.github.io/leaflet/), [ggmap](https://github.com/dkahle/ggmap) and the [openairmaps](https://github.com/davidcarslaw/openairmaps) package for creating maps. Any specific map-related feature requests may be best raised in the `openairmaps` repo.
