### ISSUE TITLE
ScatterPlot: how to combine hexbin and linear?

### ISSUE THREAD

**Issue by MatthiasKetzel** [davidcarslaw/openair#11]
In a scatter plot I would like to add a linear-regression line, while plotting the data with the hexbin method like: 
scatterPlot(mydata,x="nox",y="no2", method = "hexbin", linear = TRUE)

However the hexbin seems to prevents the linear regression? "Linear" works only without the "hexbin".

Any work around for this?

**Comment by davidcarslaw** [comment]
Yes, that would be useful. I will add it to the list of enhancements...

**Comment by davidcarslaw** [comment]
Should now be possible to use linear fits when method = "hexbin" e.g.

    scatterPlot(mydata, x = "pm10", y = "pm25", method = "hexbin",  col = "increment", linear = TRUE)

Note, setting aspect can help change the shape of the plot when using hexagonal binning e.g. try aspect = 0.5 as an option in the above.
