### ISSUE TITLE
Met output along trajectories?

### ISSUE THREAD

**Issue by KatieB24** [davidcarslaw/openair#110]
Hello,
I am interested in getting the met output along the trajectories using the R/openair code.  I know this is possible in the Hysplit GUI and I've looked at how the control file needs to be altered but I'm having trouble seeing where to added the lines to change the variable values from 0 to 1 so the CONTROL, MESSAGE, and TRAJ.CFG files get written properly.  It seems that the pressure is automatically output in the same manner that I'd like to get potential temperature and rain.  Any suggestions?  Thanks!

**Comment by schonhose** [comment]
@KatieB24 If you could be so kind to share the changes needed to the CONTROL and TRAJ.CFG I will try to take a look at it.

As far as your comment about the variables I am not sure if I understand it. Could you elaborate?

**Comment by jack-davison** [comment]
Closing stale issue (6 years without a response). 

If your issue persists please feel free to reopen a new issue, answering the questions from schonhose above.

Cheers!
