### ISSUE TITLE
output openair plot list to r markdown file

### ISSUE THREAD

**Issue by DonnaHaga** [davidcarslaw/openair#112]
I want to output a plot list of calendarPlot's an rmarkdown document, but I am getting an error when I try to create the html taglist. I think this has something to do with the openair class object created; when I try to do something similar with a summaryPlto, it works. 

yaml:

`
title: "mwe openair plotList"  
author: "Author's Name"  
date: "April 28, 2017"  
output: html_document
`

chunks:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(openair)
library(tidyverse)
library(dygraphs)
library(htmltools)

```

```{r data}
data(mydata)

#pick a year of data and two pollutants
mydata<-mydata %>% select(date,no2,o3) %>% filter(format(date,"%Y")=="1998")
```

```{r summaryPlot}
#make a plot list from summaryPlot
plotList<-lapply(names(mydata[-1]),function(i){
  summaryPlot(mydata,
              pollutant=i)
})

#output the plotList:
tagList(plotList)
```

```{r calendarPlot}
#make a plot list from calendarPlot
plotList<-lapply(names(mydata[-1]),function(i){
  calendarPlot(mydata,
              pollutant=i,
              year="1998")
})

#output the plotList:
tagList(plotList)
```
The error I get on the calendarPlot chunk is:Error in as.character(x) : cannot coerce type 'closure' to vector of type 'character'.

**Comment by schonhose** [comment]
If you run the code in the code window, does it produce a graph or not?

**Comment by jack-davison** [comment]
I'm going to close this as it is very stale (6 years!).

I'm not clear what was trying to be achieved here; if you're looking to generate a load of plots for a report programmatically, you can just use a loop or map function and they'll be rendered in the report.

If you have any more details about what `tagList()` is trying to achieve, do let me know!

Jack

````
---
title: "mwe openair plotList"  
author: "Author's Name"  
date: "April 28, 2017"  
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(openair)
library(tidyverse)
library(dygraphs)
library(htmltools)
```

```{r data}
data(mydata)

#pick a year of data and two pollutants
mydata <-
  mydata %>% select(date, no2, o3) %>% filter(format(date, "%Y") == "1998")
```


```{r summaryPlot}
summaryPlot(mydata)

```

```{r calendarPlot}
purrr::walk(names(mydata[-1]),
            ~ calendarPlot(mydata, pollutant = .x, year = 1998))
```
````
