### ISSUE TITLE
PolarPlot

### ISSUE THREAD

**Issue by DafinaKikaj** [davidcarslaw/openair#113]
Hello,

I am using a black background for polarPlot but then I need to change the color of polar coordinates and axes and legend, I tried something with parr.settings but I just changed the axis color. I would appreciate your help.

**Comment by jack-davison** [comment]
I'm closing this stale issue (6 years). If this is still a feature you'd like, feel free to reopen.

If you'd like extra customisation, I'd recommend using `{ggopenair}` and `{ggplot2}` - you can customise almost any element you'd like! https://github.com/jack-davison/ggopenair

``` r
library(ggplot2)

plt <- ggopenair::polar_plot(openair::mydata, "nox")

plt +
  ggopenair::theme_polar() +
  theme(
    panel.background = element_blank(),
    plot.background = element_rect(fill = "black"),
    line = element_line(color = "white"),
    axis.text = element_text(color = "white"),
    legend.background = element_blank(),
    legend.text = element_text(color = "white"),
    legend.title = element_text(color = "white"),
    panel.ontop = TRUE,
    text = element_text(family = "serif")
  ) +
  ggopenair::scale_opencolors_c(scheme = "turbo")
```

![](https://i.imgur.com/OaLWzld.png)

<sup>Created on 2023-09-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
