### ISSUE TITLE
windRose code works, pollutionRose doesn't

### ISSUE THREAD

**Issue by GeraldCNelson** [davidcarslaw/openair#117]
The follow code to generate wind roses works.
```
# windrose by season
for (i in c(locationNames.complete, locationNames.noT)) {
  print(paste("working on ", i))
  title = paste(i,  'wind roses, by season')
  ws = paste("ws_", i, sep = "")
  wd = paste("wd_", i, sep = "")
  temp <- windRose(combined.sites, ws, wd, type =  "season", main = title, key.footer = "miles/hour")
  assign(paste("rose", i, sep = "."), temp)
}
```

but the following code for pollutionRoses returns 
Error in `[[<-.data.frame`(`*tmp*`, vars[i], value = numeric(0)) : 
  replacement has 0 rows, data has 4645

```
# pollutionRose by season
for (i in c(locationNames.complete, locationNames.noT)) {
  print(paste("working on ", i))
  title = paste(i,  'pollution roses, by season')
  ws = paste("ws_", i, sep = "")
  wd = paste("wd_", i, sep = "")
  pollutant = paste("O3_Avg_", i, sep = "")
  pollutionRose(combined.sites, ws, wd, pollutant, type =  "season", main = title)
#  assign(paste("rose", i, sep = "."), temp)
}
```
The only obvious difference is that the pollutant option is in pollutionRose but not in windRose. There are some NAs in the data. But windRose isn't bothered by them. Are there any places where pollutionRose would object to something that windRose finds ok?

**Comment by davidcarslaw** [comment]
Thanks for the report. Any chance you can send the data needed to run the code so I can check things?

**Comment by GeraldCNelson** [comment]
I have attached an RDS version of combined.sites.

 

The relevant code is as follows (some of the libraries are for preparation of the data that end up in combined.sites)

 

library(readr)

library(data.table)

library(ggplot2)

library(ggmap)

library(maps)

library(mapdata)

library(openair)

library(rgdal)

library(maps)

 

combined.sites <- readRDS("combined.sites.RDS")

 

locationNames.complete <- c("BangsCanyon", "BookCliffs", "Escalante", "Highline", "Ute")

locationNames.noWind <- c("DougPass", "GrandMesa")

locationNames.noT <- c("Palisade", "Pitkin")

locationNames.O3only <- c("Whitewater")

locationNames.particulates <- c("Powell_PM")

 

# windrose by season

for (i in c(locationNames.complete, locationNames.noT)) {

  print(paste("working on ", i))

  title = paste(i,  'wind roses, by season')

  ws = paste("ws_", i, sep = "")

  wd = paste("wd_", i, sep = "")

  temp <- windRose(combined.sites, ws, wd, type =  "season", main = title, key.footer = "miles/hour")

  assign(paste("rose", i, sep = "."), temp)

}

 

# pollutionRose by season

for (i in c(locationNames.complete, locationNames.noT)) {

  print(paste("working on ", i))

  title = paste(i,  'pollution roses, by season')

  ws = paste("ws_", i, sep = "")

  wd = paste("wd_", i, sep = "")

  pollutant = paste("O3_Avg_", i, sep = "")

  temp <- pollutionRose(combined.sites, ws, wd, pollutant, type =  "season", main = title)

#  assign(paste("rose", i, sep = "."), temp)

}

 

I’d also like to make the following work.

# ozone cross with particulates

rose.O3.particulates <- pollutionRose(combined.sites, ws = "ws_Pitkin", wd = "wd_Pitkin", 

                                      pollutant = "O3_Avg_Pitkin",  type = "pm10_Powell")

 

this gives me the error Error in e2[[j]] : subscript out of bounds

 

 

Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d

**Comment by GeraldCNelson** [comment]
PS Here’s a web site (in development) that uses openair to create some windRoses. It’s a bit slow to load because it’s downloading a bunch of data. 

https://nutrientmodeling.shinyapps.io/grand_valley_ozone_monitoring/

 

 

Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d

**Comment by davidcarslaw** [comment]
Thanks. I cannot see the data. Any chance you can send this directly to david.carslaw@york.ac.uk? Thanks.

**Comment by davidcarslaw** [comment]
I think you need to be more explicit when you call the function. For the `pollutionRose` bit, try:

`pollutionRose(combined.sites, ws = ws, wd = wd, pollutant = pollutant, type =  "season", main = title)`

On the other question I think I need to catch missing 'types' (in this case pm10_Powell). For now, try:

```
pollutionRose(combined.sites[!is.na(combined.sites$pm10_Powell), ], ws = "ws_Pitkin", wd = "wd_Pitkin", pollutant = "O3_Avg_Pitkin", type = "pm10_Powell")
```
![image](https://user-images.githubusercontent.com/1236491/28528159-d775f2c8-7084-11e7-8b66-a7159fce7b68.png)

I will have a look at fixing this in the function. Thanks for the report.

**Comment by GeraldCNelson** [comment]
Thanks for the quick response! I thought I had tried eliminating NAs but must have missed something.

 

 

Gerald C. Nelson

Professor Emeritus, UIUC

+1 217-390-7888 (cell)

+1 970-639-2079 (land line)

http://bit.ly/1arho7d
