### ISSUE TITLE
Calculate backward trajectories using a different meteorological data

### ISSUE THREAD

**Issue by jfmendeze** [davidcarslaw/openair#119]
Dear David,
Thanks for your valuable code.

I ran your code sucessfully for Colombian cities (off the  web-servers at King’s College London), using NCEP/NCAR Reanalysis data.

Do you know if exist a way to run your code with GDAS1, to calculate backward trajectories?

I am an apprenti, so I appreciate your patient and time

**Comment by schonhose** [comment]
Hysplit uses the control file to provide the meteo files to the model. In order to use GDAS1 you need to modify the CONTROL file, this is something that can be done in R. I made some modifications to allow the additional use of GDAS1, GDAS0p5 en NARR meteo.

**Comment by jfmendeze** [comment]
I am an apprenti in R. Would you give me some general steps in order to modify the CONTROL file?. I appreciate so much your help
