### ISSUE TITLE
timePlot, timeVariation inconsistent labelling

### ISSUE THREAD

**Issue by FlorentinBulotUoS** [davidcarslaw/openair#131]
Hello,

The labeling of the plots with the functions timePlot, timeVariation when plotting several pollutants with these functions. I have noticed this inconsistency on different datasets so I came back to the manual to test it with the code from the manual page 150.

When I  try:
```
data(mydata)
timePlot(selectByDate(mydata, year = 2003, month = "aug"),
         pollutant = c( "nox", "o3","pm25", "pm10", "ws"))

```
I obtain this plot:
![noxo3pm25pm10ws](https://user-images.githubusercontent.com/32537171/37358913-31256810-26e4-11e8-9cb1-c2fdcbbcd74b.png)

When I try:
```
data(mydata)
timePlot(selectByDate(mydata, year = 2003, month = "aug"),
         pollutant = c( "o3","pm25", "pm10", "ws","nox"))
```
 
I obtain this plot:
![o3pm25pm10wsnox](https://user-images.githubusercontent.com/32537171/37358967-50cedcb4-26e4-11e8-994d-d06bf9a3216e.png)

If you check the name of each plot, the first plot is in the first case NOx and in the second case it is O3 but the data is the same.

I have not yet tested it with the other plot functions but there may be a similar issue.

Thank you for your help,
Florentin.

**Comment by davidcarslaw** [comment]
Thanks for this. Yes, this is a result of changing some of the dependent packages. Should be fixed now.

**Comment by FlorentinBulotUoS** [comment]
Thank you very much for your help.
I have tested it and it works correctly.
