### ISSUE TITLE
timeAverage and selectByDate not selecting date range

### ISSUE THREAD

**Issue by FlorentinBulotUoS** [davidcarslaw/openair#132]
Hello,

With the function timeAverage with the start.date parameter. When I type:
`daily <- timeAverage(mydata, avg.time = "day",start.date="2004-01-29")`

daily contains all the initial values, not only the ones after “2004-01-29”. 

The same issue exists with the selectByDate function:
`selectByDate(mydata,start="2004-03-29")`
returns all the data.

`data.1999 <- selectByDate(mydata, start = "1999-01-01", end = "1999-12-31")`
Returns the following error message:
```
Warning messages:
1: All formats failed to parse. No formats found. 
2: All formats failed to parse. No formats found. 
```

Thank you for your help,
Florentin.

**Comment by davidcarslaw** [comment]
Hi

Thanks for the report.

For the first, the `start.date` is meant to help with padding-out the data. A typical example would be a time series that started half-way through a month but you want to fill in the initial (missing) dates. In your case the data is present, so it just averages what you have.

On the second and third, I have just committed a fix that should mean they both now work.

Do you want to try the GitHub version and let me know if you still have a problem.

**Comment by FlorentinBulotUoS** [comment]
I have tried it on the GitHub version, and it now works perfectly fine. Thanks a lot!
