### ISSUE TITLE
hour-day.csv example dataset not found

### ISSUE THREAD

**Issue by vermen76** [davidcarslaw/openair#133]
Hello,

In the OpenAir manual it is written that the example dataset hour-day.csv is provided but I can't find it in the data folder of the openair library. Do you have any suggestion in order to find it?

Thank you very much in advance.

**Comment by JocelynRM** [comment]
I found it here: http://www.erg.kcl.ac.uk/downloads/Policy_Reports/.Trash-0/files/

**Comment by taposhisarma** [comment]
> I have a copy of it if you still need it.

hey can you send it to taposhisharma@yahoo.co.in

**Comment by JocelynRM** [comment]
Oh, it’s been awhile. I can find it for you on Monday when I’m back in the office. 

Jocelyn

**Comment by taposhisarma** [comment]
> Oh, it’s been awhile. I can find it for you on Monday when I’m back in the office.
> 
> Jocelyn
> Thanks a lot. I will be waiting for your mail.

**Comment by JocelynRM** [comment]
I emailed it to you.

Jocelyn

**Comment by afcorral** [comment]
Could you be able to upload the hour-day.csv file here? Thank you so much!

**Comment by JocelynRM** [comment]
Hmmm...it won't let me post a .csv

**Comment by dimpk25** [comment]
Can someone please share the hour-day.csv file. kaushikdimple11@gmail.com here is my email id. Thanks in advance.

**Comment by JocelynRM** [comment]
[hour-day.csv.zip](https://github.com/davidcarslaw/openair/files/3768887/hour-day.csv.zip)

**Comment by JocelynRM** [comment]
> Can someone please share the hour-day.csv file. [kaushikdimple11@gmail.com](mailto:kaushikdimple11@gmail.com) here is my email id. Thanks in advance.

See above.

**Comment by jack-davison** [comment]
Closing as the openair manual has been superseded by the openair book, which is a fully online resource found [here](https://bookdown.org/david_carslaw/openair/). The openair book is fully reproducible and self-contained, which avoids issues with .csv files disappearing!

**Comment by JocelynRM** [comment]
Excellent!
