### ISSUE TITLE
disable npoints in trajPlot

### ISSUE THREAD

**Issue by masabhathini** [davidcarslaw/openair#135]
Hi David,
Here, I expecting a quick look on this.
I plotted trajectories for a long period of data. For this I have used trajPlot().
I want to disable the npoint. 
The code and plot is attached here.

trajPlot(s07,type=c("hh","mm"),parameters=NULL,orientation=c(90,0,0),projection="mercator",cols = "blue",main="July Density Trajectory Plot YAG(3000AGL:1948-2017)",map=TRUE,map.fill=FALSE,grid.col="gray",par.settings=list(fontsize=list(text=18)),npoints=120,lwd=0.05)

![yag_07-test](https://user-images.githubusercontent.com/25902165/37817155-c7353c0e-2e9b-11e8-9a2c-43db43e77e8f.png)

Thanks & regards
Sateesh

**Comment by davidcarslaw** [comment]
Apologies it has taken so long to get around to this. You can now set `npoints = NA`, which will suppress the plotting of interval points.

**Comment by masabhathini** [comment]
It is giving error on the display......
Image is attached here.

![s01-test](https://user-images.githubusercontent.com/25902165/38409214-24b98ab2-399e-11e8-9cae-fc47a3b7b367.png)

**Comment by masabhathini** [comment]
Is there any alternate solution to reduce the size of the npoint=120 ?

**Comment by jack-davison** [comment]
Closing stale issue. At time of writing (v 2.14.0) `npoint = NA` does work:

```r
trajPlot(openairmaps::traj_data, npoints = NA)
```
![image](https://user-images.githubusercontent.com/45171616/216983925-31e49ba2-c720-41cf-9153-212ed41bf585.png)
