### ISSUE TITLE
Creating polar plots but missing weather data?

### ISSUE THREAD

**Issue by lauthiamkok** [davidcarslaw/openair#14]
I have these data below, for instance, but I don't have the weather data for wind speed and wind direction,

```
    	timestamp	humandate		particle_concentration	
    1	1412877113	09-10-2014 13:51	2.5	
    2	1412876508	09-10-2014 13:41	4.5
    3   1412876508	09-10-2014 13:41    6.6
    4   1412877118	09-10-2014 13:51    7.1
```

so when I run this line below,

`polarPlot(dat, pollutant = "raw_particles", uncertainty = TRUE)`

I get this error, 

```
Can't find the variable(s) wd ws 
Error in checkPrep(mydata, vars, type, remove.calm = FALSE) : 
```

I don't know if I can get the missing data from elsewhere, but I am told that openair package provides easy access to UK air quality monitoring station data, including several stations in London. These data will automatically include wind speed and direction (ws and wd). This capability is provided by openair's importAURN and importKCL functions.

But when I tried to fetch the data from this line that I took from this site,

`> kc1 <- importAURN(site = "kc1", year = 2011:2012)`

result:

```
KC1_2011 does not exist - ignoring that one.
KC1_2012 does not exist - ignoring that one.
Error in (function (x, ...)  : argument "x" is missing, with no default
```

What do I actually need to fetch the data from the data station? Do I need a site code, such as KC1 or MY1?
    ....

**Comment by davidcarslaw** [comment]
There is a problem at the moment with accessing the data from UK sites at the moment (the webserver was attacked and is currently down - hopefully it will be working again soon). This affects the `importAURN` function. If your site of interest is in London, try `importKCL` with the option `met = TRUE`. That should give you met data form an average of several surface me sites in London.

```
 kc1 <- importKCL("kc1", year = 2011:2012, met = TRUE)
NOTE - mass units are used 
ug/m3 for NOx, NO2, SO2, O3; mg/m3 for CO
PM10_raw is raw data multiplied by 1.3
> head(kc1)
                 date      nox      no2       o3  so2        co pm10_raw
1 2011-01-01 00:00:00 43.29333 37.56333 14.66667 5.32 0.2320000  37.5375
2 2011-01-01 01:00:00 37.56333 28.65000 28.00000 2.66 0.2706667  36.1400
3 2011-01-01 02:00:00 32.94750 30.56000 17.50000 2.66 0.2320000  23.7900
4 2011-01-01 03:00:00 31.03750 29.12750 14.50000 2.66 0.2320000  21.0925
5 2011-01-01 04:00:00 31.03750 29.12750 16.50000 2.66 0.2320000  23.1075
6 2011-01-01 05:00:00 28.17250 26.26250 24.00000 2.66 0.1450000  18.9800
      pm10 pm25 v2.5 nv10 nv2.5                               site code
1 46.84896   39    7   NA    32 Kensington and Chelsea - North Ken  KC1
2 40.26810   30    6   NA    24 Kensington and Chelsea - North Ken  KC1
3 31.40653   31    8   NA    23 Kensington and Chelsea - North Ken  KC1
4 31.93858   29    8   NA    21 Kensington and Chelsea - North Ken  KC1
5 33.16059   25    6   NA    19 Kensington and Chelsea - North Ken  KC1
6 27.77461   23    7   NA    16 Kensington and Chelsea - North Ken  KC1
         ws       wd solar rain     temp       bp    rhum
1 0.9083333 307.5153     0    0 6.277083 1021.644 76.2564
2 1.1500000 305.2606     0  NaN 6.091667 1021.753 77.1714
3 1.3250000 299.2548     0  NaN 5.991667 1021.078 77.9644
4 1.4750000 288.3867     0  NaN 5.925000 1020.825 77.1714
5 1.0625000 261.1122     0  NaN 5.800000 1020.065     NaN
6 1.2250000 263.5514     0  NaN 5.575000 1020.065     NaN
```

The met data available through `importAURN` for recent years is based on regional modelled data using WRF.

**Comment by lauthiamkok** [comment]
Thank you very much for the help!
