### ISSUE TITLE
saving maps created with trajLevel function in another format 

### ISSUE THREAD

**Issue by repoepa2009** [davidcarslaw/openair#146]
Hi everyone,
Ive done a lot of PSCF and CWT analysis maps and im trying to export the maps created with these functions into GIS compatible formats (i.e. shapefile or dbf). I want to plot the maps with Arc-GIS.
Any suggestions on how to export those maps?
thanks.

**Comment by masabhathini** [comment]
HI,
I followed this method (Because, there is no direct method to export into other formats). This may helpful for you.

First, I created the df like this....... 

my <- trajLevel(trajBC, pollutant ="bc",statistic="pscf", parameters=NULL, orientation=c(90,0,0), projection="mercator", cols = "increment", main="pscf_Delhi(bc)-2016", map=TRUE, map.fill=FALSE, grid.col="gray",par.settings=list(fontsize=list(text=18)))

write.csv(my$data,file="Delhi2016bcpscf2016.csv")

Now, this CSV file contains "xgrid","ygrid" which indicates the lon, lat. 
This file can be used in ArcGIS. There you can load .shp.

Good luck.

**Comment by repoepa2009** [comment]
Thanks for the note and update,
This was helpful.

**Comment by jack-davison** [comment]
Closing this as it appears resolved. As a general point, data can be extracted from almost all `openair` plots using syntax along the lines of the below code chunk. Note that most `openair` plotting functions also possess the `plot` argument which can be used to suppress printing the plot itself.

``` r
openair_object <- openair::function(data)
openair_object$data
```

For `trajLevel()` in particular, the data can be extracted as described above. If you'd like to do spatial analysis in R, there are online [books](https://r-spatial.org/book/) written on this topic! I'll also plug [`openairmaps`](https://bookdown.org/david_carslaw/openair/maps-traj.html), which can create interactive versions of `openair` trajectory plots.

``` r
# get trajectory data
traj <- openair::importTraj()

# run trajLevel (optionally supressing plot)
level_obj <- openair::trajLevel(traj, plot = FALSE)

# see data
level_obj$data
#> # A tibble: 3,984 × 6
#> # Groups:   xgrid, ygrid [3,984]
#>    xgrid ygrid default                          count date                height
#>    <dbl> <dbl> <fct>                            <int> <dttm>               <dbl>
#>  1  -140    81 01 January 2009 to 31 December …     1 2009-11-30 18:00:00 0.0140
#>  2  -137    81 01 January 2009 to 31 December …     1 2009-11-30 18:00:00 0.0140
#>  3  -135    81 01 January 2009 to 31 December …     2 2009-11-30 18:00:00 0.0279
#>  4  -132    81 01 January 2009 to 31 December …     2 2009-11-30 18:00:00 0.0279
#>  5  -132    82 01 January 2009 to 31 December …     1 2009-12-01 00:00:00 0.0140
#>  6  -129    82 01 January 2009 to 31 December …     3 2009-11-30 18:00:00 0.0419
#>  7  -126    82 01 January 2009 to 31 December …     3 2009-11-30 18:00:00 0.0419
#>  8  -125    81 01 January 2009 to 31 December …     1 2009-11-30 15:00:00 0.0140
#>  9  -123    81 01 January 2009 to 31 December …     1 2009-11-30 15:00:00 0.0140
#> 10  -123    82 01 January 2009 to 31 December …     3 2009-11-30 18:00:00 0.0419
#> # … with 3,974 more rows

# use in other ways, e.g.
library(ggplot2)

mapdat <- map_data("world")

ggplot(level_obj$data, aes(xgrid, ygrid)) +
  geom_polygon(
    data = mapdat,
    aes(x = long, y = lat, group = group),
    color = "grey80",
    fill = "grey90"
  ) +
  geom_tile(aes(fill = count), alpha = .75) +
  scale_fill_gradientn(trans = "sqrt", colors = openair::openColours()) +
  coord_quickmap(xlim = c(-100, 75),
                 ylim = c(25, 90)) +
  theme_classic() +
  labs(x = NULL, y = NULL)
```

![](https://i.imgur.com/MyDLzDv.png)

<sup>Created on 2023-02-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
