### ISSUE TITLE
timeVariation x axis 

### ISSUE THREAD

**Issue by DafinaKikaj** [davidcarslaw/openair#147]

**Comment by masabhathini** [comment]
I have a temporary solution.
You add +14 hours to your input data......

sat <- read.csv(file="JDP2016AE33hour.csv",header=TRUE,sep=",")
sat$date <- as.POSIXct(strptime(sat$date, format="%Y-%m-%d %H",tz="GMT"))
sat$date <- as.POSIXct(strptime(sat$date, format="%Y-%m-%d %H",tz="GMT+14"))

timeVariation(sat,pollutant=c("eBC","BB"),main="Weekly Analysis of  eBC, BB Conc(ng/m3). 2016 [Jodhpur]")

![pic](https://user-images.githubusercontent.com/25902165/39304087-1f23c56c-4976-11e8-8983-82b0fe6e31a6.png)

good luck :)

**Comment by rs028** [comment]
I think `xlim=c(14,15)` does what you want.

**Comment by jack-davison** [comment]
Closing as the issue has no description; feel free to open a new issue describing your problem including a [reproducible example](https://www.tidyverse.org/help/) if appropriate. Cheers!
