### ISSUE TITLE
data.cap statistic is wrong calculated for wind direction

### ISSUE THREAD

**Issue by anxorl** [davidcarslaw/openair#148]
data.cap statistic always return 45 for wind direction

**Comment by davidcarslaw** [comment]
could you provide a few more details - which function is this? Thanks.

**Comment by anxorl** [comment]
David,
Thanks for your interest.
data.cap in a statistic option that is passed to the 'timeAverage' function. It supposes to count the amount of data available in the period (in percentage).
For example, 6 values per hour available in a 5-min basis result in a data.cap = 50
This function is defined on line 247 of timeAverage.R
I think the problem arises when the result of the statistic (calculated on line 499) is transformed to degrees on lines 504 and following

**Comment by davidcarslaw** [comment]
great - thanks. Should be fixed now.

**Comment by anxorl** [comment]
Thanks,
Now data.cap calculation works correctly auxiliary columns u and v are not deleted. I think this change need a new revision. Should I open a pull request?

**Comment by davidcarslaw** [comment]
yes please!

**Comment by anxorl** [comment]
Pull request opened. Thank for your work.
