### ISSUE TITLE
Map Options / Calculation Question

### ISSUE THREAD

**Issue by c422j381** [davidcarslaw/openair#15]
I have two questions: 

I would like to focus on a specific area of the U.S. Is there an easy / straightforward way to plot data on a map of only a single state? 

For the "difference" statistic, what is the mathematics behind this calculation. I assume that the number of trajectories for each grid cell is divided by the corresponding number of trajectories. For example,

trajectories per grid cell meeting threshold concentration / total number of trajectories meeting the threshold

this fraction would then be compared to 

trajectories per grid cell (all trajectories) / total number of trajectories 

The difference between these values is the difference.  Is that correct?

**Comment by davidcarslaw** [comment]
It is possible to show individual states in the development version of openair. You can supply the option `map.res = "state"` for trajectories based in the USA. It's not ideal and I am looking into better base maps. You can also restrict the area of interest (lat/lon) by suppling options for `xlim` and `ylim` (longitude / latitude), which might also help.

Your understanding of the difference plot is correct.
