### ISSUE TITLE
trajPlot 

### ISSUE THREAD

**Issue by Homaghasemi** [davidcarslaw/openair#153]
Hi, 

I am trying to plot backward trajectory with a link to the concentrations of CO2. The 96-hour and 3-hour intervals make my plot so messy and unreadable. Is there a way to use avg.time?  Or any suggestion to deal with that? 

Best, 
Homa

**Comment by masabhathini** [comment]
Hi Homa,
My advise is like this....
final <- merge(traj,co2,by="date",all=FALSE)
or 
You need to create the back trajectories at 3 hour interval.
try it.

regards,
Sateesh

**Comment by Catalyst82** [comment]
Good morning. Please, how do I download and install ''openair''? I have R installed on my laptop already. Thanks.

**Comment by Homaghasemi** [comment]
Hi Masabhathini, 
Thanks, but I know how to merge traj data with my measurement data. I need to know, is there a way to average the trajectories on the plot?

Thanks,
Homa

**Comment by Catalyst82** [comment]
@masabhathini @Homaghasemi @davidcarslaw 

Hello,
I have a problem with openair. I am using trajLevel and PSCF.

Below is the error I have been receiving :
Error in summarise_impl(.data, dots) :
Evaluation error: argument "x" is missing, with no default.

Kindly assist me out.

Best regards,

**Comment by Catalyst82** [comment]
@Homaghasemi 

Thanks. Once there's a solution to it, kindly let me know, please. Thanks.

**Comment by abhilashnr** [comment]
Hi,
Can I down load data that using for trajPlot as csv, for eg. london 2010?
Thanks
Regards,

**Comment by jack-davison** [comment]
Closing stale issue (5 years) which seems to be resolved (see example below). If your issues are persisting, feel free to reopen/open a new issue, including a [reproducible example](https://www.tidyverse.org/help/).

``` r
out <- 
  openair::trajLevel(openairmaps::traj_data,
                     pollutant = "pm2.5",
                     statistic = "pcsf")
```

![](https://i.imgur.com/5Jv7APL.png)

``` r

out$data
#> # A tibble: 5,432 × 6
#>    date                xgrid ygrid hour.inc default                        pm2.5
#>    <dttm>              <dbl> <dbl>    <dbl> <fct>                          <dbl>
#>  1 2010-04-15 00:00:00     0    52        0 15 April 2010 to 21 April 2010    22
#>  2 2010-04-15 00:00:00     0    52       -1 15 April 2010 to 21 April 2010    22
#>  3 2010-04-15 00:00:00     0    52       -2 15 April 2010 to 21 April 2010    22
#>  4 2010-04-15 00:00:00     1    52       -3 15 April 2010 to 21 April 2010    22
#>  5 2010-04-15 00:00:00     1    52       -4 15 April 2010 to 21 April 2010    22
#>  6 2010-04-15 00:00:00     1    52       -5 15 April 2010 to 21 April 2010    22
#>  7 2010-04-15 00:00:00     1    53       -6 15 April 2010 to 21 April 2010    22
#>  8 2010-04-15 00:00:00     2    53       -7 15 April 2010 to 21 April 2010    22
#>  9 2010-04-15 00:00:00     2    53       -8 15 April 2010 to 21 April 2010    22
#> 10 2010-04-15 00:00:00     2    53       -9 15 April 2010 to 21 April 2010    22
#> # … with 5,422 more rows
```

<sup>Created on 2023-02-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
