### ISSUE TITLE
Good morning. Please, how do I download and install ''openair''? I have R installed on my laptop already. Thanks. 

### ISSUE THREAD

**Issue by Catalyst82** [davidcarslaw/openair#154]

**Comment by Agriculturist** [comment]
[http://www.openair-project.org/GettingStarted/Default.aspx](url) .  For support questions like this one sites like stack exchange, quora, or experts exchange will get you a faster, more detailed, and possibly a more useful answer.    The issue reporting feature of github is better for reporting software bugs or requesting new features from developers.

**Comment by jack-davison** [comment]
For those searching through issues, installation instructions are found on the openair README/website: https://davidcarslaw.github.io/openair/.

```r
install.packages("openair")
```
