### ISSUE TITLE
Theilsen: Can't find the variable (...)

### ISSUE THREAD

**Issue by yanncohen** [davidcarslaw/openair#155]
Hello everybody,

I found this problem recently with the TheilSen function. Whatever the pollutant and the dataframe, when I try to run (here, for ozone):
`model=TheilSen(mconc_df, pollutant="o3", type='season')`

I get the following error message:
```
Can't find the variable(s) o3
Error in checkPrep(mydata, vars, type, remove.calm = FALSE) :
```
and I do not find what to do.
Has someone already experienced this message?

Thanks!

**Comment by davidcarslaw** [comment]
It would mean there is no column with a name 'o3'. What does `names(mconc_df)` show?

**Comment by yanncohen** [comment]
Thanks for your answer.
Indeed, the column for ozone was named "ws". I don't really understand why, since I precised it in the "mconf_df" definition (as follow):
```
mconc_df = data.frame(date=mdates,o3=mydata[1:n_months,2])
mconc_df[1:n_months,2] = monthly_anomalies[1:n_months]
```

Nevermind, I renamed the 2nd column as "o3" and went on. The new messages I get when trying to run the TheilSen function are:
```
Using 'season' in data frame and not date-based openair version. 
This may result in different behaviour compared with openair calculations.

Erreur : 'UQS()' can only be used within a quasiquoted argument
```

I do not get the meaning of the 1st problem, and what can make the second one happen.
Thanks in advance.

**Comment by yanncohen** [comment]
Hello David.
Sorry for disturbing, my problem is still current. I don't manage to run TheilSen function because of this variable name problem, whereas I indicated it in the "mconc_df" definition (as described above). I tried a trick to go further (still as described above), but it doesn't seem to be a solution. Nevermind, it should work with the "o3" name and I guess something is incorrect in the way the library is installed.

I tried again with Openair 2.4.2 version that I installed recently, but the result is the same as before.

Yann

**Comment by davidcarslaw** [comment]
I suspect this is a problem with how the date is formatted. Any chance you can send a sample of data?

**Comment by yanncohen** [comment]
Yes, of course. The mconc_df data frame is defined as (I only took the first 20 lines):
```
> mconc_df
          date          ws
1   1994-08-01          NA
2   1994-09-01          NA
3   1994-10-01          NA
4   1994-11-01          NA
5   1994-12-01  -6.0200000
6   1995-01-01  -5.7257143
7   1995-02-01  -3.6875000
8   1995-03-01  -5.5440000
9   1995-04-01 -14.4433333
10  1995-05-01          NA
11  1995-06-01          NA
12  1995-07-01 -12.3300000
13  1995-08-01          NA
14  1995-09-01          NA
15  1995-10-01          NA
16  1995-11-01  -5.8725000
17  1995-12-01  -4.1300000
18  1996-01-01  -5.9757143
19  1996-02-01 -11.5475000
20  1996-03-01          NA
```

**Comment by schonhose** [comment]
It seems your date is a string instead of a Posix datetime. Can you install the `lubridate` package and try the following: `mconc_df$date <- lubridate::ymd(mconc_df$date)`?

**Comment by yanncohen** [comment]
Same result. 'by' is NA.

**Comment by schonhose** [comment]
Try this `mconc_df$date <- lubridate::ymd_hms(paste(mconc_df$date, "00:00:00"))` and make sure that `o3` is a numeric column in your data frame.

**Comment by yanncohen** [comment]
Hi Schonhose,
Sorry for this late answer. Your solution works well!

Thank you both for your help.
