### ISSUE TITLE
aqstats returns 99% data capture for data that starts in April

### ISSUE THREAD

**Issue by stevecrawshaw** [davidcarslaw/openair#156]
df.br11.all <- importAURN(site = "BR11", pollutant = c("no2", "nox", "no"), year = 2017)
timePlot(df.br11.all, pollutant = "no2")
#Bristol temple way - starts 1st April 2017
stats <- aqStats(df.br11.all, pollutant = "no2")

**Comment by stevecrawshaw** [comment]
sorry posted before i'd finished!
I would expect data capture to show 75% in aqStats when monitoring starts in April

**Comment by davidcarslaw** [comment]
Thanks. The source of this problem is `importAURN` when less than one year is available. I have fixed that function to always return a full year so you will have to import the data again. I will have a look at `aqStats` also because that should catch partial years also...

**Comment by jack-davison** [comment]
Closing as this appears to be fixed.

``` r
library(openair)
df.br11.all <-
  importAURN(
    site = "BR11",
    pollutant = c("no2", "nox", "no"),
    year = 2017
  )
timePlot(df.br11.all, pollutant = "no2")
```

![](https://i.imgur.com/sPKsaqk.png)

``` r
#Bristol temple way - starts 1st April 2017
stats <- aqStats(df.br11.all, pollutant = "no2")
stats$dat.cap
#> [1] 75.02283
```

<sup>Created on 2023-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
