### ISSUE TITLE
Suggestion for another timeVariation chart

### ISSUE THREAD

**Issue by BhavShah01** [davidcarslaw/openair#159]
Dear authors,
Thanks for openair, it is one of my 'go to' packages day-to-day. 

I have a suggestion for something that I do to help visualise temperatures across different years using openair from the data I collect. It is a little bit of a cheat, using the wind direction and speed columns to coerce some nice visuals of temperature variations across the year for EDA. Comments are welcome.

mydata$wd = 360*(lubridate::decimal_date(mydata$date) - lubridate::year(mydata$date))
mydata$ws = lubridate::hour(mydata$date)
pollutionRose(mydata, pollutant="Temperature", type = "year")
polarFreq(mydata, pollutant = "Temperature", type = "year")

Is something that would be useful for the openair package?
Thanks for all the work on the package, 
Best, Bhav

**Comment by jobonaf** [comment]
Hi @BhavShah01 ,
you can achieve something similar (not radial) with **ggplot2** and **dplyr**:
```r
library(ggplot2)
library(dplyr)
library(lubridate)

ggplot(mydata %>%
         mutate(Year = year(date),
                Month = factor(month(date)),
                Hour = hour(date)) %>%
         group_by(Year,Month,Hour) %>%
         summarize(Temperature = mean(Temperature, na.rm=T)), 
       aes(x=Month, y=Hour, fill=Temperature)) +
  geom_tile() +
  facet_wrap("Year") +
  theme_classic() +
  scale_fill_distiller(palette = "Spectral")
```

**Comment by jack-davison** [comment]
> Hi @BhavShah01 , you can achieve something similar (not radial) with **ggplot2** and **dplyr**:
> 
> ```r
> library(ggplot2)
> library(dplyr)
> library(lubridate)
> 
> ggplot(mydata %>%
>          mutate(Year = year(date),
>                 Month = factor(month(date)),
>                 Hour = hour(date)) %>%
>          group_by(Year,Month,Hour) %>%
>          summarize(Temperature = mean(Temperature, na.rm=T)), 
>        aes(x=Month, y=Hour, fill=Temperature)) +
>   geom_tile() +
>   facet_wrap("Year") +
>   theme_classic() +
>   scale_fill_distiller(palette = "Spectral")
> ```

This can also be achieved inside of `{openair}` using the `trendLevel()` function:

```r
trendLevel(
  mydata,
  pollutant = "nox",
  x = "month",
  y = "hour",
  type = "year"
)
```
![image](https://user-images.githubusercontent.com/45171616/216970137-4f55cd06-af61-4d39-92b0-bed2cae2e9be.png)

Simply swap out "nox" for temperature (though, again, not radial!).
