### ISSUE TITLE
Forward and back trajectories

### ISSUE THREAD

**Issue by pharwarlay** [davidcarslaw/openair#16]
I have calculated forward and back trajectories using the UGAMP offline trajectory model driven by the 6 hourly ECMWF wind analyses data. Can I plot these trajectories, both forward and backward, in open air as I have not calculated them from HYSPLIT? All I have read about in the open air manual is plotting back trajectory pre-calculated from HYSPLIT.

**Comment by davidcarslaw** [comment]
You should be able to plot other trajectories provided a few requirements are met. Have a look at the help file for `importTraj`, in particular:

*Users can supply their own trajectory files to plot in openair. These files must have the following fields: date, lat, lon and hour.inc (see details below).* You can also have a look at an openair trajectory file by importing one of the pre-calculated data sets e.g. `traj = importTraj("london")`

**Comment by hasannawaz92** [comment]
How can I select site in Pakistan e.g., Lahore or Karachi using openair package?
