### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by mvieno** [davidcarslaw/openair#162]

**Comment by mvieno** [comment]
It seems like that the AURN data are only updated to the 2018-07-09, or do I do something wrong using the "importAURN" function?

 test <- importAURN(site="MH", year=2018)

....
4558 2018-07-09 21:00:00   MH Mace Head        NA  5.4  51.6
4559 2018-07-09 22:00:00   MH Mace Head        NA  6.2  50.9
4560 2018-07-09 23:00:00   MH Mace Head        NA  6.6  56.3
4561 2018-07-10 00:00:00   MH Mace Head        NA   NA    NA
4562 2018-07-10 01:00:00   MH Mace Head        NA   NA    NA
....
4665 2018-07-14 08:00:00   MH Mace Head        NA   NA    NA
4666 2018-07-14 09:00:00   MH Mace Head        NA   NA    NA
4667 2018-07-14 10:00:00   MH Mace Head        NA   NA    NA
4668 2018-07-14 11:00:00   MH Mace Head        NA   NA    NA
....
5017 2018-07-29 00:00:00   MH Mace Head        NA   NA    NA
5018 2018-07-29 01:00:00   MH Mace Head        NA   NA    NA
5019 2018-07-29 02:00:00   MH Mace Head        NA   NA    NA
5020 2018-07-29 03:00:00   MH Mace Head        NA   NA    NA
5021 2018-07-29 04:00:00   MH Mace Head        NA   NA    NA
5022 2018-07-29 05:00:00   MH Mace Head        NA   NA    NA
5023 2018-07-29 06:00:00   MH Mace Head        NA   NA    NA

many thanks

**Comment by davidcarslaw** [comment]
Apologies for the delay in responding. Seems the data on the server were not updated due to a permissions issue. Should be OK now.
