### ISSUE TITLE
Changing the font size of 'correlation' and 'observed' in multipanel Taylor plot using openair package in R

### ISSUE THREAD

**Issue by bappa10085** [davidcarslaw/openair#163]
I have created a multipanel Taylor plot using 'openair' package. I want to change the font size of 'correlation' and 'observed' and make it sentence case. At this time it is not possible using the package.

**Comment by masabhathini** [comment]
Dear Bappa,
for increasing size use "cex"
for various shapes use "pch"
Here, I added my sample code. It may helpful.




png("taylorDiagram_IPWV-IPWV3R.png",width = 3*300, height = 3*300, res=100)
TaylorDiagram(ssodr,obs="IPWV",mod="IPWV3R",group="stn",key.columns = 1,pch=seq(15,19),cex=2,par.settings=list(fontsize=list(text=18)),main="IPWV Vs IPWV3R")
dev.off()
![taylordiagram_ipwv-ipwv3d](https://user-images.githubusercontent.com/25902165/44072651-cb1b8174-9fad-11e8-94c3-2e23f0e9cb7b.png)

**Comment by bappa10085** [comment]
Thanks for your reply. But I want to make the correlation and observed as
sentence case i.e. it should be 'Correlation' and 'Observed'. I could able
to change the xlab and ylab but not these two.

**Comment by masabhathini** [comment]
Edit Line numbers 674; 682 in the code and compile.............
https://github.com/davidcarslaw/openair/blob/master/R/TaylorDiagram.R

**Comment by Caroline120** [comment]
is there a way to label the models in the plot

**Comment by jack-davison** [comment]
In all `{openair}` plots, font size can be controlled using the `fontsize` argument.

``` r
openair::TaylorDiagram(openair::mydata, "no2", "nox", fontsize = 20)
```

![](https://i.imgur.com/rwcshVW.png)

<sup>Created on 2023-09-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Note that this font size argument only applies when the functions themselves print the plot, not when it is stored. This issue details how you can handle this: https://github.com/davidcarslaw/openair/issues/228
