### ISSUE TITLE
metadata returned by importAURN is incomplete

### ISSUE THREAD

**Issue by stevecrawshaw** [davidcarslaw/openair#164]
site BR11 (Bristol Temple Way) is not returned from:
`meta <- importMeta(source = "aurn", all = TRUE)`

I'm unsure who maintains the list.

I think it would also be helpful for users if the "openair" site code was included in the [monitoring site metadata page](https://uk-air.defra.gov.uk/networks/site-info?uka_id=UKA00631)

**Comment by jmclaren17** [comment]
It would also be useful to see the QA/QC status of the monitored values through the importAURN tool.

**Comment by stevecrawshaw** [comment]
This seems to be resolved now..
