### ISSUE TITLE
clusterPlot plotting

### ISSUE THREAD

**Issue by masabhathini** [davidcarslaw/openair#165]
Dear David,

Here, I did the clusterPlot for one year backward & forward trajectories.
The percentage value is overlapping in Forward clusterPlot. 
Pls, can you resolve this issue.
Figures are attached here.

**Backward**
![bngbackward2017cluster4plotyeareuclidmercatorproj](https://user-images.githubusercontent.com/25902165/44384616-60788f00-a53a-11e8-92c6-c33c03595483.png)
**Forward**
![bngforward2017cluster4plotyeareuclidmercatorproj](https://user-images.githubusercontent.com/25902165/44384617-60788f00-a53a-11e8-99ae-9e6904ad9dc4.png)

**Comment by jack-davison** [comment]
This should now be fixed; please download dev version 2.16.0.9005 from GitHub and give it another go!

```r
# install.packages("remotes")
remotes::install_github("davidcarslaw/openair")
```
