### ISSUE TITLE
timeVariation (difference = TRUE) does not work for incomplete data sets

### ISSUE THREAD

**Issue by YuryZammit** [davidcarslaw/openair#166]
We have an issue with the latest build of OpenAir.  If we use the following command

`> timeVariation(mydata, pollutant = "PM10", group = "split.by", type="year", difference=TRUE) `

for data where the baseline covers only a few days (e.g. Tuesday to Saturday), we get the following error:

> Error in quantile.default(x, c((1 - conf.int)/2, (1 + conf.int)/2)) : 
>   missing values and NaN's not allowed if 'na.rm' is FALSE

This does not occur in a previous installation of OpenAir undertaken in February 2015, where warnings were issued such as:

> In mean.default (x) : argument is not numeric or logical: returning NA

but the charts were still plotted.

**Comment by dataknut** [comment]
Hi, I have just run in to the same problem. Was hoping to pass "na.rm = TRUE" through but doesn't seem to be supported :-(

**Comment by jack-davison** [comment]
This should now be fixed in the dev version.

``` r
library(openair)

mydata |>
  splitByDate("2000-01-10") |>
  timeVariation(
    pollutant = "pm10",
    group = "split.by",
    difference = TRUE,
    type = "year"
  )
```

![](https://i.imgur.com/478UgFu.png)

<sup>Created on 2023-03-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
