### ISSUE TITLE
debug timeVariation: error with "median" quantiles

### ISSUE THREAD

**Issue by VeraBer** [davidcarslaw/openair#169]
I noticed there is a problem with statistic="median": the function median.hilow has a wrong call to quantile:
median.hilow <- function(x, conf.int = 0.95, na.rm = TRUE, ...) {
  quant <- quantile(x, probs = **c(0.5, (1 - conf.int) / 2, (1 +
    conf.int) / 2)**, na.rm = na.rm)
  names(quant) <- c("Mean", "Lower", "Upper")
  quant
}
I think it should be:
median.hilow <- function(x, conf.int = 0.95, na.rm = TRUE, ...) {
  quant <- quantile(x, probs = **c(0.5, (1 - conf.int),  conf.int)**, na.rm = na.rm)
  names(quant) <- c("Mean", "Lower", "Upper")
  quant
}
Best regards

**Comment by davidcarslaw** [comment]
Yes, indeed! Good catch - thanks

**Comment by VeraBer** [comment]
you are welcome!
thank you for all your work in the openair project!!! Great tool!!!
 
 
 
 
-------Messaggio originale-------
 
Da: David Carslaw
Data: 27/09/2018 09:29:05
A: davidcarslaw/openair
Cc: VeraBer;  Author
Oggetto: Re: [davidcarslaw/openair] debug timeVariation: error with "median"
quantiles (#169)
 
Yes, indeed! Good catch - thanks
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

Mail priva di virus. www.avg.com
