### ISSUE TITLE
P_value in ModStats?

### ISSUE THREAD

**Issue by optimsari** [davidcarslaw/openair#17]
If we take this example:

 1-  modStats(mydata, mod = "no2", obs = "nox")
  default     n      FAC2        MB      MGE        NMB     NMGE
 RMSE         r        COE       IOA
 1 all data 63095 0.1703868 -129.6739 129.7277 -0.7252306 0.725532
 166.6203 0.7874487 -0.3374671 0.3312664

 Is there a way to return also the p-value?

We want to know if the correlation is significant or not?

**Comment by davidcarslaw** [comment]
Not possible at the moment. I would need to think about how to return that info. e.g. another column. I will have a think about that one.

**Comment by jack-davison** [comment]
Old issue, but this is easy enough to implement by switching `cor()` to `cor.test()`

```r
data <- importAURN(year = 2020)
modStats(data, "no2", "pm2.5")
```

```r
# A tibble: 1 × 12
  default      n  FAC2    MB   MGE   NMB  NMGE  RMSE     r         P   COE    IOA
  <fct>    <int> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>     <dbl> <dbl>  <dbl>
1 all data  6848 0.111  33.4  33.7  3.72  3.76  40.9 0.288 5.14e-131 -5.38 -0.686
```
