### ISSUE TITLE
Vertical motion method option in trajPlot

### ISSUE THREAD

**Issue by tepea** [davidcarslaw/openair#172]
Hello i am a newbie;

I am using local pre-calculated backtrajectories for trajPlot function but I don't know how can i choose Vertical Motion Method (This is really important for me) for backtrajectories when I am ploting trajPlot.

please, can you help me to resolve this.

**Comment by jobonaf** [comment]
Hi @tepea , 
with function `importTraj` you import pre-calculated backtrajectories and with `trajPlot` you plot them. Package **openair** does not run HYSPLIT. You can try package **[SplitR](https://github.com/rich-iannone/SplitR)**. In function `hysplit_trajectory` consider the parameter `vert_motion`:

> The methods are: 0 (input model data), 1 (isobaric), 2 (isentropic), 3 (constant density), 4 (isosigma), 5 (from divergence), 6 (remap MSL to AGL), 7 (average data), and 8 (damped magnitude).

**Comment by tepea** [comment]
@jobonaf Thank you for your answer.

I think openair is also run HYSPLIT (see in Appendix D in OpenAir manuel). I calculated my own backtrajectory data with instructions in Appendix D. I can plot clusters and trajectories, but still I don't know which vertical motion method is used!

Of course I can use SplitR, I was just curious. Thanks again. :)

**Comment by tepea** [comment]
When you are calculating your own data with procTraj function, you can change this part of the code for vertical motion method, model top (meters) and number of meteorological data files to use, respectively.

for vertical motion method  --> 0: data, 1: sob, 2: isen, 3: dens, 4: sigma 

`   x <- "echo 0 >>CONTROL
             echo 10000.0 >>CONTROL
             echo 3 >>CONTROL"
    write.table(x, bat.file, col.names = FALSE,
                row.names = FALSE, quote = FALSE, append = TRUE)`
