### ISSUE TITLE
add plot argument to windRose

### ISSUE THREAD

**Issue by renejuan** [davidcarslaw/openair#175]
I have created multiple windRose that I want to arrange in a single page (graphic device) but it does not work (or make it harder) because windRose will plot even if I tried to record the object in a variable (e.g., `wr <- windRose(mydata)`.

Maybe adding a plot argument is a good idea to control this behaviour.

**Comment by jobonaf** [comment]
Try this workaround
``` r
library(openair)
pdf(NULL)
wr1 <- windRose(mydata,angle = 10)
wr2 <- windRose(mydata,angle = 15)
wr3 <- windRose(mydata,angle = 30)
wr4 <- windRose(mydata,angle = 45)
dev.off()

library(gridExtra)
grid.arrange(wr1$plot, wr2$plot, wr3$plot, wr4$plot, nrow=2, ncol=2)
```

**Comment by jack-davison** [comment]
At time of writing, `windRose()` has a `plot()` method. Incidentally, it also has a `plot` argument which turns off printing the plot on the first function call.

```r
plt <- openair::windRose(openair::mydata, plot = FALSE)
plot(plt) \# or plt$plot
```
