### ISSUE TITLE
modStat Function

### ISSUE THREAD

**Issue by SaraTn27** [davidcarslaw/openair#177]
Hello OpenAir Users,

I have a problem using the "modStat" Function. I used this function to evaluate the model performance, unfortunately, the "NMB" parameter was not included in the statistical results. I even directly called this parameter in the command I used but it did not show up in the result (as stated by the manual). I would be grateful if you could help me in this regard.
Thanks a lot in advance!

**Comment by jobonaf** [comment]
Hello @SaraTn27 ,
maybe you are using v1-8.2 (see issue #71 ). This bug has been fixed in [v1.8-6](https://github.com/davidcarslaw/openair/blob/c34ac297a9c84f8525c865a77e70a89065ab4342/NEWS.md#openair-18-6)
