### ISSUE TITLE
trajplot mergedata

### ISSUE THREAD

**Issue by pavanaditya369** [davidcarslaw/openair#178]
Dear sir
I have issues merging hysplit back-trajectory data with my pollutant data set. I have followed instructions as mentioned in the openair tutorial. 
I have run the back trajectory run for 96 hours and have generated the following data as output

head(traj)
 receptor year month day hour hour.inc    lat    lon height pressure
1        1 2017     2   1    0        0 13.164 80.263   10.0    997.6
2        1 2017     1  31   23       -1 13.183 80.329   10.7    998.3
3        1 2017     1  31   22       -2 13.204 80.409   11.3    999.3
4        1 2017     1  31   21       -3 13.228 80.502   11.5   1000.5
5        1 2017     1  31   20       -4 13.255 80.606   11.4   1002.0
6        1 2017     1  31   19       -5 13.286 80.720   10.9   1003.6
                date2       date
1 2017-02-01 00:00:00 2017-02-01
2 2017-01-31 23:00:00 2017-02-01
3 2017-01-31 22:00:00 2017-02-01
4 2017-01-31 21:00:00 2017-02-01
5 2017-01-31 20:00:00 2017-02-01
6 2017-01-31 19:00:00 2017-02-01
1) When compared to manual, I am not getting the time for the second date datafield. How to resolve this?
2) How to merge my pollutant dataset with this data?

**Comment by masabhathini** [comment]
HI,
combined <- merge(traj,observed,by="date")

Good luck.

**Comment by pavanaditya369** [comment]
> combined <- merge(traj, observed, by = "date")
> head(combined)
 [1] date     receptor year     month    day      hour     hour.inc lat      lon      height   pressure date2    ws      
[14] wd       nox      no2      so2      co       pm25    
<0 rows> (or 0-length row.names)
Sir, as displayed above, the data is not merging. Does this have anything to do with the date and time column not being displayed in the head(traj) function  of hysplit back trajectory run using openair?

**Comment by jobonaf** [comment]
probably `date` has no common values (different classes?)
what is the structure of the 2 objects?
```r
str(traj)
str(observed)
```

**Comment by masabhathini** [comment]
Now, I understand your problem.
Your observed data time is at every 59th minute.
whereas, your hysplit trajectory data is 00th minute.
The solution for this ............

######
library(openair)
### read pm2.5 #####
obs <- read.csv(file="github.txt",header=TRUE,sep="")
obs$date <- as.POSIXct(obs$date,format="%d/%m/%Y %H:",tz="GMT+7") ## If your time zone is 6 UTC
### read trajectories #####
load("XXXX.RData")
### merging #####
final <- merge(traj,obs,by="date")
###################

**Comment by masabhathini** [comment]
A small modification.

library(openair)

read pm2.5
obs <- read.csv(file="github.txt",header=TRUE,sep="")
names(obs) <- c("date","time","ws","wd","pm25")
obs$date <- as.POSIXct(paste(obs$date,obs$time),format="%d/%m/%Y %H:",tz="GMT+7") ## If your time zone is 6 UTC

read trajectories
load("XXXX.RData")

merging
final <- merge(traj,obs,by="date")
###################

Try this.

**Comment by pavanaditya369** [comment]
Dear sir
When I try this code
obs <- read.csv(file="github.txt",header=TRUE,sep="")
The response is coming as
**Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  duplicate 'row.names' are not allowed**
Also, regarding the timezone, won't the code come as tz = "Etc/GMT-7" which has been mentioned in the tutorial? Because, if I type tz = "GMT+7", the software is not recognizing the timezone
**Warning messages:
1: In strptime(x, format, tz = tz) : unknown timezone 'GMT+7'
2: In as.POSIXct.POSIXlt(as.POSIXlt(x, tz, ...), tz, ...) :
  unknown timezone 'GMT+7'**

**Comment by masabhathini** [comment]
library(openair)

read pm2.5
obs <- read.csv(file="yourObservationPM25.txt",header=TRUE,sep="")
names(obs) <- c("date","time","ws","wd","pm25")
obs$date <- as.POSIXct(paste(obs$date,obs$time),format="%d/%m/%Y %H:",tz="Etc/GMT+7") ## If your time zone is 6 UTC

read trajectories
load("XXXX.RData")

merging
final <- merge(traj,obs,by="date")
###################

**Comment by pavanaditya369** [comment]
sir
I have tried the same. 
I have directly uploaded the csv file into the software by using code
**> obs <- read.csv("c:/users/pavan aditya/Documents/R/openair hysplit 2017.csv", header = TRUE, sep = "")
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  duplicate 'row.names' are not allowed**
But no change.

**Comment by pavanaditya369** [comment]
Dear sir
I have merged the results successfully
In my dataset, both time and date fields are in the same field. So, I had deleted the $time component from the code. The software merged the hysplit and my observed data successfully
I really thank you for your patience in guiding me sir.
