### ISSUE TITLE
trajCluster

### ISSUE THREAD

**Issue by masabhathini** [davidcarslaw/openair#181]
Dear David,
I am trying to plot trajCluster with year and season as follows.
trajCluster(traj,method="Euclid",n.cluster=4,col="jet",grid.col="grey",grid.alpha=0.2,lwd=6,map.fill=FALSE,map.cols = "transparent",map.alpha = 0.2,type=c("year","season"))
![image](https://user-images.githubusercontent.com/25902165/50341626-809a7800-0545-11e9-9f32-a5f05c23e09f.png)

one season is missing and result also not fruitful.
guide me in this regard.
regrads,
M. Sateesh
NCMRWF, INDIA.

**Comment by davidcarslaw** [comment]
Hi - any chance you could email the data frame to me so I can test it?

Thanks

David

**Comment by masabhathini** [comment]
[bakwardVSK500m2011-2016.zip](https://github.com/davidcarslaw/openair/files/2702831/bakwardVSK500m2011-2016.zip)
Thanks for quick reply.
####
> library(openair)
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

Matrix products: default
BLAS: /gpfs1/home/Libs/GNU/R/R-3.4.0/lib64/R/lib/libRblas.so
LAPACK: /gpfs1/home/Libs/GNU/R/R-3.4.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] openair_2.1-0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11        cluster_2.0.6       magrittr_1.5
 [4] maps_3.1.1          MASS_7.3-47         lattice_0.20-35
 [7] R6_2.2.1            rlang_0.1.1         stringr_1.2.0
[10] plyr_1.8.4          dplyr_0.5.0         tools_3.4.0
[13] grid_3.4.0          nlme_3.1-131        mgcv_1.8-17
[16] latticeExtra_0.6-28 DBI_0.6-1           lazyeval_0.2.0
[19] assertthat_0.2.0    tibble_1.3.3        Matrix_1.2-9
[22] RColorBrewer_1.1-2  mapproj_1.2-4       reshape2_1.4.2
[25] stringi_1.1.5       compiler_3.4.0      lubridate_1.6.0
[28] hexbin_1.27.1

**Comment by masabhathini** [comment]
Dear David,
Christmas Greetings.........
Here, One more bug in trajCluster()
![cluster4ploteuclidmercatorproj-ndl_trv](https://user-images.githubusercontent.com/25902165/50446676-385fc900-093c-11e9-8f81-a4ef902d7a96.png)

I tried the trajectories cluster for two stations. The station mark is not changed for the second station.
trajCluster(traj,method="Euclid",n.cluster=4,type="stn")

regards,
M. Sateesh

**Comment by masabhathini** [comment]
> Dear David,
> I am trying to plot trajCluster with year and season as follows.
> trajCluster(traj,method="Euclid",n.cluster=4,col="jet",grid.col="grey",grid.alpha=0.2,lwd=6,map.fill=FALSE,map.cols = "transparent",map.alpha = 0.2,type=c("year","season"))
> ![image](https://user-images.githubusercontent.com/25902165/50341626-809a7800-0545-11e9-9f32-a5f05c23e09f.png)
> 
> one season is missing and result also not fruitful.
> guide me in this regard.
> regrads,
> M. Sateesh
> NCMRWF, INDIA.
I have updated the openair 2.4-2 to 2.6-1
![cluster4plotyeareuclidmercatorproj-e04](https://user-images.githubusercontent.com/25902165/50447691-f5edba80-0942-11e9-8636-489ecdc1f019.png)
plotting of map is done. There is some error massage on it. 
What could be the error massage ?

**Comment by masabhathini** [comment]
> Dear David,
> Christmas Greetings.........
> Here, One more bug in trajCluster()
> ![cluster4ploteuclidmercatorproj-ndl_trv](https://user-images.githubusercontent.com/25902165/50446676-385fc900-093c-11e9-8f81-a4ef902d7a96.png)
> 
> I tried the trajectories cluster for two stations. The station mark is not changed for the second station.
> trajCluster(traj,method="Euclid",n.cluster=4,type="stn")
> 
> regards,
> M. Sateesh

In trajCluster plot of New Delhi, C3(yellow line) is coming from North west of New Delhi. But, In trajLevel of clusters showing C3 is coming from Arabian sea.

![cluster4ndl-cwt-aod](https://user-images.githubusercontent.com/25902165/50467002-bb2d6600-09c6-11e9-9bb2-a3a8967d0807.png)

**Comment by Jaip2018** [comment]
Hi Dawid and Sateesh 
I am trying to plot trajCluster with type season as follows.
trajCluster(traj, method = "Euclid", n.cluster = 4, plot = TRUE, type = "season", cols = c("yellow", "green", "blue", "red"), split.after = FALSE, map.fill = FALSE, map.cols = "transparent", map.alpha = 1, projection = "mercator", parameters = NULL, orientation = c(90,0,0), by.type = TRUE, origin = TRUE, lwd=4, grid.col="grey", grid.alpha=0.4, font.label= c(12, "bold", "red"), par.settings=list(fontsize=list(text=16)))

I am not getting as above plot which you plotted. 
![cluster](https://user-images.githubusercontent.com/42550319/51790028-0305ff80-21b6-11e9-8859-121f954cbaf6.png)

Please let me know what should do.

**Comment by masabhathini** [comment]
Dear Jai Prakash,

You need to pass xlim, ylim also.
................. ,xlim=c(40,100),ylim=c(-10,40)

regards,
M. Sateesh
