### ISSUE TITLE
Merge Hysplit output with Site observation data

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#184]
Hi Folks,
Is there any package or function that can help me to merge Hysplit output data with my site observation data?
We previously had the code in Appendix D. But they are not available now. 
I am wondering if there is a way that I can quickly merge my Hysplit output with site observation data. 
Thank you very much.
Yi

**Comment by lyggd** [comment]
Does anyone know how to do that? I remember in the old version of open-air manual we have one section on that. However, it is not in the updated version.

**Comment by masabhathini** [comment]
Dear lyggd,
`merge()`
This merge function will combine your station observation data to the Trajectory data.
You can also find examples in `http://www.havakalitesi.itu.edu.tr/R/OpenAir_Manual.pdf`.

regards,
Sateesh

**Comment by jack-davison** [comment]
Hi lyggd,

This is described in the [openair book](https://bookdown.org/david_carslaw/openair/trajectory-analysis.html#plotting-trajectories).

Best,
Jack
