### ISSUE TITLE
How to display only selected linear regression lines in grouped scatterPlot?

### ISSUE THREAD

**Issue by martinottopaul** [davidcarslaw/openair#185]
Hi,
when I create a scatterPlot, e.g. for a group of stations (group = "stations") and additionally activate "linear = TRUE", scatterPlot is plotting linear regression lines for every group item (in this case, for every station). So, I will have a lot linear regression lines in my scatterPlot. But, 

I just want to show one particular regression line (e.g. just for one station). 

Is it possible to select the regression line(s) that are plotted, when "linear = TRUE"? Or is it possible to add manually a regression line from a linear regression model object (I was just able to add horizontal or vertical lines with ref.y and ref.x)?

Thank you in advance and best regards,
Martin

**Comment by jack-davison** [comment]
Hi,

I'm afraid that fine level of control is not available in `{openair}`. Have you considered exploring alternative packages, like `{ggplot2}`? The `{ggplot2}` package is a lot more flexible and may better suit your needs.

``` r
library(ggplot2)
library(openair)

# get some data
dat <- importAURN(c("my1", "kc1"))

# time avg - make it a bit nicer to plot
dat <- timeAverage(dat, "day", type = "site")

# openair plot, for comparison
scatterPlot(
  dat,
  y = "nox",
  x = "o3",
  group = "site",
  linear = TRUE
)
```

![](https://i.imgur.com/mqysuo7.png)

``` r

# ggplot
plt <-
  ggplot(dat, aes(x = o3, y = nox, color = site)) +
  geom_point(alpha = .25) +
  theme_bw() +
  labs(y = quickText("NOx (ug/m3)"),
       x = quickText("O3 (ug/m3)"))

# both lines
plt + 
  geom_smooth(method = "lm")
#> `geom_smooth()` using formula = 'y ~ x'
#> Warning: Removed 16 rows containing non-finite values (`stat_smooth()`).
#> Warning: Removed 16 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/CgkSDZl.png)

``` r

# one line
plt +
  geom_smooth(method = "lm",
              data = dat[dat$site == "London Marylebone Road",])
#> `geom_smooth()` using formula = 'y ~ x'
#> Warning: Removed 12 rows containing non-finite values (`stat_smooth()`).
#> Removed 16 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/lWMvgOn.png)

``` r

# add the equation
mod <-
  lm(data = dat[dat$site == "London Marylebone Road",],
     formula = nox ~ o3)

eq <-
  paste0("London Marylebone Road: ",
         signif(mod$coefficients["o3"], 3),
         "[O3] + ",
         signif(mod$coefficients["(Intercept)"], 3),
         " / ",
         "R2 = ", round(summary(mod)$r.squared, 2))

plt +
  geom_smooth(method = "lm",
              data = dat[dat$site == "London Marylebone Road",]) +
  labs(subtitle = quickText(eq))
#> `geom_smooth()` using formula = 'y ~ x'
#> Warning: Removed 12 rows containing non-finite values (`stat_smooth()`).
#> Removed 16 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/IcpVDpv.png)

<sup>Created on 2023-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
