### ISSUE TITLE
importSAQN - same data request sometimes fails/succeeds

### ISSUE THREAD

**Issue by andyrm1** [davidcarslaw/openair#186]
I'm finding that data requests using importSAQN sometimes fail to find any data but sometimes succeed. Using the code below I intermittently get the first error message, but sometimes succeed to get the data. I presume this is a remote server issue (?) but wonder if there is a way to resolve?

> SAQNdata = importSAQN(site = "ABD3", year=2019, pollutant="pm10")

-----------------------------

_ABD3_2019 does not exist - ignoring that one.
Error: No data to import - check site codes and year.
In addition: Warning message:
In load(con, envir = .GlobalEnv) :
  InternetOpenUrl failed: 'The operation timed out'_

-----------------------------

_Warning message:
In importSAQN(site = "ABD3", year = 2019, pollutant = "pm10") :
  You have selected some data that is less than 6-months old.
 This most recent data is not yet ratified and may be changed
 during the QA/QC process. For complete information about the 
ratification status of a data set, please use the online tool at:_

**Comment by jack-davison** [comment]
Hi Andy,

I'm going to close this as this issue hasn't been looked at, and I expect the servers and data have all been updated and shifted around since 2019. If this is still an ongoing issue, feel free to reopen the issue and we'll have a look for you.

Thanks,
Jack

``` r
(SAQNdata = openair::importSAQN(site = "ABD3",
                                year = 2019,
                                pollutant = "pm10"))
#> # A tibble: 8,760 × 4
#>    date                 pm10 site                           code 
#>    <dttm>              <dbl> <chr>                          <chr>
#>  1 2019-01-01 00:00:00 14.4  Aberdeen Union Street Roadside ABD3 
#>  2 2019-01-01 01:00:00 14.4  Aberdeen Union Street Roadside ABD3 
#>  3 2019-01-01 02:00:00 12.3  Aberdeen Union Street Roadside ABD3 
#>  4 2019-01-01 03:00:00 17.0  Aberdeen Union Street Roadside ABD3 
#>  5 2019-01-01 04:00:00 14.5  Aberdeen Union Street Roadside ABD3 
#>  6 2019-01-01 05:00:00 11.7  Aberdeen Union Street Roadside ABD3 
#>  7 2019-01-01 06:00:00  9.90 Aberdeen Union Street Roadside ABD3 
#>  8 2019-01-01 07:00:00  6.46 Aberdeen Union Street Roadside ABD3 
#>  9 2019-01-01 08:00:00  3.92 Aberdeen Union Street Roadside ABD3 
#> 10 2019-01-01 09:00:00  9.42 Aberdeen Union Street Roadside ABD3 
#> # … with 8,750 more rows
```

<sup>Created on 2023-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
