### ISSUE TITLE
more locations and different elevations/ backward trajectory 

### ISSUE THREAD

**Issue by Homaghasemi** [davidcarslaw/openair#189]
Dear All, 

I have backward trajectory calculations by HYSPLIT which include 4 different locations at five different elevations. Is there a way to analyze this data as a whole in openair or I have to subset data by locations and elevations? 

Best, 
Homa

**Comment by jack-davison** [comment]
Closing stale issue (4 years).

If you have columns of your data which distinguish all of these sites/heights, you can use the "group" or "type" arguments to split up your trajectory plots, e.g.,

``` r
library(openair)

traj <-
  dplyr::bind_rows(
    "lon" =  importTraj("london"),
    "ah" = importTraj("ah"),
    "yw" = importTraj("yw"),
    .id = "site"
  )

traj <-
  selectByDate(traj, month = 1, day = 1:5)

trajPlot(traj, group = "site")
```

![](https://i.imgur.com/ZBpI8UC.png)

``` r
trajPlot(traj, type = "site")
```

![](https://i.imgur.com/wOTD4ki.png)

<sup>Created on 2023-03-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
