### ISSUE TITLE
Bug in summaryPlot

### ISSUE THREAD

**Issue by dpinxter** [davidcarslaw/openair#19]
summaryPlot with period="months" gives an error. The following example (modified from help)

```
library(openair)

# load example data from package
data(mydata)

# do not clip density plot data
summaryPlot(mydata, period="months",clip = FALSE)
```
gives this output on my machine (Win 7 64bit, R, RStudio, openair, all up to date versions)

```
    date1     date2        ws        wd       nox       no2        o3      pm10       so2 
 "POSIXt" "POSIXct" "numeric" "integer" "integer" "integer" "integer" "integer" "numeric" 
       co      pm25 
"numeric" "integer" 
Error in strsplit(avg.time, " ", fixed = TRUE) : object 'avgt' not found
```

**Comment by davidcarslaw** [comment]
Thanks. This bug should have been fixed a while ago - try installing the Github version of openair and you should be OK.

**Comment by dpinxter** [comment]
Great, it does work with the Github version. Thanks.
