### ISSUE TITLE
Suppress year on calendar plot

### ISSUE THREAD

**Issue by rafaelrsss** [davidcarslaw/openair#190]
Calendar plot is amazing but I usually plot a mean of 15 years and not 1 specifc year. Does anybody knows how to supress or not display the year besides the month name on the calendar?

Thanks.

**Comment by jack-davison** [comment]
Closing as a duplicate of https://github.com/davidcarslaw/openair/issues/150 so do continue the conversation there. We'll look into this as it is a nice enhancement for use cases like yours!
