### ISSUE TITLE
importTraj

### ISSUE THREAD

**Issue by tepea** [davidcarslaw/openair#198]
Hi;

After I updated openair to version 2.6-5, when I try to use importTraj for my local data, I am geting an error like below. Before this version I was able to run importTraj for same data.

`traj <- importTraj(site = "Akdeniz_Muh", year = 2011:2015, local = "E:/Users/tepea/Desktop/ahmet_traj/TrajProc2/")` 

`Error in UseMethod("close") : 
  no applicable method for 'close' applied to an object of class "character"`

**Comment by jwsaf** [comment]
Hi there

I also got such an error message:

library(devtools)
devtools::install_github("rich-iannone/SplitR", force=TRUE)

library(SplitR)

library(magrittr)

setwd("C:/Users/User/Documents/R/win-library/3.5/SplitR") 

library(tidyverse)

library(tidyr)

library(dplyr)


trajectory <- 
  hysplit_trajectory(
    lat = -25.73,    ## Pretoria
    lon = 28.20,
    height = 250,
    duration = 72,
    run_period = c("2017-04-28"),  
    daily_hours = c(0, 6, 12, 18),
    direction = "backward",
    met_type = "reanalysis",
    extended_met = TRUE)


names(trajectory)

[1] "receptor" "year"     "month"    "day"      "hour"     "hour.inc" "lat"      "lon"      [9] "height"   "pressure" "date2"    "date" 


trajectory2 <- filter(trajectory, !is.na(day))


saveRDS(trajectory2, "trajectory2.RData")

library(openair)

glimpse(trajectory2)

Observations: 292
Variables: 12
$ receptor <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
$ year     <dbl> 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 1...
$ month    <int> 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...
$ day      <int> 28, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 2...
$ hour     <int> 0, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, ...
$ hour.inc <dbl> 0, -1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17...
$ lat      <dbl> -25.730, -25.717, -25.702, -25.683, -25.663, -25.639, -25.614, -25.589, -25.5...
$ lon      <dbl> 28.200, 28.270, 28.341, 28.413, 28.487, 28.562, 28.640, 28.712, 28.772, 28.81...
$ height   <dbl> 250.0, 255.1, 260.5, 266.1, 272.0, 278.3, 285.0, 290.9, 294.5, 296.0, 295.3, ...
$ pressure <dbl> 850.4, 850.8, 851.3, 851.8, 852.3, 852.9, 853.5, 854.3, 855.3, 856.4, 857.4, ...
$ date2    <dttm> 2017-04-28 00:00:00, 2017-04-27 23:00:00, 2017-04-27 22:00:00, 2017-04-27 21...
$ date     <dttm> 2017-04-28, 2017-04-28, 2017-04-28, 2017-04-28, 2017-04-28, 2017-04-28, 2017...



traj2 <- importTraj(site = "trajectory2", year = 17, local = "C:/Users/User/Documents/R/win-library/3.5/SplitR/")

_**Error in UseMethod("close") : 
  no applicable method for 'close' applied to an object of class "character"
In addition: Warning message:
file ‘trajectory217.RData’ has magic number 'X'
  Use of save versions prior to 2 is deprecated**_

**Comment by jack-davison** [comment]
Closing stale issue (4 years).

If your problem is persisting, please feel free to reply in this issue with one or more of the files you're trying to read in. This will help us recreate your issue on our computers to diagnose what may be going on.

Cheers,
Jack
