### ISSUE TITLE
import Airbase daily data

### ISSUE THREAD

**Issue by jobonaf** [davidcarslaw/openair#2]
Many PM10 and PM2.5 stations in Airbase provide only daily (not hourly) data. It would be useful to access them through `importAirbase`

**Comment by davidcarslaw** [comment]
Yes indeed. This is something I intend implementing soon - hopefully for the next release.

**Comment by jack-davison** [comment]
Closing very old issue. Airbase data can be imported w/ [saqgetr](https://github.com/skgrange/saqgetr) or `openair::importEurope()`.
