### ISSUE TITLE
How to import data with odd time intervals into openair?

### ISSUE THREAD

**Issue by MatthiasKetzel** [davidcarslaw/openair#20]
I got measured data from filter samples over several days having the structure:

StartDate         EndDate           Pollutant_1 Pollutant_2 Pollutant_3
Period1start    Period1end  XX1 YY1     ZZ1
Period2start    Period2end  XX2 YY2     ZZ2
Period3start    Period3end  XX3 YY3     ZZ3
...

The lengths of the measuring periods are / can be different each time between days / weeks there might be gaps/overlaps etc.
Has anyone a good idea how to import / process/ plot data of such structure?
We want to plot /compare these data with modelled data that are of course continuous in the time dimension.

**Comment by jack-davison** [comment]
Closing this stale issue. If you are still interested in continuing this conversation, feel free to reopen it.

Below I've demonstrated some ways to mess around with irregular data. If there's something specific you'd like to do with your irregular data, feel free to provide a [reproducible example](https://www.tidyverse.org/help/).

----

``` r
library(openair)

data <- selectByDate(mydata, year = 2005)

# model irregular data
irregular <- dplyr::slice_sample(data, prop = .05)

timePlot(irregular)
```

![](https://i.imgur.com/WauPBAU.png)

``` r

# fill with NA using timeAverage
na_insert <- timeAverage(irregular, "hour")

timePlot(na_insert)
```

![](https://i.imgur.com/UtZIj9g.png)

``` r

# gap fill to create a step chart
filled <- tidyr::fill(na_insert, nox)

timePlot(filled)
```

![](https://i.imgur.com/XKelNsn.png)

<sup>Created on 2023-02-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
