### ISSUE TITLE
WindrRose plot 

### ISSUE THREAD

**Issue by vrinanand** [davidcarslaw/openair#201]
In the windRose plot the direction of winds is it blowing from that direction or the winds are blowing to a particular direction

**Comment by davidcarslaw** [comment]
Direction **from**

**Comment by vrinanand** [comment]
when I check the windRose with the windrose from Origin it is showing the opposite. For eg. in origin when I choose and plot Flow vector(blowing to)  I get the same plot as the one using openair windrose function.

**Comment by jack-davison** [comment]
Can confirm it is direction *from*.

``` r
dat <- data.frame(wd = rep(90, 100), ws = rep(10, 100))
dat$date <- Sys.Date()

openair::windRose(dat)
```

![](https://i.imgur.com/Cnxlhme.png)

``` r

openair::calendarPlot(dat, "ws", annotate = "wd")
```

![](https://i.imgur.com/JMF22Dn.png)

<sup>Created on 2023-02-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
