### ISSUE TITLE
TheilSen 

### ISSUE THREAD

**Issue by dyun33** [davidcarslaw/openair#202]
First, thank you very much for making this awesome package. I believe my case is a bit unique and hopefully, there is a solution to my problems.

I am working with environmental monitoring data collected in South Florida (Everglades). Due to its latitude, there is a different type of seasonality, which is wet (May to November) and dry (December to April) season. When I use 'TheilSen' function even with 'deseason = FALSE', I got this message 'Error in seq.Date(start.date, end.date, by = interval) :  invalid string for 'by''. Before I run the code, I averaged the data by the season (W and D) and crated a new column 'date' where wet season = YYYY-07-01 and dry season  = YYYY-01-01. I also try YYYY-06-01 for wet season. I look into a source code and found that there is no option for other time intervals than month and year. Is there any way I can use the seasonal data, instead of creating new dataframe separately for dry and wet?

Thank you agani.

**Comment by davidcarslaw** [comment]
Hi 

Thanks for the message. Can you confirm the openair version being used? Also, it might be better to send some example data along with the code you are trying to use so I can look at it.

**Comment by dyun33** [comment]
Thank you for the fast response. Please see the workflow below which I follow in order.

- My packageVersion("openair") is: ‘2.6.5’
- I attach data and code files in Zip format: 
[Github_question.zip](https://github.com/davidcarslaw/openair/files/3258638/Github_question.zip)

The data consists of four columns: date, water_year (which is different from a calendar year. For example,  from May 1, 1999, to April 31, 2000, is water year 2000.), Season (May to November = wet season, December to April  = dry season), and respiration rate. 

1) After data is imported, I run the following code:
`df$date <- as.Date(df$date)
MKresults <- TheilSen(df, pollutant = "respiration", ylab = "Respiration rate", deseason = F, slope.percent = TRUE)`
, then I get this message "Error in seq.Date(start.date, end.date, by = interval) : invalid string for 'by'". I believed that the error is caused by date in irregular interval.

2) So, I average respiration rate by water_year and season and then created a new date column, which defines wet season = YYYY-07-01 and dry season = YYYY-01-01.
`df.1 <- df %>% 
  group_by(water_year, Season) %>% 
  mutate(R.avg = mean(respiration, na.rm=T),
         new_month = if_else(Season == "Wet", 7, 1),
         new_date = paste(water_year, new_month, "01", sep="-")) %>%
  ungroup() %>%
  distinct(water_year, Season, .keep_all = TRUE) %>% 
  rename(date_old = date,
         date = new_date)
df.1$date <- as.Date(df.1$date)
MKresults <- TheilSen(df.1, pollutant = "R.avg", ylab = "Respiration rate", deseason = F, slope.percent = TRUE)`
Unfortunately, I got the same error. Due to this error, I realized that I cannot use my two season system with TheilSen. 

3) So, I decided to average data only by water year although this step can reduce the effect of important outliers:
`df.2 <- df %>% 
  group_by(water_year) %>% 
  mutate(R.avg = mean(respiration, na.rm=T)) %>% 
  ungroup() %>%
  distinct(water_year, .keep_all = TRUE) #%>% 
df.2$date <- as.Date(df.2$date)
MKresults <- TheilSen(df.2, pollutant = "respiration", ylab = "Respiration rate", deseason = F, slope.percent = TRUE)`
But I still got the same error. Only reason for the error I can think of is date, which is irregular. 

4) Finally, I averaged by water year and create a new date column with fixed month and day (01-01)
`df.3 <- df %>% 
  group_by(water_year) %>% 
  mutate(R.avg = mean(respiration, na.rm=T),
         new_date = paste(water_year, "01-01", sep="-")) %>%
  ungroup() %>%
  distinct(water_year, .keep_all = TRUE) %>% 
  rename(date_old = date,
         date = new_date)
df.3$date <- as.Date(df.3$date)
MKresults <- TheilSen(df.3, pollutant = "R.avg", ylab = "Respiration rate", deseason = F, slope.percent = TRUE)`
The last code works and produce a result. However, this analysis was not my original goal: I want to use raw data (irregularly distributed date) and want to deseason (if possible) as seasonality is big issue in the system. 

Any help and insight will be greatly appreciated. Thank you again for creating the package and your help. 

Best, 

Dong

**Comment by davidcarslaw** [comment]
The date needs to be formatted as POSIXct, so

`df$date <- lubridate::ymd(df$date, tz = "UTC")`

I would then show the trends separately by season because of the nature of this data e.g.

`MKresults <- TheilSen(df, pollutant = "respiration", ylab = "Respiration rate", deseason = F, slope.percent = TRUE, type = "Season")`

Which gives:

![image](https://user-images.githubusercontent.com/1236491/58983494-dcdd1580-87ce-11e9-858d-1d0085bc8d2e.png)

**Comment by dyun33** [comment]
Thank you so much. The trick really works. But during the analysis, I notice a problem: discrepancies between an estimated slope and the slope in the plot. (Data:)
[df.zip](https://github.com/davidcarslaw/openair/files/3266107/df.zip)

(Code:)
`MKresults <- TheilSen(df, pollutant = "value",deseason = F, slope.percent = TRUE, type = "Season")`
![Picture1](https://user-images.githubusercontent.com/12587031/59108344-ac00fb80-8908-11e9-80ef-3e3d91be8ee3.png)

Also, I have one more question with the graph. In the OpenAir manual page 168, the plot points are connected by lines; however, on my plot, I don't see any line between points. Could you please tell me what causes the differences? 

Thanks.

**Comment by davidcarslaw** [comment]
I'm not sure why there is a difference - perhaps date formatting? The actual points shown should correspond to your data directly, so it should be easy to see which one is correct ... then work out what went wrong with the other.

As for lines, it will only plot lines with regular monthly or annual time series. Your data has variable differences from one period to the next ... the slope estimates should be valid though (notwithstanding the differences you see above).

**Comment by dyun33** [comment]
The percent slope shown on the plot -373.7 %/yr is the same with the output `(MKresults$data[[2]])$slope.percent[4]`. However, the estimated slope (not percent) in Wet season is positive and looks correct as it is similar to another slope in Dry season. All values are positive, and there is no zero or missing value. So, I guess the format is not an issue. 

However, I am wondering whether the equation for calculating the percent slope leads to this error; Equation 7, p167. If C_End is smaller than C_Start, even if a general trend is increasing, would this equation produce a negative slope? BTW, my C_End is larger than C_Start, so this is not my case, either.  Or simply the percent slope equation in the Openair package is not what I want. I was looking for an overall percent change, which can be calculated by %change = (Sen's slope * length of the period)*100 / mean (I found [here](https://www.researchgate.net/post/How_do_I_calculate_Change_magnitude_as_percentage_of_mean_from_Theil-Sens_slope_estimator_for_rainfall_data_of_more_than_100_years)).

Anyway, thank you again, and any comment will be appreciated.

**Comment by davidcarslaw** [comment]
OK, thanks. Let me look into this - perhaps there is a problem due to it being a non-regular time series.

**Comment by dyun33** [comment]
Oh, I didn't think about a potential issue with irregularity in date. I will let you know after I test a regular vs irregular dataset. I will create a new date column with a fixed interval and report results here.

**Comment by davidcarslaw** [comment]
I realised that you plotted "value" i.e. different data to what I plotted? Looking at the data I plotted, it all seems correct. If so, could you make the data available again to see if I can reproduce this?

**Comment by dyun33** [comment]
Yes, in the previous question, I used a subset of data, which I attach here again: df.1.zip
[df (1).zip](https://github.com/davidcarslaw/openair/files/3266512/df.1.zip)

I used this code which generates a negative percent slope: 
`df <- read.csv("df.csv", stringsAsFactors = F)
df$date <- lubridate::ymd(df$date, tz = "America/New_York")

MKresults <- TheilSen(df, pollutant = "value", deseason = F, slope.percent = T, type = "Season")`
Thanks.

**Comment by davidcarslaw** [comment]
I think the problem here is that percentage changes don't work well. In the "Wet" case above the predicted trend at the start point is slightly negative. This means it does not make sense to consider a % change defined as 100 * (Cend / Cstart -1). Personally, I would avoid % changes anyway as they can be defined in lots of different ways - and as we see here, sometimes don't work at all.
