### ISSUE TITLE
conditionalQuantile plots

### ISSUE THREAD

**Issue by kailas29** [davidcarslaw/openair#204]
Hi David,

I have an issue with the conditional quantile function. I have different species (e.g. NOx, PM10, PM2.5) for comparison however when I'm trying to plot all individual conditionalQuantile plots in one plot I cannot. Even when in setting a layout or the par(mflow) or with ggarrange comand from another package etc. Any ideas why?

Thanks

**Comment by davidcarslaw** [comment]
Hi - any chance you can send some example data + the code you are trying to use to make the plot? It might not make much sense to combine several pollutants in a single plot ...

**Comment by kailas29** [comment]
Hi David,

The code that I'm using is the very basic one:

pm10 <- conditionalQuantile(PM10, obs = "obs", mod = "model", ylab = "Observed PM10 (ug/m3)", xlab = "Modelled PM10 (ug/cm3)")
no2 <- conditionalQuantile(no2, obs = "obs", mod = "model", ylab = "Observed NO2 (ppb)", xlab = "Modelled NO2 (ppb)")

And I want to combine the into one plot side by side.

Example data can be found here : 
https://drive.google.com/file/d/1D7QZBTjFDHPjKdGuRWVxL4lpe8I6Mo1Q/view?usp=sharing

Thanks for the quick response

**Comment by N-thony** [comment]
Hi David,
I have an issue with the conditional quantile function. When I'm trying to set the key.position to "right" or "left", I'm getting the error in the image below.
![image](https://user-images.githubusercontent.com/68591383/103630304-22813780-4f4a-11eb-997b-6f407aed0f6d.png)
Any ideas of what to do?

**Comment by davidcarslaw** [comment]
I can't seem to reproduce this. I just tried the example in the help file with `key.position = "right"` and it works OK. Could you try loading opener into a fresh R session and try again?

```
mydata$mod <- mydata$nox*1.1 + mydata$nox * runif(1:nrow(mydata))
conditionalQuantile(mydata, obs = "nox", mod = "mod", key.position = "right")
```

<img width="905" alt="image" src="https://user-images.githubusercontent.com/1236491/104287902-0718ae00-54af-11eb-9912-386b95576ab0.png">

**Comment by N-thony** [comment]
I tried your example and I'm facing the same problem.
![image](https://user-images.githubusercontent.com/68591383/104290333-e65a5380-54c2-11eb-9c1e-6f9ef2be98d1.png)

**Comment by N-thony** [comment]
So, to sort out this I have to load again **latticeExtra**
library(openair)
library(latticeExtra)

mydata$mod <- mydata$nox*1.1 + mydata$nox * runif(1:nrow(mydata))
conditionalQuantile(mydata, obs = "nox", mod = "mod", key.position = "right")
![image](https://user-images.githubusercontent.com/68591383/104290514-199ce280-54c3-11eb-9e17-ce7bb23e7480.png)

**Comment by jack-davison** [comment]
Hi N-thony, 

This should now be fixed in the development verison.

Cheers,
Jack

```r
mydata$mod <- mydata$nox*1.1 + mydata$nox * runif(1:nrow(mydata))
conditionalQuantile(mydata,
                    obs = "nox",
                    mod = "mod",
                    key.position = "right")
```
![image](https://user-images.githubusercontent.com/45171616/217614112-bbfaca27-b65c-4b26-a2d1-6003abe9291d.png)
