### ISSUE TITLE
Plots from TheilSen

### ISSUE THREAD

**Issue by Biogeomur** [davidcarslaw/openair#205]
First I really appreciate this piece of code. I have been using an excel file with Sen slope built in but am finally making a leap to R. I am a novice so forgive me if I ask basic questions!

I am using Openair version 2.6-5 and have run TheilSen on daily climate data. Here is how I ran it, where MinT_PN is daily minimum temperature data for one site:

TheilSen(PN_temp_test, pollutant = "MinT_PN", deseason = FALSE, type = "season", avg.time = "year", statistic = "mean", percentile = NA, data.thresh = 0, alpha = 0.05, dec.place = 3, xlab = "year", lab.frac = 0.99, lab.cex = 0.8, x.relation = "same", y.relation = "same", data.col = "cornflowerblue", trend = list(lty = c(1, 5), lwd = c(2,  1), col = c("red", "red")), text.col = "darkgreen", slope.text = NULL, cols = NULL, shade = "grey95", auto.text = TRUE, autocor = FALSE, slope.percent = FALSE, date.breaks = 5, plot = TRUE, silent = FALSE)

The output seems right with 4 graphs all with in one row. What I can't figure out is how to split or realign the graphs so they are stacked instead of squished in one row. It doesn't seem to allow a change to the layout.  
Also just to clarify, the way I ran the code above I  am not sure whether to interpret the winter summary to be the previous years Dec with the Jan and Feb of the following year. I had thought I needed to put yearseason in Type but that did not work, and under the Avg.time descriptions you have "For “season” the data are split up into spring: March, April, May etc. Note that December is considered as belonging to winter of the following year. " Can you clarify how the winter season is handled when type = "season", avg.time = "year"?

Thank you!

**Comment by davidcarslaw** [comment]
Hi

You might be best with `avg.time = "season"` in this situation? Also, you can control the layout with the `layout` option e.g. `layout = c(1, 4)`

david

**Comment by Biogeomur** [comment]
Thanks. That worked, and I will use season for the avg.time. Results are similar to my excel spreadsheet but a bit different. Maybe it is how it handles missing data. I will have to look into that.
