### ISSUE TITLE
Specifying hemisphere for seasonal analysis

### ISSUE THREAD

**Issue by khbrc** [davidcarslaw/openair#209]
Hi,
I use the openair package a lot for air quality analysis so thanks heaps for developing it.  I live in the southern hemisphere and previously I've had no issues with using hemisphere="southern" when using type="season" in a function.  More often now it doesn't seem to work and the seasons end up wrongly labelled in the plots.

For example, the command below, produced the following image.
> scatterPlot(seas2,x="soi",y="iod", type="season", hemisphere="southern", linear=TRUE) 

![Scatterplot_hem_southern](https://user-images.githubusercontent.com/45218985/64734776-63766100-d53b-11e9-8035-6752d8d19884.png)

Winter here is JJA and summer is DJF!  Has something changed or is there something I'm missing?  The timeAverage function is also not labeling the seasons correctly for the southern hemisphere in the resulting dataframe.

I use openair for other types of analyses, which often include rainfall.  It would be really useful to have "sum" as an option in the statistics call so that I can get monthly/seasonal totals of rainfall from the daily data.  

Regards,
Kathleen

**Comment by davidcarslaw** [comment]
Hi Kathleen

Strange. What version of openair are you using? I just tried teh code below and it does what I would expect - does that work for you?

```
scatterPlot(selectByDate(mydata, year = 2000), x ="nox",y="no2", type="season", hemisphere="southern", linear=TRUE)
```
![image](https://user-images.githubusercontent.com/1236491/64764100-4771c000-d539-11e9-935a-cf2f848f8fdd.png)


>

**Comment by khbrc** [comment]
That'll be wonderful.  Thanks very much.

Regards,
Kathleen
________________________________
