### ISSUE TITLE
TaylorDiagram:how we can increase the font size of the words in legend (key)?

### ISSUE THREAD

**Issue by optimsari** [davidcarslaw/openair#21]
Could you please tell me how we can increase the font size of the words in legend (key)?
Also, could you please tell me how we change the "default" ylab and xlab? is it possible to increase the font size of the word correlation in the plot and the numbers that show the correlation? 

I am using this command:

TaylorDiagram(mydata, obs = "obs", mod = "mod", group = NULL,
  type = "default", normalise = FALSE, cols = "brewer1",
  rms.col = "darkgoldenrod", cor.col = "black", arrow.lwd = 3,
  annotate = "centred\nRMS error", key = TRUE, key.title = group,
  key.columns = 1, key.pos = "right", strip = TRUE, auto.text = TRUE,
  ...)

**Comment by jobonaf** [comment]
With the argument ```fontsize=15``` you can increase/decrease the font size in the plot. It is passed to the function ```lattice::trellis.par.set```. As far as I understand, all the labels are rescaled consequently.
You can pass also the extra-arguments ```xlab="my X label", ylab="my Y label"```.

``` {r}
TaylorDiagram(mod.dat, obs = "obs", mod = "mod", 
              group = "model", fontsize = 15,
              xlab = "my X label", ylab = "my Y label")
```

**Comment by jack-davison** [comment]
Closing as this feels like its resolved, although optimsari feel free to reopen/open a new issue if you do need more help with `TaylorDiagram()`.

``` r
openair::TaylorDiagram(
  openair::mydata,
  obs = "no2",
  mod = "nox",
  fontsize = 10,
  xlab = "my X label",
  ylab = "my Y label"
)
```

![](https://i.imgur.com/qmNRWL9.png)

``` r
openair::TaylorDiagram(
  openair::mydata,
  obs = "no2",
  mod = "nox",
  fontsize = 15,
  xlab = "my X label",
  ylab = "my Y label"
)
```

![](https://i.imgur.com/JVNm0fl.png)

``` r
openair::TaylorDiagram(
  openair::mydata,
  obs = "no2",
  mod = "nox",
  fontsize = 20,
  xlab = "my X label",
  ylab = "my Y label"
)
```

![](https://i.imgur.com/1dOjrJ2.png)

<sup>Created on 2023-02-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
