### ISSUE TITLE
timePlot ylim

### ISSUE THREAD

**Issue by simonadzs** [davidcarslaw/openair#210]
Hi.
I was used to plot timeseries with timePlot: several variables, ungrouped. Very useful. 
In the openair version 1.8-2 the function automatically adjusted the ylim for each variable, so that it was possible to display variables with different ranges.
Now I'm migrating to openair 2.6.5, an the y-limits are fixed, they are the same for the different variables, so that it is not possible to display e.g. pressure and temperature.
Am I missing something?
Thank you very much

**Comment by davidcarslaw** [comment]
Hi

There was a change some time back to make olotting more flexible. You need to set the `y.relation` as in this example:

```
timePlot(selectByDate(mydata, year = 2003, month = "aug"),
pollutant = c("nox", "o3", "pm25", "pm10", "ws"),
y.relation = "free")
```

**Comment by simonadzs** [comment]
Thank you so much!
Regards
Simona
