### ISSUE TITLE
Missing data in meteorological data: importKCL

### ISSUE THREAD

**Issue by lma1335** [davidcarslaw/openair#211]
Hi,

I found there are many missing data in meteorological information with importKCL. I downloaded an version of meteorology information in 2018 and tried to do it again recently for newer data. I found lots of missing data: not only the data within 2019, but also the data previously shown with typical values when I downloaded them in 2018 (they disappear when I tried to download them in 2019). For example, it lost all temperature data before October 2018.

Could you please help me with this? Thank you very much in advance.

Regards,
Marina

**Comment by davidcarslaw** [comment]
Hi

Do you have an example for a particular site? Note a lot of sites may have ceased measurements and other opened. You can get some useful meta data by:

`meta <- importMeta(source = "kcl", all = TRUE)`

**Comment by lma1335** [comment]
> Hi
> 
> Do you have an example for a particular site? Note a lot of sites may have ceased measurements and other opened. You can get some useful meta data by:
> 
> `meta <- importMeta(source = "kcl", all = TRUE)`

Hi,

Thank you for your quick reply. I suppose the weather data won't change with site, i.e. the weather data is only specific to Datetime. Below is what I got in 2018:
![image](https://user-images.githubusercontent.com/56355405/66563898-ad606000-eb56-11e9-9bc7-d814e12cf507.png)
Here is what I got recently, where you can see that the temperature column data disappears:
![image](https://user-images.githubusercontent.com/56355405/66563930-bf420300-eb56-11e9-8e6e-96990ff64795.png)

Above is an example. Actually, the temperature column has no data now at anytime before 2018-10. The wind speed column only have two data point in 2019. Are there something wrong in the url source of the weather data? I tried to retrieve the url provided in your source code instead of using importKCL and get the same result and same problem.

**Comment by davidcarslaw** [comment]
The met data as part of this function come from a mix of air quality sites that KCL run and it may be the data are no longer available. You might be better accessing other met data - have a look at my `worldmet` package (`install.packages("worldmet")` and see https://github.com/davidcarslaw/worldmet. I think that will be a better option...

**Comment by lma1335** [comment]
> The met data as part of this function come from a mix of air quality sites that KCL run and it may be the data are no longer available. You might be better accessing other met data - have a look at my `worldmet` package (`install.packages("worldmet")` and see https://github.com/davidcarslaw/worldmet. I think that will be a better option...

Thank you very much.
