### ISSUE TITLE
Not a bug: clustering with corPlot()

### ISSUE THREAD

**Issue by pcristofanelli** [davidcarslaw/openair#213]
Hi David,

I'm wondering what kind of distance measure is used to calculate clustering with corPlot() and if some references are available.

Thanks for the info and for openair.

Paolo

**Comment by jack-davison** [comment]
Hi Paolo,

`corPlot()` uses the `stats::hclust()` function with its default parameters to perform hierarchical clustering.

Try typing `?hclust` into your R console to bring up the `hclust()` [help pane](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/hclust). That contains several references which you could use in publications and so on.

Best,
Jack
