### ISSUE TITLE
timePlot selectByDate x axis issue

### ISSUE THREAD

**Issue by jmclaren17** [davidcarslaw/openair#214]
Good morning, 

I have had an issue when trying to plot one particular month in the timePlot( ).  I want to look at one pollutant, and "Stack" they years for October to see how things vary over the years.  Generally it works, but there are formatting issues.  The pane on the left of each plot normally displays (or used to) the year for which the data relates to.  More importantly the bottom left corner of each plot displays 01-Oct, but no other ticks along the x axis.  This will not change no matter what nuber of date.breaks or date.format combination is used.

Has anyone found a way around this?  I am running openair 2.6-6 in RStudio.

The code I am using is something like: 
timePlot(selectByDate(mydata,month = 10), pollutant = "benzene", stack = TRUE)

**Comment by davidcarslaw** [comment]
Hi - It's been so long since I have looked at this function as I think most will now use ggplot for such plots. However, I have made a couple of modifications that I hope fix this issue if you would like to install the github version...

Thanks

**Comment by jmclaren17** [comment]
Thanks David, 

This I am not too familiar with ggplot - I will check it out.
