### ISSUE TITLE
white center percentileRose

### ISSUE THREAD

**Issue by JasperSch** [davidcarslaw/openair#216]
Hi,

When using the percentileRose function, sometimes white bars occur in the center of the plot.
What do these bars mean? Should they be removed and how can they be removed?

Thanks in advance.

minimal working example using example data:
http://www.openair-project.org/Downloads/ExampleDataSets.aspx

`df = read.csv("OpenAir_example_data_long.csv")`
`library(openair)`
`percentileRose(mydata = df)`

![exampleWhiteCenter](https://user-images.githubusercontent.com/49677239/69634131-e8a8e680-1051-11ea-928d-4a2047cc39b3.png)

**Comment by JasperSch** [comment]
This is my local bug fix.
Would this be recommended or not?

within percentileRose()

replacing
`lpolygon(subdata$x, subdata$y, col = "white", border = NA)  `  

by

```
       if(length(percentile) > 1)            
              lpolygon(subdata$x, subdata$y, col = col[1], border = NA)  
        else
              lpolygon(subdata$x, subdata$y, col = "white", border = NA)
```

**Comment by davidcarslaw** [comment]
Thanks for this. To be honest, I can't remember why this is the case! I can see no reason why there should be any white space and your solution seems entirely reasonable. Let me have a look through the code - this is quite an old function that probably needs a fresh look...

Thanks again.

David
