### ISSUE TITLE
worldmet connection error

### ISSUE THREAD

**Issue by jmclaren17** [davidcarslaw/openair#217]
Hi David,

I am trying to download some met data for london city.  However when I used the following code I get this error:

getMeta(lat = 51.3, lon = 0.02)
Error in open.connection(con, "rb") : HTTP error 403.

Furthermore I have tested with some old code that I used to get heathrow data successfully in the past:
 heathrow<-importNOAA(code = "037720-99999", year = 2017:2019)

This throws up the error:
Call `rlang::last_error()` to see a backtrace.

Is there an issue with the server?  Any ideas would be gratefully received!

**Comment by jmclaren17** [comment]
Further to the above - this is not just an issue that I am experiencing, so are my colleagues.

**Comment by davidcarslaw** [comment]
I think this is due to scheduled maintenance this week, see https://www.ncdc.noaa.gov/isd

**Comment by jmclaren17** [comment]
Amazing, thank you David!  Glad to hear it isnt an issue with the package itself.

**Comment by jmclaren17** [comment]
Hi David, 

All fixed this morning.  Thanks
