### ISSUE TITLE
Issue importing precalculated back trajectories into openair

### ISSUE THREAD

**Issue by pavanaditya369** [davidcarslaw/openair#218]
Dear sir
I have the precalculated back trajectories for my location stored. I am not able to import the precalculated back trajectory into the system.
The response is coming like this. Kindly help me.

l1itraj <- importTraj(site = "newmanali", year = 2016, local = "c:/users/pavan aditya/Documents/R/TrajProc/")
Error in UseMethod("close") : 
  no applicable method for 'close' applied to an object of class "character"

**Comment by jack-davison** [comment]
Closing stale issue (4 years).

If your problem is persisting, please feel free to reply in this issue with one or more of the files you're trying to read in. This will help us recreate your issue on our computers to diagnose what may be going on.

Cheers, 
Jack
