### ISSUE TITLE
base map about the back trajectory functions

### ISSUE THREAD

**Issue by MoonLightSAMA** [davidcarslaw/openair#219]
Dear sir,
I try to use the back trajectory functions to draw picture.
I try to use "@param map.res" to change the base map. You give us three chioce in this parameter "TRUE","hires" and "state", but I want to use a higher resolution base map which have the states boundary in my study region like the [map.res = "state"].
I see the source code of the "openair" package, but I still don't know how this function run.
Maybe, my IT skill is poor.
So, could you tell me how to change the base map to my needs if the "openair" package has this function now?
Thanks

**Comment by jack-davison** [comment]
I appreciate that this issue is quite old (~3 years), but do the answers in https://github.com/davidcarslaw/openair/issues/243 and https://github.com/davidcarslaw/openair/issues/123 help at all?

**Comment by MoonLightSAMA** [comment]
> I appreciate that this issue is quite old (~3 years), but do the answers in #243 and #123 help at all?

I'm so surprising when I find this reply. Thanks~
