### ISSUE TITLE
Error in aggregate.data.frame(mydata["nox"], format(mydata["date"], "%Y-%m"),  :    'by' must be a list

### ISSUE THREAD

**Issue by Shailendra-ufp** [davidcarslaw/openair#225]

**Comment by danyhleis** [comment]
same problerm

**Comment by danyhleis** [comment]
same problem

**Comment by schonhose** [comment]
Where, what and how?

**Comment by jack-davison** [comment]
Closing stale branch. Please provide a [reproducible example](https://www.tidyverse.org/help/#reprex%3E) in a new issue and we'll be able to help you out.

Jack
