### ISSUE TITLE
Maybe the wrong formula was used in trajCluster function when method = “angle”

### ISSUE THREAD

**Issue by MoonLightSAMA** [davidcarslaw/openair#226]
Dear sir,
The result is different between  trajCluster function and TrajStat (Another software which can  cluster back trajectories), when I use the same data and method.
I find the information in "the openair manual".
The formula used in trajCluster function is “d1,2 = 1/n * ∑cos−1 ((**0.5Ai + Bi + Ci** )/√AiBi )"
but in the paper "Use of backward trajectories to interpret the 5-year record of pan and o3 ambient air concentrations at kejimkujik national park, nova scotia"(Sirois, A. , & Bottenheim, J. W. . (1995). ), the formula is “d1,2 = 1/n * ∑cos−1 ((**0.5Ai + Bi - Ci** )/√AiBi )"
NOTE : is "0.5Ai + Bi - Ci" ,not "0.5Ai + Bi + Ci", the right is "minus", the wrong is "plus". 
Thanks

**Comment by jack-davison** [comment]
Thanks for drawing this to our attention. This is a typo in the openair manual that we'll look to rectify; the actual code is correct:

https://github.com/davidcarslaw/openair/blob/af6034d86083b6fc1bc172b267b7b5b2219c36b4/src/cluster.cpp#L47
