### ISSUE TITLE
Translate WindRose to another language

### ISSUE THREAD

**Issue by paulvern** [davidcarslaw/openair#229]
Not exactly an issue, but I was wondering if it's possible to automatically translate the text strings in WindRose to another language instead of English. In particular when using seasonal plots and the initials of months, a not English speaking reader will find it difficult to figure out the real meaning of the four wind roses.

**Comment by schonhose** [comment]
I think the names of the months can be changed using the locale of R.

See [this link](https://stat.ethz.ch/R-manual/R-devel/library/base/html/locales.html)

## Set your language
### Windows

- `Sys.setlocale("LC_TIME", "German")`
- `Sys.setlocale("LC_TIME", "English")`
- `Sys.setlocale("LC_TIME", "French")`

### Other

- `Sys.setlocale("LC_TIME", "de") # Solaris: details are OS-dependent`
- `Sys.setlocale("LC_TIME", "de_DE") # Many Unix-alikes`
- `Sys.setlocale("LC_TIME", "de_DE.UTF-8") # Linux, macOS, other Unix-alikes`
- `Sys.setlocale("LC_TIME", "de_DE.utf8") # some Linux versions`

**Comment by paulvern** [comment]
I'm working on a Ubuntu 16.04 machine with it_IT.UTF-8 as one of the installed locales.
sadly, changing the locale inside R doesn't seem to affect the result. The windRoses are still in English.

**Comment by schonhose** [comment]
`month.abb` is a predefined constant as "the three-letter abbreviations for the English month names". Hence, this will always give the English names.

On my windows machine:
```
Sys.setlocale("LC_ALL", "Italian")
format(ISOdate(2000, 1:12, 1), "%b")
```
returns:
`"gen" "feb" "mar" "apr" "mag" "giu" "lug" "ago" "set" "ott" "nov" "dic"`

**Comment by paulvern** [comment]
My mistake on month.abb, and yes your code works and it returns the correct month names but still the windrose is in English. I found out that the month names are hard coded in cutData:
`if` (hemisphere == "northern") {
        x[[type]] <- "winter (DJF)"
        ids <- which(as.numeric(format(x$date, "%m")) %in% 
          3:5)
        x[[type]][ids] <- "spring (MAM)"
        ids <- which(as.numeric(format(x$date, "%m")) %in% 
          6:8)
        x[[type]][ids] <- "summer (JJA)"
        ids <- which(as.numeric(format(x$date, "%m")) %in% 
          9:11)
        x[[type]][ids] <- "autumn (SON)"
        seasons <- c("spring (MAM)", "summer (JJA)", 
          "autumn (SON)", "winter `(DJF)")`
Any chance to make them dynamic (i.e. based on locale)?

**Comment by schonhose** [comment]
Ow, it is not my package, I am just trying to help.

**Comment by paulvern** [comment]
It does not. WindRose calls cutData when dealing with the 'type' option (I need seasonal wind roses) and those season are hard coded in cutData.

**Comment by jack-davison** [comment]
Hi both,

I've just pushed a fix on the development version for this.

We can't automatically translate the month names themselves (e.g., Primavera, Estate, etc.) but we can use the correct abbreviations, which should help a little with interpretation for non-English language speakers.

You can, of course, manually recode the season names if needed.

```r
Sys.setlocale("LC_ALL", "Italian")

windRose(mydata, type = "season")
```

![image](https://user-images.githubusercontent.com/45171616/222972831-fabfd517-a385-43ac-8531-bf2e1cb2b982.png)
