### ISSUE TITLE
subscript issue with parameter 'PMcoarse' 

### ISSUE THREAD

**Issue by Tavas666** [davidcarslaw/openair#230]
I guess openair plot functions automatically write PM10 and PM2.5 with 10 and 2.5 as subscript. I am now using PMcoarse (=PM10-PM2.5) but something funny happens with the subscripts turning it into 'PMcoarseoarse' in graphs.  

![image](https://user-images.githubusercontent.com/57726985/82664280-aabc0200-9c31-11ea-90ee-9b367eafa4aa.png)

**Comment by mauriciorozas97** [comment]
Hi,

Your problem will probably be solved by setting the argument "auto.text = FALSE" in the timplot function.

**Comment by Tavas666** [comment]
thanx for you reply @mauriciorozas97 that sort of solves the problem, but of course it would be even nicer if the autotext option would also deal with PMcoarse or PM(10-2.5) like it does with PM10 and PM2.5. Guess I'll have to sort it out manually if I want it to look pretty ;-)

**Comment by schonhose** [comment]
This effect is caused by the ordering of the replacement in `QuickText.R`:

```
ans <- gsub("pmc", "' 'PM' [coarse] * '", ans)
ans <- gsub("pmcoarse", "' 'PM' [coarse] * '", ans)
ans <- gsub("PMc", "' 'PM' [coarse] * '", ans)
ans <- gsub("PMcoarse", "' 'PM' [coarse] * '", ans)
```
My suggestion would be to rename the `PMcoarse` variable to `PMc` prior to creating a plot, which is the easiest way until the order of replacement has been fixed (i.e. replace `pmcoarse` before `pmc`).
