### ISSUE TITLE
importAURN returning NULL

### ISSUE THREAD

**Issue by stevecrawshaw** [davidcarslaw/openair#231]
I have tried multiple sites. e.g.
importAURN(site = "brs8", year = 2017, pollutant = "no2")
NULL is returned for all
This must have happened in the last few days as it worked last week.

**Comment by karlropkins** [comment]
Steve,
Not sure if you got to bottom of this? 
I had similar after R4 rebuild. I ended up reinstalling ropenaq and openair from GitHub sites. 
(NB: I needed ropenaq as well as openair and that might be down to CRAN version being pre R4 at time... hope that helps you as well) 

#installed both ropenaq and openair from GitHub sites 
remotes::install_github("ropensci/ropenaq")
#(check https://github.com/ropensci/ropenaq if your are on linux machine)
devtools::install_github('davidcarslaw/openair')

**Comment by stevecrawshaw** [comment]
Thanks Karl - that did the trick. I should have realised that it would be connected to the R upgrade!
cheers
steve

**Comment by BlaiseKelly** [comment]
Thanks for raising Steve and Karl, thanks for the response. I came across this today and solved by installing from Github as you suggested Karl. Had also just upgraded to 4.0.
