### ISSUE TITLE
importTraj is not working

### ISSUE THREAD

**Issue by purelandWH** [davidcarslaw/openair#232]
Hi David, I would like to create some back trajectory figures but I get the following error message: 

> traj <- importTraj(site = "london", year = 2020)
london2020 does not exist - ignoring that one.
Warning message:
In load(con) :
  cannot open URL 'http://met-data.ricardo-aea.com/trajectories/london2020.RData': HTTP status was '404 Not Found'

Is importTraj not temporarily not available due to the server issue? Thanks!

**Comment by koushiksaha09** [comment]
Hi purelandWH, I am facing thesame problem in oct,2020. Showinh 
> traj <- importTraj(site = "heathrow", year = 2018)
heathrow2018 does not exist - ignoring that one.
Warning message:
In load(con) :
  cannot open URL 'http://met-data.ricardo-aea.com/trajectories/heathrow2018.RData': HTTP status was '404 Not Found'
Please tell me how to address this issue.
