### ISSUE TITLE
summaryPlot produces error code

### ISSUE THREAD

**Issue by richardpdunne** [davidcarslaw/openair#233]
I have had 'openair' running just fine with a dataframe where "date" is in POSIXct format. Reusing the same dataframe and R script produced the error below when using e.g., the 'summaryPlot' function.  Are you able to help?

 Error: `vec_cast.POSIXct.POSIXct()` is implemented at C level.
 This R function is purely indicative and should never be called.
Backtrace:
     x
  1. +-openair::timeAverage(...)
  2. | \-`%>%`(...)
  3. |   +-base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  4. |   \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5. |     \-base::eval(quote(`_fseq`(`_lhs`)), env, env)
  6. |       \-openair:::`_fseq`(`_lhs`)
  7. |         \-magrittr::freduce(value, `_function_list`)
  8. |           +-base::withVisible(function_list[[k]](value))
  9. |           \-function_list[[k]](value)
 10. |             +-dplyr::do(., suppressWarnings(calc.mean(., start.date)))
 11. |             \-dplyr:::do.grouped_df(., suppressWarnings(calc.mean(., start.date)))
 12. |               \-rlang::eval_tidy(args[[j]], mask)
 13. +-base::suppressWarnings(calc.mean(., start.date))
 14. | \-base::withCallingHandlers(...)
 15. +-openair:::calc.mean(., start.date)
 16. | \-dplyr::bind_rows(firstLine, mydata)
 17. |   \-vctrs::vec_rbind(!!!dots, .names_to = .id)
 18. \-vctrs:::vec_cast.POSIXct.POSIXct(...)
 19.   \-vctrs:::stop_native_implementation("vec_cast.POSIXct.POSIXct")

**Comment by jack-davison** [comment]
Closing stale issue, but feel free to reopen if you're still having issues. From my end, this seems to have been resolved?

``` r
class(openair::mydata$date)
#> [1] "POSIXct" "POSIXt"
openair::summaryPlot(openair::mydata)
```

![](https://i.imgur.com/soRcrNg.png)

<sup>Created on 2023-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
