### ISSUE TITLE
differing timestamps on importAURN data and UK-AIR files

### ISSUE THREAD

**Issue by stevecrawshaw** [davidcarslaw/openair#235]
I have noticed that timestamps on importAURN data differ from the UK-AIR data by one hour. If this is because of a different convention, i.e. time ending instead of time beginning, this would seem to be inconsistent and IMO needs to be documented.

E.g. timestamp for PM10 at 44.4 ugm-3 import aurn is 00:00, for the flat CSV files is 01:00

 brs8 <- importAURN(site = "brs8", year = 2020)
head(brs8)
site              code  date                  nox   no2     no    o3  pm10 pm2.5    ws    wd air_temp
  <chr>             <fct> <dttm>              <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>    <dbl>
1 Bristol St Paul's BRS8  2020-01-01 00:00:00  29.0  27.1  1.25   17.2  **44.4**    40   3.5  110.      3.3
2 Bristol St Paul's BRS8  2020-01-01 01:00:00  NA    NA   NA      24.3  37.7    27   3.7  115.      2.7
3 Bristol St Paul's BRS8  2020-01-01 02:00:00  23.5  22.0  0.967  35.9  22.2    22   4.1  125.      2.7

from UK-AIR csv

  |   | Bristol St   Paul's |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
Date | time | PM<sub>10</sub> particulate matter (Hourly measured) | status | unit | Nitric oxide | status | unit | Nitrogen dioxide
  |   |   |   |   |   |   |   |  
01/01/2020 | 01:00 | **44.445** | R | ugm-3 (Ref.eq) | 1.24836 | R | ugm-3 | 27.12291
01/01/2020 | 02:00 | 37.682 | R | ugm-3 (Ref.eq) |   |   |   |  
01/01/2020 | 03:00 | 22.223 | R | ugm-3 (Ref.eq) | 0.96748 | R | ugm-3 | 22.00612
01/01/2020 | 04:00 | 27.054 | R | ugm-3 (Ref.eq) | 0.40572 | R | ugm-3 | 15.73502

I have checked back to 2011, e.g. for site kc1 and the issue is there at that point. It doesn't seem to be related to daylight savings.

**Comment by jack-davison** [comment]
Hi Steve, good spot (3 years ago!) 

You're right - openair does date beginning, UK AIR / AQE / etc. does date ending. Add that to the documentation.
