### ISSUE TITLE
 Modstats with spearman's coefficient

### ISSUE THREAD

**Issue by mauriciorozas97** [davidcarslaw/openair#237]
Hi,

I would like to know how can I configure the **"modstats"** function to show me the Spearman correlation coefficient instead of the Pearson coefficient? I tried to add **'method = "spearman"'** as argument, but there was no difference in the results. If you could give me an example of its use, I would appreciate it. (Attached image below)

Thank you very much in advance.

<img width="416" alt="Screenshot_1" src="https://user-images.githubusercontent.com/61034062/91415538-2ffc1780-e81c-11ea-9b05-7cc236ee901a.png">

**Comment by schonhose** [comment]
According to the docs the method should be `Spearman`, note the captital "S".

**Comment by mauriciorozas97** [comment]
Hello @schonhose ,

Thank you very much for your answer.

I modified the value of the "method" argument that I showed above with "Spearman" (capital "S") but the result was the same.

I checked the code for the "modStats" function in "davidcarslaw / openair / r" and I couldn't find the Spearman function. Perhaps it is not yet available in the current version of openair.

**Comment by jack-davison** [comment]
Fixed in the development version so feel free to give it a go!

```r

dplyr::bind_rows(
  "p" = openair::modStats(openair::mydata, "nox", "no2", method = "pearson", statistic = "r"),
  "s" = openair::modStats(openair::mydata, "nox", "no2", method = "spearman", statistic = "r"),
  .id = "method"
)
```
``` r
# A tibble: 2 × 3
# Groups:   default [1]
  method default      r
  <chr>  <fct>    <dbl>
1 p      all data 0.787
2 s      all data 0.842
```
