### ISSUE TITLE
Data unavailable using importKCL

### ISSUE THREAD

**Issue by kleeming** [davidcarslaw/openair#242]
Old data (pre 2019) no longer available to import from LondonAir website: importKCL() returns no data with error 
"Warning messages: 1: In load(con) :  cannot open URL 'http://www.londonair.org.uk/r_data/MY1_2009.RData': HTTP status was '404 Not Found'
2: No data to import - check site codes and year. "

Related to error #238

**Comment by davidcarslaw** [comment]
Thanks - should be fixed now. This was due to King's moving to Imperial...

**Comment by amystidworthy** [comment]
I've just tried the same thing and got the same error

> importKCL()
MY1_2009 does not exist - ignoring that one.
NULL
Warning messages:
1: In load(con) :
  cannot open URL 'http://www.londonair.org.uk/r_data/MY1_2009.RData': HTTP status was '404 Not Found'
2: No data to import - check site codes and year. 

Related to error #238

**Comment by jack-davison** [comment]
The above code works at time of writing. Feel free to reopen the issue if your problem persists. I expect the issue related to "MY1" being part of the AURN rather than the KCL network.

``` r
openair::importKCL()
#> NOTE - mass units are used 
#> ug/m3 for NOx, NO2, SO2, O3; mg/m3 for CO
#> PM10_raw is raw data multiplied by 1.3
#> # A tibble: 8,760 × 13
#>    date                  nox   no2    o3   so2    co pm10_raw  pm10  v2.5  nv10
#>    <dttm>              <dbl> <dbl> <dbl> <dbl> <dbl>    <dbl> <dbl> <dbl> <dbl>
#>  1 2009-01-01 00:00:00 131.   48.2  13.5 0.887 0.503     48.4  53.3    NA    NA
#>  2 2009-01-01 01:00:00  61.8  31.8  18.7 0     0.464     43.6  45.6    NA    NA
#>  3 2009-01-01 02:00:00  77.7  36.9  21.3 0     0.464     42.6  45.4    NA    NA
#>  4 2009-01-01 03:00:00  68.3  34.9  20.5 0     0.464     38.4  42.9    NA    NA
#>  5 2009-01-01 04:00:00  59.7  29.6  26   0     0.377     31.2  37.2    NA    NA
#>  6 2009-01-01 05:00:00  59.2  29.6  28   0     0.377     30.2  34.6    NA    NA
#>  7 2009-01-01 06:00:00  61.1  28.6  27.5 0     0.377     33.8  37.1    NA    NA
#>  8 2009-01-01 07:00:00  90.7  42.0  22   0     0.406     34.8  38.3    NA    NA
#>  9 2009-01-01 08:00:00  56.3  32.5  22   0     0.348     27.6  33.2    NA    NA
#> 10 2009-01-01 09:00:00  48.7  32.5  23.5 0     0.348     26.6  31.0    NA    NA
#> # … with 8,750 more rows, and 3 more variables: nv2.5 <dbl>, site <fct>,
#> #   code <chr>
```

<sup>Created on 2023-02-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
