### ISSUE TITLE
boundary of India

### ISSUE THREAD

**Issue by Jaip2018** [davidcarslaw/openair#243]
Dear David,

We plotted trajLevel for PSCF using back trajectories analysis. One of the reviewer commented on boundary of India. They said that boundary of India is merged with Pakistan boundary. What I should reply for this comments. 

 I used this code with package of maproj and opeanir

trajLevel(selectByDate(PSCF_NS,start="25/04/2019", end="30/06/2019", year=2019, 
                       month=4:6, day=1:31,hour=0:23), lon = "lon", lat = "lat", 
    pollutant = "BB", plot = TRUE, type = "Season", percentile= 50, 
    statistic = "PSCF", col="increment", map.fill = FALSE, map.cols = "transparent", 
    map.alpha = 0.4, projection = "lambert", parameters = c(-10, 100), 
    orientation = c(0,90,0), by.type = TRUE, origin = TRUE, lwd=6, grid.col="grey40", 
    grid.alpha=0.2, font.label= c(16, "bold", "red"),  smooth = TRUE, xlim = c(30, 100), ylim = c(0, 40), 
    par.settings=list(fontsize=list(text=18)), xlab= "Longitude", ylab= "Latitude")

Please let me suggest I can modified this code or need any another package for accuracy for boundary of India.  

![Rplot03](https://user-images.githubusercontent.com/42550319/93921014-9b5adb80-fd2d-11ea-92ca-4c3be81725aa.jpg)

**Comment by masabhathini** [comment]
Dear Jai Prakash,

 I also faced this issue during my Ph.D. time. This issue will help you (https://stackoverflow.com/questions/53737409/how-to-add-my-own-shape-file-trajlevel-in-openair-package-r).

regards,
M. Sateesh

**Comment by masabhathini** [comment]
Dear Jai Prakash,
 Here, I attached my shape file in R (maps) supported format.
 Arrange these files path to maps by adding the following lines before you call trajLevel().


### To make map() call this new database:
library(maps)
worldMapEnv="MYMAP"
Sys.setenv("MYMAP"="/my/path/to/") # don't add the "world!"
[sateesh.zip](https://github.com/davidcarslaw/openair/files/5280031/sateesh.zip)

![pic](https://user-images.githubusercontent.com/25902165/94216560-4ec5fa80-fefd-11ea-8015-83c01eb2a641.jpeg)


regards,
M. Sateesh

**Comment by moorthynair** [comment]
Hi Sateesh,
Thanks for the code.
this was really helpful.
I am struggling to make the map border thicker. 
I want just like the one you posted above. If you can help me with the syntax

**Comment by jack-davison** [comment]
Closing as this appears to be resolved. Answer in https://github.com/davidcarslaw/openair/issues/123 may also be useful. Cheers!
