### ISSUE TITLE
how to import simple csv file with import ?

### ISSUE THREAD

**Issue by adibratul** [davidcarslaw/openair#246]
Error in import() : 
  Date conversion problems, check that date.format is correct.
 First few dates looks like this: 2020-01-01, 2020-01-01, 2020-01-01, 2020-01-01, 2020-01-01, 2020-01-01

I have add the screenshop of my csv file here 
![image](https://user-images.githubusercontent.com/47941638/106505862-16f64180-64f3-11eb-8cb7-73ef1d84aa51.png)

**Comment by adibratul** [comment]
the date has to convert by using  as.POSIXct(file$date, tz= " ")

**Comment by adibratul** [comment]
the date has to convert by using  as.POSIXct(file$date, tz= " ")

**Comment by schonhose** [comment]
What I would do is read the CSV manually by using `read_table()` function, then concatenate the date and time column to a new date column, use `lubridate::ymd_hm()` function to transform the textual date into a POSIX date time.

Remove the old date and time columns, rename the new date column to `date` and you should be set.

Please be aware of TZ issues with daylight saving times etc.

**Comment by adibratul** [comment]
Thanks it works for me . TIA
