### ISSUE TITLE
Error while installing the openair package

### ISSUE THREAD

**Issue by lovleengupta** [davidcarslaw/openair#249]
I have Rstudio version 1.1.1103 and R version 4.0.4 When I install the openair package, I get the following error:

"Error in readRDS(file) : error reading from connection"

Request you to please suggest what can I do to set it right.

Eagerly looking forward to your reply.
Please reply.

Thanks,
Lovleen.

**Comment by Shailendra-ufp** [comment]
Ma'am Lovleen
May Java update issue.
Sincerely,Shailendra Kumar YadavResearch Scholar,Department of Environmental Engineering,Delhi Technological University, New Delhi 1100429655812372,9654310802 

    On Tuesday, 16 February, 2021, 06:07:45 am IST, lovleengupta <notifications@github.com> wrote:  
 
 


I have Rstudio version 1.1.1103 and R version 4.0.4 When I install the openair package, I get the following error:

"Error in readRDS(file) : error reading from connection"

Request you to please suggest what can I do to set it right.

Eagerly looking forward to your reply.
Please reply.

Thanks,
Lovleen.
