### ISSUE TITLE
Export trajectories

### ISSUE THREAD

**Issue by JaysonAP** [davidcarslaw/openair#25]
Would like to request an enhancement to the trajectories, the ability to export, preferably as KML/KMZ or any other data file that would allow them to be imported into GIS, etc.

Mapping function within OpenAir works great, but the ability to export trajectories and loaded into GIS software would allow several additional functions, such as overlaying sources, etc.

**Comment by davidcarslaw** [comment]
The actual trajectory data is the result of using `importTraj` (or a user supplying their own trajectory model output). The various trajectory functions just plot the data in various ways. For example:

````
head(traj)
Source: local data frame [6 x 12]

  receptor  year month   day  hour hour.inc    lat    lon height pressure               date2       date
     (int) (dbl) (int) (int) (int)    (dbl)  (dbl)  (dbl)  (dbl)    (dbl)              (time)     (time)
1        1  2014     1     1     0        0 51.500 -0.100   10.0    985.2 2014-01-01 00:00:00 2014-01-01
2        1  2013    12    31    23       -1 51.169 -0.329   10.0    985.0 2013-12-31 23:00:00 2014-01-01
3        1  2013    12    31    22       -2 50.836 -0.607   10.0    984.7 2013-12-31 22:00:00 2014-01-01
4        1  2013    12    31    21       -3 50.503 -0.934    9.8    984.4 2013-12-31 21:00:00 2014-01-01
5        1  2013    12    31    20       -4 50.170 -1.314    9.5    983.9 2013-12-31 20:00:00 2014-01-01
6        1  2013    12    31    19       -5 49.841 -1.743    9.1    985.0 2013-12-31 19:00:00 2014-01-01
````

This has the lat/lon that can be used elsewhere. Or am I misunderstanding you?

**Comment by JaysonAP** [comment]
Yes, you could use the trajectory data and find a way to import into GIS. There would likely still need to be additional coding to format the data properly.

However, I'm looking more at the option of taking the trajectories plotted with OpenAir (i.e. the 90th-100th percentile of PM2.5 data) and the ability to take that trajectory data, and export as a KML/KMZ so they can then be overlaid onto source data (or any other data) in a GIS program.

Can the trajectory data be opened within HYSPLIT itself? HYSPLIT has an option to export as KML/KMZ.

Am I explaining myself well enough?

**Comment by davidcarslaw** [comment]
Yes - I see. I am currently looking at better mapping so can take a look at various output options, including KML/KMZ. Currently however, this is not possible...

**Comment by jack-davison** [comment]
Closing this issue as stale; if you are still interested in this, please do reach out again and we can have another look.

Noting that outputs from `trajPlot()` and `trajLevel()` can be expressed as data, which can then be saved locally as a .csv or other file types. Also noting that much has been written on doing [geocomputation in R](https://geocompr.robinlovelace.net/).

``` r
library(openair)

traj_data <- importTraj()

traj_level <- trajLevel(traj_data, plot = FALSE)

traj_level$data
#> # A tibble: 3,984 × 6
#> # Groups:   xgrid, ygrid [3,984]
#>    xgrid ygrid default                          count date                height
#>    <dbl> <dbl> <fct>                            <int> <dttm>               <dbl>
#>  1  -140    81 01 January 2009 to 31 December …     1 2009-11-30 18:00:00 0.0140
#>  2  -137    81 01 January 2009 to 31 December …     1 2009-11-30 18:00:00 0.0140
#>  3  -135    81 01 January 2009 to 31 December …     2 2009-11-30 18:00:00 0.0279
#>  4  -132    81 01 January 2009 to 31 December …     2 2009-11-30 18:00:00 0.0279
#>  5  -132    82 01 January 2009 to 31 December …     1 2009-12-01 00:00:00 0.0140
#>  6  -129    82 01 January 2009 to 31 December …     3 2009-11-30 18:00:00 0.0419
#>  7  -126    82 01 January 2009 to 31 December …     3 2009-11-30 18:00:00 0.0419
#>  8  -125    81 01 January 2009 to 31 December …     1 2009-11-30 15:00:00 0.0140
#>  9  -123    81 01 January 2009 to 31 December …     1 2009-11-30 15:00:00 0.0140
#> 10  -123    82 01 January 2009 to 31 December …     3 2009-11-30 18:00:00 0.0419
#> # … with 3,974 more rows
```

<sup>Created on 2023-02-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
