### ISSUE TITLE
Procedure to remove the frame and cicles around the center of the wind rose

### ISSUE THREAD

**Issue by rasillad** [davidcarslaw/openair#251]
Dear friend, thank you very much for your awesome openair program. It makes it much easier for us to carry out tasks that used to take a lot of time.
I am carrying out an analysis of the wind in the interior of a basin, in which I have several meteorological stations data. I want to represent winds by making wind roses with the openair windRose function. Once prepared, I want to superimpose them on a map with the geographical location of these stations.
I would like to know if it is possible:
- To delete the frame and the circles around the center of the compass rose, so that only the compass rose stands out? More than speed, my interest is on wind direction, and in a map, if the stations are close, the drawins usually paste.
- Is it possible to plot wind roses on an interactive leaflet map, as pollution roses in openairmaps ?

**Comment by jack-davison** [comment]
This is now well served by recent `openairmaps` updates.

See: https://github.com/davidcarslaw/openairmaps and https://bookdown.org/david_carslaw/openair/maps-polar.html.

```r
openairmaps::windroseMap(openairmaps::polar_data, provider = c("CartoDB.Positron"))
```
![image](https://user-images.githubusercontent.com/45171616/216971648-d8f939db-fd82-4361-921e-ee1a886c3e1e.png)
