### ISSUE TITLE
Large file size of graphs using saveRDS()

### ISSUE THREAD

**Issue by dannyparsons** [davidcarslaw/openair#255]
Hi, I've been saving the graph objects of type `openair` as `.RDS` files using `saveRDS()`. The files seem to become unmanageably large. 

For example, using the example for `conditionalQuantile()`, I had to abort the saving after 10 minutes and the file had become 3GB! I tried also just extracting the `trellis` object from the result, but it was still the same.
```r
library(openair)
mydata$mod <- mydata$nox*1.1 + mydata$nox * runif(1:nrow(mydata))
g <- conditionalQuantile(mydata, obs = "nox", mod = "mod")
saveRDS(g, "openair_all.RDS")
saveRDS(g$plot, "openair_trellis.RDS")
```
This doesn't seem to be a general issue with `trellis` objects e.g. this seems to be ok and produces a file of size 12KB.
```r
library(lattice)
Depth <- equal.count(quakes$depth, number=8, overlap=.1)
g <- xyplot(lat ~ long | Depth, data = quakes)
saveRDS(g, "trellis.RDS")
```
I don't know enough about `trellis` objects to understand the possible causes of this. Any ideas on why this happens? And if there might be a way of preventing the files becoming so large? Thanks.

**Comment by jack-davison** [comment]
Afternoon,

This has now been fixed in the dev version.

It was related to having nested data passed to the plotting function, which I have disabled.

You can download the dev version using:

```r
# install.packages("pak")
pak::pak("davidcarslaw/openair")
```

Cheers,
Jack
