### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by mfansler** [davidcarslaw/openair#259]
I wanted to let you know that I created [a Conda recipe for this package on Conda Forge](https://github.com/conda-forge/r-openair-feedstock). This allows those managing their R environments with Conda to use the package (as `conda-forge::r-openair`). It works downstream of CRAN, so it doesn't require you to do anything. If you would like to be added as a maintainer on the feedstock, you can submit a Pull Request, adding your GitHub ID under [the list of maintainers in the meta.yaml file](https://github.com/conda-forge/r-openair-feedstock/blob/135bb3263ddea85151e3480b2c1f655958218cf2/recipe/meta.yaml#L85). You may also be interested in adding a badge to your README here, to indicate the package's availability via Conda, e.g., 

```
[![Conda Version](https://img.shields.io/conda/vn/conda-forge/r-openair.svg)](https://anaconda.org/conda-forge/r-openair)
```
corresponds to 

[![Conda Version](https://img.shields.io/conda/vn/conda-forge/r-openair.svg)](https://anaconda.org/conda-forge/r-openair)

There are others available on [the feedstock's README](https://github.com/conda-forge/r-openair-feedstock/blob/master/README.md).

This is mostly just FYI, so feel free to close this once you've read it.

**Comment by jack-davison** [comment]
Thanks for the heads up! Added to README, which should carry over to the pkgdown site.
