### ISSUE TITLE
Proper interpretation of pollutionRose

### ISSUE THREAD

**Issue by tspeidel-suncor** [davidcarslaw/openair#262]
First of all, thank you for this wonderful package and the significant effort it must have taken.

I have a question about the proper interpretation of the `normalise = TRUE` and `statistic = "prop.mean"` argument of `pollutionRose`. Because it's not always clear to me what's being compared to what, what is the denominator and numerator.

Suppose:
`pollutionRose(mydata, pollutant = "so2", normalise = TRUE, seg = 1)`

![image](https://user-images.githubusercontent.com/66435255/124503831-8cf12400-dd83-11eb-85bf-ee78d6a60284.png)

Is it correct to say:  among all 12 wind sectors, approximately 20% of the highest concentrations (i.e. 10-63) came from the East. However, winds from the East are not very frequent.

Now, how would one interpret this in a similar fashion? 
`pollutionRose(mydata, pollutant = "so2", normalise = TRUE, statistic = "prop.mean", seg = 1)`

![image](https://user-images.githubusercontent.com/66435255/124504013-de011800-dd83-11eb-9669-b916e9ed5caf.png)

**Comment by jack-davison** [comment]
Hi Thomas,

Just to check - have you read the page in the [openair book](https://bookdown.org/david_carslaw/openair/wind-roses.html) on this topic? I believe a very similar example is discussed, only using `nox`.

Happy to clear anything up if there are still things you're uncertain of after giving that a read!

Cheers,
Jack
