### ISSUE TITLE
polarPlot Function - Robust and Quantile slopes

### ISSUE THREAD

**Issue by BORE2021** [davidcarslaw/openair#266]
Dear Dr. Carslaw,

Sorry for taking some of your time.

To the best of my knowledge, it is not yet possible to specify the radius for pollution dispersion using the polarPlot function, so I would like to know the default radius (distance) at which the pollutants are spread away from the center of the plot.

Additionally, how can we explain to a non-specialist the technical terms "Robust" and "Quantile" slopes and in which case these functions could be useful in air pollution analysis?. I could not find a detailed explanation in the openair manuals.

Thank you for your time, and I hope to hear from you soon.

**Comment by jack-davison** [comment]
Good afternoon,

Polar plots don't really visualise dispersion; one can think of them as polar heatmaps showing smoothed concentrations as a function of both wind speed and wind direction. An easy way to illustrate this is to consider them in relation to the polar frequency plot, which is much more obviously a heatmap. Note that the two are very similar in appearance, the `polarPlot()` is just a lot more smooth.

``` r
openair::polarFreq(openair::mydata,
                   "nox",
                   statistic = "mean",
                   trans = FALSE)
```

![](https://i.imgur.com/T23Pe9W.png)

``` r

openair::polarPlot(openair::mydata, "nox")
```

![](https://i.imgur.com/NH9cveO.png)

<sup>Created on 2023-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Much has been written about the pairwise statistics in the openair book, specifically this page: https://bookdown.org/david_carslaw/openair/sections/directional-analysis/polar-plots.html#sec-polar-pairwise. Does this provide an appropriate description for your purposes?

For the layperson, I may choose to describe pairwise polar plots as follows:

> In air quality science, we often express how two different variables (meterological conditions, pollutant concentrations, human activity, etc.) correlate. For example, ozone is typically correlated with high temperatures, which is to say when ambient temperature goes up, so does ozone. NOx is correlated to traffic count, which is to say that when there's more traffic on the roads we typically measure more NOx.
> 
> Correlations can be very useful when we consider sources. For example, if PM is correlated with NOx, we may determine they come from a shared combustion source. If it is instead correlated with SO2, we might consider an industrial source. A high ratio of PM2.5 to PM10 (lots of fine particulate) may suggest a combustion source, whereas a low ratio (lots of coarse particulate) may suggest an industrial source.
> 
> Pairwise polar plots extend this concept to consider correlations under different wind conditions. They allow us to say that two pollutants correlate *when winds blow in a certain direction*. This can not only help identify the type of source, but also the likely direction it is relative to the measurement site. For example, if two metal species are only highly correlated when the wind is blowing from the east, this is evidence to look for an industrial source to the east of our measurement site. (NB: see Figure 8.12 and associated text in the openair book for an example).

As this is stale (2 years) I will close this issue, but if you have further questions please just give us a shout!

Jack
