### ISSUE TITLE
How to read variable which starts with a number 

### ISSUE THREAD

**Issue by morshedahmed17** [davidcarslaw/openair#268]
Hi, 

The name of one of the variables that I am dealing with is 2,4-DNP. However, openair couldn't read this and read like "X2.4.DNP". So, how can I read the variable?

Regards, 
Morshad

**Comment by rs028** [comment]
It's not a matter of openair. In R variable names cannot start with a letter (and cannot contain a comma either).
You have to give the variable a different name.

**Comment by schonhose** [comment]
@rs028 That is not entirely correct. In R you can access these variables by encapsulating them using backticks. See also [this reference on how it works with dplyr](https://newbedev.com/dplyr-nonstandard-column-names-white-space-punctuation-starts-with-numbers).
