### ISSUE TITLE
Fix color scale in polarPlot()

### ISSUE THREAD

**Issue by tspeidel-suncor** [davidcarslaw/openair#269]
Is there a way to fix the colour scale so it remains the same, for instance when producing multiple plots?
I know once can use `polarPlot(..., type = "year")` but I don't want a grid of graphs as I'm trying to create an animation.

```
library(openair)
library(dplyr)
library(lubridate)

polarPlot(filter(mydata, year(date) == 1999),
          pollutant = "nox")

polarPlot(filter(mydata, year(date) == 2004),
          pollutant = "nox")
```

![image](https://user-images.githubusercontent.com/66435255/133127278-093c37b6-a1e8-4d94-924a-bafe5d4d977c.png)

**Comment by davidcarslaw** [comment]
Yes - you can set limits as an option e.g. `limits = c(0, 300)`. Alternatively, if you combine both data sets and have a column that identifies each e.g. "data 1" and "data 2" in a column called `data_type`, you can then add the option `type = "data_type"`. Also, have a look at https://bookdown.org/david_carslaw/openair/

**Comment by davidcarslaw** [comment]
Yes, you can use the option `upper` e.g. `upper = 20`
