### ISSUE TITLE
Strip background colour in openair objects

### ISSUE THREAD

**Issue by dpinxter** [davidcarslaw/openair#27]
Plotting a polar plot in the interactive device gives white strip backgrounds for the trellis plots. 

Storing the plot object and plotting several plots on a pdf device (using gridExtra::marrangeGrob) gives the strip backgrounds in the ugly lattice default colour. Here is the code conceptually:

plotlist <- list()

pdf(somefile,onefile = T)

for (i in somevector) {
 p <- polarPlot(somedata, somepollutant, type=i)
 plotlist <- c(plotlist,p[1])
}

gridExtra::marrangeGrob(grobs=plotlist, ncol=2, nrow=3)

dev.off()

I can get the white strip backgrounds in my pdf if I include 

par.settings=list(strip.background=list(col='white'))

to the polarPlot call, but I guess the stored object should be the same as the automatically printed one?

On a sidenote: In the code above, all the individual polar plots would be printed, even though I call them inside the for loop (where usually automatic printing is suppressed in R). This results in all the individual plots to be stored in my pdf in addition to the overview on one page (produced by the final marrangeGrob call. Is there a way to avoid this?

**Comment by jack-davison** [comment]
Closing as this appears to have been fixed.

To stop printing the individual polar plots, you can use the (relatively new) `plot` argument which turns off all of the "side effect" printing.

Cheers,

``` r
plotlist <- list()

data <- dplyr::mutate(mydata, site = "my1")

pdf("test.pdf", onefile = T)

for (i in c("nox", "no2", "o3", "pm10", "so2", "co")) {
  p <- polarPlot(data, i, type = "site", plot = FALSE)
  plotlist <- c(plotlist, p[1])
}

gridExtra::marrangeGrob(grobs = plotlist, ncol = 2, nrow = 3)

dev.off()
```
![image](https://user-images.githubusercontent.com/45171616/217759699-a0c72f53-d840-40a9-9b67-2a05b5e45e09.png)
