### ISSUE TITLE
trajPlot colored by height

### ISSUE THREAD

**Issue by ajgor74** [davidcarslaw/openair#270]
Dear Carlslaw
there 's any option /suggestion to improve the trajPlot function so that I can use the trajectory height -that is already included on the df along Lat and Lon- to change the color of each point along every trajectory plot?
tk

**Comment by jack-davison** [comment]
Hi ajgor74, 

This is something I'm sure that can be looked into when there's time to.

For now, this is something that can be achieved currently using the development version of [openairmaps](https://github.com/davidcarslaw/openairmaps/tree/master/R).

``` r
openair::trajPlot(openairmaps::traj_data, pollutant = "height")
```

![](https://i.imgur.com/6x7cAlx.png)

``` r
openairmaps::trajMapStatic(openairmaps::traj_data, xlim = c(-70, 20)) +
  ggplot2::scale_color_gradientn(colours = openair::openColours())
```

![](https://i.imgur.com/HQIhxnp.png)

<sup>Created on 2023-03-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
