### ISSUE TITLE
Openair returning NULL value for some places using importAURN function. 

### ISSUE THREAD

**Issue by holliealfieri** [davidcarslaw/openair#274]
sorry I am a beginner, but I was wondering why importAURN works fine in some places and others return NULL. I have done the recent update, yet I can't access the values which I could before the update. Any help would be immensely appreciated.

Thanks, 

Hollie

**Comment by avila-a** [comment]
I am having a similar issue although it mainly happens with ImportAURN and ` data_type = "daily"`. 

An example would be 
```
aurn_data <- importAURN(site = "my1",  year = 2009, 
                   pollutant = "no2", 
                   data_type = "daily") 
```

Thanks!

Antonio

**Comment by davidcarslaw** [comment]
Hi

This isn't quite implemented yet but should be soon (along with other stats). The servers that host the data are being upgraded ... You can however obtain some useful annual stats data:

```test <- importAURN(data_type = "annual", year = 2020)```

We'll make these other data available as soon as we can (daily, monthly etc.)

Thanks
David

**Comment by avila-a** [comment]
Many thanks for your response David. I will wait for the servers and stop trying to fix it.

Best,

Antonio
