### ISSUE TITLE
wind direction in importSAQN function

### ISSUE THREAD

**Issue by AlanMcDonaldSEPA** [davidcarslaw/openair#28]
Would it be possible to add modelled wind direction to the importSAQN function, as it only seems to output wind speed? I am able to get wind speed if I use the importAURN, but this is only for a few Scottish locations.

Thanks

Alan

**Comment by davidcarslaw** [comment]
I will look to see why wd is not included. You might also be interested in accessing surface met data more generally. Take a look at my `worldmet` package https://github.com/davidcarslaw/worldmet - which might be of interest. You might need to wade through various terms and conditions of usage on the NOAA site to ensure you can use it without issue...

**Comment by AlanMcDonaldSEPA** [comment]
Many thanks, worldmet looks useful though unfortunately I can't get it to work, perhaps due to permissions of accessing ftp sites.

**Comment by davidcarslaw** [comment]
What is the error you get?

**Comment by AlanMcDonaldSEPA** [comment]
This is what I get:

> getMeta(site="edinburgh")
        USAF  WBAN             STATION CTRY ST CALL     LAT     LON ELEV(M)      BEGIN        END         code
1325  031600 99999           EDINBURGH   UK    EGPH  55.950  -3.373    41.1 1973-01-01 2015-08-31 031600-99999
1331  031660 99999 EDINBURGH GOGARBANK   UK          55.933  -3.350    57.0 2003-03-30 2015-08-31 031660-99999
26028 956760 99999           EDINBURGH   AS    YPED -34.703 138.621    20.4 1972-11-17 2015-08-30 956760-99999
> edindata <- importNOAA(code="031660-99999", year=2012)
Warning messages:
1: In readLines(z) : InternetOpenUrl failed: 'The operation timed out
'
2: Data for 2012 does not exist on server

**Comment by davidcarslaw** [comment]
Strange - maybe there are some restrictions in accessing external sites where you work. Just checked and the data do exist. Does typing update.packages() in the R console work OK i.e. can you update your R packages in this way?

**Comment by AlanMcDonaldSEPA** [comment]
Yes, update.packages() works OK. I think there may be some ftp restrictions, but I'm not sure exactly what.

**Comment by davidcarslaw** [comment]
I can only think there is some sort of restriction. No one else has mentioned this. I will take a closer look. Can you see  ftp://ftp.ncdc.noaa.gov/pub/data/noaa/?

**Comment by AlanMcDonaldSEPA** [comment]
No, I'm unable to access that ftp site. I think it may be restrictions that we have.

**Comment by davidcarslaw** [comment]
Shame! Can't do anything about that. Might be worth asking for an exception to access this ftp site? You will have to try it on a computer outside your organisation to see how useful these data are.
