### ISSUE TITLE
Control of labels on polarPlot

### ISSUE THREAD

**Issue by rs028** [davidcarslaw/openair#286]
I am trying to control the size of the labels on a polar plot. For example, in the attached plot I want to change the font size of wind speed and direction (ie., "N", "E", "S", "W", "2", "4 ws", "6", etc...)
![image](https://user-images.githubusercontent.com/7703778/163226547-c074e8a7-6143-469f-8403-ace1730a5333.png)
They don't seem to respond to `cex` nor to `par.strip.text` (which can control the font size of the strip labels (eg, "cl2.ppt"). The manual is not very clear on how to do this.

Also, how can the text in the strip labels be changed? eg, from "cl2.ppt" to "Cl2 (ppt)". Normally a lattice levelplot accepts an argument of the type: `strip=strip.custom(factor.levels = `, but this doesn't seem to work for the openair `polarPlot` function.

**Comment by jack-davison** [comment]
Hello,

1. Font size can be controlled using `fontsize` in almost all `{openair}` functions.

2. Renaming strip text is probably best done by renaming your column names (if using `pollutant`) or column values (if using `type`). `{openair}` currently does not have an option to control these after the plot has been made.

    - To rename columns, you could use `dplyr::rename()` or use a more base R method (shown below)
    - To replace values within the columns, you could use `dplyr::case_when()`, `dplyr::case_match()` (demonstrated below), or a more base R method.

Some examples:

``` r
data <- openair::mydata

# rename facets (polltuant columns)
data$`NOx (ug/m3)` <- data$nox
data$`SO2 (ug/m3)` <- data$so2
openair::polarPlot(data, c("NOx (ug/m3)", "SO2 (ug/m3)"),
                   normalise = TRUE)
```

![](https://i.imgur.com/sIy7QNX.png)

``` r

# rename facets (other columns)
# (lots of ways to do this - dplyr makes it easiest:)
unique(iris$Species)
#> [1] setosa     versicolor virginica 
#> Levels: setosa versicolor virginica

iris$Species <-
  dplyr::case_match(iris$Species,
                    "setosa" ~ "Plant1",
                    "versicolor" ~ "Plant2",
                    "virginica" ~ "Plant3")

unique(iris$Species)
#> [1] "Plant1" "Plant2" "Plant3"

# font size
openair::polarPlot(data, fontsize = 10)
```

![](https://i.imgur.com/9DjMYNv.png)

``` r
openair::polarPlot(data, fontsize = 20)
```

![](https://i.imgur.com/JXIEqLC.png)

``` r
openair::polarPlot(data, fontsize = 30)
```

![](https://i.imgur.com/HdAYZ6v.png)

<sup>Created on 2023-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
