### ISSUE TITLE
Where is the function 'do' used in windRose

### ISSUE THREAD

**Issue by shirleyxyliu** [davidcarslaw/openair#289]
Hi David, thanks for your lovely windRose function. As I am customizing the max of wind speed & digits of mean, there is an error showing "could not find function 'do'" (See below). Could you please kindly point to me where is that function? 

Error in do(., prepare.grid(.)) : could not find function "do"

Thanks, 
Shirley

**Comment by karlropkins** [comment]
Shirley, 
do is in dplyr.
If you are running code from openair locally try either loading first dplyr or use:
dplyr::do rather than do in code.
Hope that helps?

**Comment by jack-davison** [comment]
`do()` is indeed in `dplyr`. It was also deprecated in `dplyr` 1.0.0, so probably needs revisiting at some stage!

For now, do ensure that `openair` and `dplyr` are properly installed. Perhaps uninstall and reinstall the packages and see if that sorts your issue, if you're still experiencing it.

Going to close this issue and reopen another to scrape through `openair` looking for deprecated functions. Do feel free to reopen this if you're still having issues and we can have a closer look for you.

Cheers,
Jack
