### ISSUE TITLE
timePlot and BST

### ISSUE THREAD

**Issue by jmclaren-17** [davidcarslaw/openair#295]
Hi all, 

I hope someone will be able to assist me.  I have some traffic data and I am looking to plot a simple diurnal profile of counts for a specific day.  The data has been obtained through an API and the date formatted to GMT as per best practice.  I understand that openair handles the daylight savings issue in many of its functions.  However, I had assumed when plotting my timePlot it would offset the time given my particular day is in July and affected by BST.  So my peak in traffic occurs an hour behind in the graph compared to how it is in reality.   I paste my code below which sums 5 minute values for each hour for a subset of my data below.

```
timePlot(subset(selectByDate(traffic_data, start = "2022-07-01", end = "2022-07-01"), site_id == "41770"& class == "total_all"),
pollutant = "countTotal", type = "class", avg.time = "hour",
statistic = "sum", pch = 1)
```

I have seen someone in a previous query was able to obtain this by merging two dataframes with different time zones some time ago, but I want to avoid this complicated procedure to avoid issues - I understand having the data as one fixed zone is paramount.  Is there a way to offset the axis to account for BST without changing the data?  Or do I have to come up with some sort of workaround where I add an hour to the date for the plot?  I wish to avoid this due to potential issues later down the line.  

Does anyone know how many of the other plots such as timeVariation handle BST?  I have played around with the sample "mydata" and subset by type = "dst".  The average diurnal plot shows that the peaks occur at the same time of day between GMT and BST, so it appears to be off-setting things correctly.  Just not specifically in timePlot when focussing in on a particular date. 

Kind regards,

**Comment by davidcarslaw** [comment]
Thanks for the message. Recent versions of openair should plot in the time zone of the data that is provided. It will provide a message if it detects data in local time e.g. BST. It can indeed be useful to plot temporal data in local time and the best way to do this is to tweak how the time zone is represented in your data.

For example, given the `mydata` data set (all GMT), we can express the time zone in local time (which means it will represent daylight saving - BST in summer). The easiest way to do this I think is to use the `lubridate` package:

```
mydata$date <- with_tz(mydata$date, tz = "Europe/London")
```

Then try a plot e.g.

```
timeVariation(mydata, ci = FALSE)
```

which should show the diurnal plot in local time, meaning for example that rush hour is not shifted as it would be in GMT.

This ought to work, but let me know if you have a problem.

When it comes to combining data in different time zones, R takes care of this, which is very useful. So, if one data set was in GMT and another in local time (or any other time zone), joining should make sure the times are actually synchronous - although you might then want to choose how the time is represented as shown above. This sort of thing is important for global data such as that from my `worldmet` package (all GMT/UTC) or Hysplit back trajectories (all GMT/UTC) but where there is a need to combine AQ data from potentially any other time zone.

You can list all the time zone names by:

```
OlsonNames()
```

I should probably add a short section on this issue to the [openair manual](https://bookdown.org/david_carslaw/openair/openair-package.html) ...

**Comment by jmclaren-17** [comment]
Thanks @davidcarslaw for your quick response David, helpful as always.  I think a small section to supplement the existing parts on DST would be helpful, particularly with images of the impact.  

Your lubridate solution seems to have worked (see below).  I saved subsets of my data to compare the changes GMT and BST.  

`timePlot(selectByDate(subset(GMT, site_id == "41770" & class == "total_all"),
 start = "26/07/2022", end = "26/07/2022"),
pollutant = "countTotal", type = "class", avg.time = "hour",
statistic = "sum", pch = 1)`

This code produced the following image: 

![image](https://user-images.githubusercontent.com/110392766/182164444-7e098885-b5a0-4ed8-bd10-8b9e4f28cbde.png)

For the BST data I used the code as you suggested:

`BST$date <- with_tz(BST$date, tz = "Europe/London")`
`timePlot(selectByDate(subset(BST, site_id == "41770" & class == "total_all"),
 start = "26/07/2022", end = "26/07/2022"),
pollutant = "countTotal", type = "class", avg.time = "hour",
statistic = "sum", pch = 1)`

This produces the following image:

![image](https://user-images.githubusercontent.com/110392766/182164914-ce154c89-ab4d-4fcf-bb3d-608fb3300155.png)

You will see the data has correctly shifted to the right of the axis to represent BST and the peaks are now in the right place.  So this has solved my issue.  Using the BST data I was warned as you suggested that "Detected data with Daylight Saving Time.".

I have also had a look at what happens for a day plotted from GMT i.e. 08/03/2022.  Both plots are the same for the GMT and BST datasets which show the peaks in the correct position.  

So to confirm, the with_tz() function adds one hour to my data which is imported as UTC/GMT between March and October (Daylight saving hours).  Those winter hours (GMT) remain unchanged?  

My question now is what is the impact on plots such as timeVariation over a longer timeframe e.g. 1 year.  If I were to use the GMT dataset, would the function automatically adjust for DST or do the changes in human behaviour just get averaged over the peak hours and the data presented as GMT/UTC?  I am inclined to keep everything as GMT / UTC as that is how all of our datasets are recorded.  Or is it better to work with my data in "Europe/London" timezone? 

Sorry for the essay with this!  I want to just be absolutely sure whats going on with the time as we have multiple data sources recorded by different instruments and want to ensure it all matches up and is presented in the correct way. 

Thanks again,
Josh

**Comment by davidcarslaw** [comment]
I think that's what is expected...

To confirm the `with_tz` function - it basically allows you to take any data in any time zone and express it in another time zone of your choosing. It has the effect of shifting the hours in BST when the original data were in GMT. Here are some examples where it is the **same absolute time** in all cases, but just expressed in different time zones. My computer is in BST, so GMT is an hour earlier and the time in Athens (for example!) is 6.15 pm.

```
Sys.time()
[1] "2022-08-01 16:16:30 BST"
> with_tz(Sys.time(), tz = "GMT")
[1] "2022-08-01 15:16:33 GMT"
> with_tz(Sys.time(), tz = "Europe/Athens")
[1] "2022-08-01 18:16:45 EEST"
```

I think for your use where you want to show local variations, keeping the time in local time makes sense. Generally when you read data into R (such as air quality data in the UK) it will be in GMT, so the additional step of expressing that as local time is often what you need...

Quite which is best to work with depends on what you are doing. My preference is to keep everything in GMT (as mentioned above, most data sets are probably GMT to begin with). However, if I was wanting to show diurnal variations in concentrations it often (but not always) makes sense to express the time as local time to capture things that vary by local time such as rush hours / traffic. By not expressing in local time the effect will be to 'smear-out' peaks in rush hour concentrations and the like because they occur at two different hours if expressed as GMT...

I hope that makes sense! 

David

**Comment by jmclaren-17** [comment]
Thanks @davidcarslaw 

That makes complete sense, I have run some tests on the sample "mydata" (with GMT) and understand exactly whats doing on.  Running a timeVariation on the dataset using GMT for the NOx suggests a slight shift in the peak in the BST months, but on average for the whole dataset it is minimal.  

I hope the below may be helpful to others. 

Running the same for the BST dataset shows the peak at the same time across the months.  Its good to see it visually and I am much happier about whats going on behind the scenes.  I appreciate that there are more variables that control NOx than just human activity, but it is slightly visible in the data despite this.  Comparison in the shift of human activity can be seen mainly in the AM peak for November, January and February compared to the summer months reasonably clearly.  The impact of the "with_tz()" function can be seen when comparing the two plots i.e. the profile is shifted for the summer months in the BST plot. 

`GMT<-mydata`
`BST<-mydata`
`BST$date<-with_tz(BST$date, tz = "Europe/London")`
`a<-timeVariation(GMT, main = "GMT", ci = FALSE, type = "month", pollutant = "nox")`
`print(a$plot$hour)`
`a<-timeVariation(BST, main = "BST", ci = FALSE, type = "month", pollutant = "nox")`
`print(a$plot$hour)`

GMT dataset plot:
![image](https://user-images.githubusercontent.com/110392766/182194478-a088196a-76e1-47c5-a997-b124e1b9e167.png)

BST dataset plot:
![image](https://user-images.githubusercontent.com/110392766/182195701-1946894e-5c22-4691-a9bb-5145bb9c7187.png)


Thanks again, 
Josh

**Comment by jack-davison** [comment]
Closing this as it appears to have been resolved. Thanks for your detective work Josh!
