### ISSUE TITLE
Error with running TaylorDiagram

### ISSUE THREAD

**Issue by fghiami** [davidcarslaw/openair#298]
When I run TaylorDiagram, setting type = "my stations name", it gives me the error:

Error in unit(0.5 * showr, "strwidth", list(right)) : 
  no string supplied for 'strwidth/height' unit

Any solution for that?

**Comment by jack-davison** [comment]
Hi fghiami,

Please provide a [reproducible example](https://bookdown.org/david_carslaw/openair/sections/appendices/appendix-gethelp.html#sec-reprex) and we can assist you.

We'd ideally need the data you're using and the code you're running. Then we can try to recreate your problem on our computers.

Cheers,
Jack

**Comment by jack-davison** [comment]
Actually, I have been able to recreate this quite simply;

``` r
openair::TaylorDiagram(openairmaps::polar_data,
                       "nox", "no2",
                       type = "site")
#> Error in unit(0.5 * showr, "strwidth", list(right)): no string supplied for 'strwidth/height' unit
```

![](https://i.imgur.com/lELny1G.png)

<sup>Created on 2023-09-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This function is very long in the tooth; @davidcarslaw is this something you'd be able to investigate?

**Comment by Francisca-Z** [comment]
Hi @jack-davison, I saw the discussion yesterday  as I  came into the same error, but for the "season" type, while trying to run this: 
TaylorDiagram( gathered, 
              obs = "obs_tas", 
              mod = "tas", 
              group = "models",
              type = "season")
Example of my data are attached here as csv file.
I hope this helps. 
Thanks in advance!
[example_data.csv](https://github.com/davidcarslaw/openair/files/13646653/example_data.csv)
