### ISSUE TITLE
Fix Y-axis scale in timeProp function

### ISSUE THREAD

**Issue by anhduytran98** [davidcarslaw/openair#305]
Dear, I want to ask how to manage the same scale of Y-axis in the [Time proportion plots], like this: 
Thank you very much

![InkedwsB](https://user-images.githubusercontent.com/74843979/200110131-a8103865-8522-43f7-9b6b-24b6d3e2b100.jpg)
![InkedWS_D](https://user-images.githubusercontent.com/74843979/200110137-48b15fa0-bb3b-4c51-8b24-2d3951abed16.jpg)

**Comment by jack-davison** [comment]
Hello,

You can control the y axis limits by using the `ylim` argument, which isn't listed in the `openair` documentation but is passed down to the underlying `lattice` code. So you could make multiple plots have matching y axes by setting them all to be the same values.

``` r
openair::timeProp(openair::mydata, "nox", "wd", "year", ylim = c(0, 100))
#> Warning: 219 missing wind direction line(s) removed
```

![](https://i.imgur.com/22WG6xJ.png)

``` r
openair::timeProp(openair::mydata, "nox", "wd", "year", ylim = c(0, 200))
#> Warning: 219 missing wind direction line(s) removed
```

![](https://i.imgur.com/OEIgUja.png)

``` r
openair::timeProp(openair::mydata, "nox", "wd", "year", ylim = c(0, 300))
#> Warning: 219 missing wind direction line(s) removed
```

![](https://i.imgur.com/BpN8TaJ.png)

<sup>Created on 2023-02-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
