### ISSUE TITLE
Mean in Pollution Rose differs from normal mean 

### ISSUE THREAD

**Issue by Saolaina** [davidcarslaw/openair#308]
Hi,
I need to know how the average for the pollution rose is calculated, as when I calculate the average of the pollutant I get a different result than with the package.

Cheers,
Saolaina

e.g.

![image](https://user-images.githubusercontent.com/118790159/203219886-21ee522f-ad7f-45a9-a371-256bf5d040eb.png)

**Comment by schonhose** [comment]
Is it possible that the mean in the plot is based on concentrations with meteorological data only? In other words, samples without meteorological data might be omitted.

**Comment by jack-davison** [comment]
@schonhose is spot on; `pollutionRose()` drops missing met data first, as that is the data visualised in the rose itself.

``` r
mean(openair::mydata$nox, na.rm = TRUE)
#> [1] 178.7986

mean(openair::mydata$nox[!is.na(openair::mydata$ws)], na.rm = TRUE)
#> [1] 178.6236

openair::pollutionRose(openair::mydata)
```

![](https://i.imgur.com/Lre7Sey.png)

<sup>Created on 2023-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
