### ISSUE TITLE
polarPlot x limits (ie fixing the wind speed scale)

### ISSUE THREAD

**Issue by clarkdk** [davidcarslaw/openair#32]
In `polarPlot`, is it possible to set the scale range limits of the radial `x` variable (usually wind speed)? 
This would be analagous to setting the `pollutant` range using the argument `limits = c(lower, upper)`, but for the wind speed scale. 

I am comparing polarPlots between several stations with different wind data, and it would be helpful to fix the wind speed scale on all the plots. 

A second question is: Is it possible to extract the wind speed (x) scale choosen by polarPlot programmatically? This would be to automate the fixing of wind speed scale for a group of stations.

**Comment by clarkdk** [comment]
Sorry, I now see the `upper=` argument, which sets the upper limit of the wind speed (x) scale -- which answers my first question.

My second question remains, and refers to obtaining the value of `upper`automatically set by `polarPlot`, if the `upper=` argument is not specified (`upper = NA` is default).

**Comment by davidcarslaw** [comment]
If `upper` is not supplied it is just set at the maximum wind speed...
