### ISSUE TITLE
Compilation error in version 2.14 

### ISSUE THREAD

**Issue by rs028** [davidcarslaw/openair#321]
Updating `openair` from version 2.13 to 2.14, I get the following compilation error:

```
Error in parse(outFile) : 
  /tmp/Rtmp7uKSLg/R.INSTALLb758732d8d97/openair/R/importUKAQ.R:192:23: unexpected '>'
191:           
192:           dat <- dat |>
                           ^
ERROR: unable to collate and parse R files for package ‘openair’
```
I have encountered this on two different Linux systems, with different versions of R (3.6 and 4.2). I never had any problem with previous updates using the same method (`update.packages()` from the R console).

**Comment by GeraldCNelson** [comment]
The |> is the new pipe added to a recent version of R. If you update to the latest version of R that should be fine.

Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
Skype: jerrynelson
http://bit.ly/1arho7d

From: "R. Sommariva" ***@***.***>
Reply-To: davidcarslaw/openair ***@***.***>
Date: Thursday, February 2, 2023 at 6:57 AM
To: davidcarslaw/openair ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [davidcarslaw/openair] Compilation error in version 2.14 (Issue #321)


Updating openair from version 2.13 to 2.14, I get the following compilation error:

Error in parse(outFile) :



  /tmp/Rtmp7uKSLg/R.INSTALLb758732d8d97/openair/R/importUKAQ.R:192:23: unexpected '>'



191:



192:           dat <- dat |>



                           ^



ERROR: unable to collate and parse R files for package ‘openair’



I have encountered this on two different Linux systems, with different versions of R (3.6 and 4.2). I never had any problem with previous updates using the same method (update.packages() from the R console).

**Comment by davidcarslaw** [comment]
Thanks. I am going to revert this change (to not use native pipe) because many people are using older versions of R. There will be a new release to CRAN shortly.

David
