### ISSUE TITLE
importAURN endpoints 

### ISSUE THREAD

**Issue by jmclaren-17** [davidcarslaw/openair#325]
I have been looking at how to download R data files using the importAURN call.  I was wondering if there was any other formats available than .RData files when accessing.  Perhaps there is some additional endpoints available through API access?

**Comment by jack-davison** [comment]
Hi @jmclaren-17,

There are a few end points to access AURN data.

- The one you're aware of - `importAURN()` *et al.*, which reads .RData objects from UK-AIR. If you have a look at the source code in https://github.com/davidcarslaw/openair/blob/master/R/importUKAQ-utils.R and https://github.com/davidcarslaw/openair/blob/master/R/importUKAQ.R you can see the URLs for these.

- There is the [Data Selector Tool](https://uk-air.defra.gov.uk/data/data_selector) which is very manual and probably not what you're after.

- There are flat CSV files for the AURN sites (e.g., https://uk-air.defra.gov.uk/data/flat_files?site_id=MY1 for Marylebone Road).

- There is the Sensor Observation Service (https://uk-air.defra.gov.uk/data/about_sos) and Atom Download Service (https://uk-air.defra.gov.uk/data/atom-dls/) if you're happy working in XML.

I'm not sure which language you'd prefer to use, but as I know Python is popular there is a `PyAURN` library (https://pypi.org/project/pyaurn/) which accesses the RData objects. This is currently unaffiliated with the `openair` R package so any questions would have to go to its authors.

Hope this helps!

Jack
