### ISSUE TITLE
[Question]: How to fix missing Dates Issue in R Openair 

### ISSUE THREAD

**Issue by rowlandemmanuel** [davidcarslaw/openair#327]
Hello,

Please can anyone help with this issue? 

I'm trying to generate a summary plot of my pollutants data with the code below:

>setwd("C:/Documents_R")
>Data=read.table("K_data.csv", header=TRUE,sep=",")
>Data$date<- as.POSIXct(strptime(Data$Date, format = "%Y-%m-%d %H:%M:%S"))
>summaryPlot(mydata=Data, avg.time="hour")

I keep getting this error message  "There are some missing dates on line(s) 2065"
Please how do I fix this?

**Comment by jack-davison** [comment]
Hi,

That error message usually appears if there are missing dates (i.e., `NA` values in your "date" column).

If you do something like the below, does that solve your issue?

```r
setwd("C:/Documents_R")
Data=read.table("K_data.csv", header=TRUE,sep=",")
Data$date<- as.POSIXct(strptime(Data$Date, format = "%Y-%m-%d %H:%M:%S"))
Data <- Data[!is.na(Data$date),]
summaryPlot(mydata=Data, avg.time="hour")
```

If not, we'll be better able to diagnose your problem if you provide access to "K_data.csv". You'll be able to attach it to a reply to this issue.

Cheers,
Jack
