### ISSUE TITLE
[Bug]: summaryPlot % data availability showing incorrect value

### ISSUE THREAD

**Issue by bws200** [davidcarslaw/openair#329]
Hi,

I'm having an issue with the % data availability in the summaryPlot function when loading daily averaged data. The issue seems to be around data types but I haven't been able to isolate the problem in the function internals. If I just leave the date as is the % shows around 49.5 % when it should be near 99%. When I convert the date field with as.character() the % calculates correctly. Code below and tried to attach the files needed

Thanks!

```r
library(dplyr, warn.conflicts = FALSE)
library(openair)

df_hourly <- read.csv("hourly.csv") |> 
  mutate(date = lubridate::ymd_hm(date))

df_daily <- read.csv("daily.csv") |> 
  mutate(date = lubridate::ymd(date))

df_daily_character <- df_daily |> 
  mutate(date = as.character(date))

summaryPlot(df_hourly)
summaryPlot(df_daily)
summaryPlot(df_daily_character)

```
Update to attach files [daily.csv](https://github.com/davidcarslaw/openair/files/10834942/daily.csv) and [hourly.csv](https://github.com/davidcarslaw/openair/files/10834944/hourly.csv)

**Comment by jack-davison** [comment]
Hi,

I can't seem to recreate your issue using your `daily.csv` file. Could you clarify which version of `{openair}` you're using?

``` r
library(openair)

df_daily <- read.csv("C:/Users/jd6th/Downloads/daily.csv") |> 
  dplyr::mutate(date = lubridate::ymd(date))

summaryPlot(df_daily)
#> Detected data with Daylight Saving Time.
```

![](https://i.imgur.com/8GXB78a.png)

``` r

df_daily_character <- df_daily |>
  dplyr::mutate(date = as.character(date))

summaryPlot(df_daily_character)
```

![](https://i.imgur.com/9pegNiS.png)

<sup>Created on 2023-03-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bws200** [comment]
Thanks for the reply! I am using ```openair``` version 2.13.

After a bit of googling maybe this recreates the error for you?

```r
library(openair)
library(tidyverse)

Sys.setenv(TZ='NZ')

df_daily <- read.csv("daily.csv") %>% 
  dplyr::mutate(date = lubridate::ymd(date))

summaryPlot(df_daily)

```
![image](https://user-images.githubusercontent.com/101080796/224565607-e9d0324c-fe20-4d6e-a009-78965f137538.png)

```r

Sys.setenv(TZ='Europe/London')

df_daily <- read.csv("daily.csv") %>% 
  dplyr::mutate(date = lubridate::ymd(date))

summaryPlot(df_daily)

```
![image](https://user-images.githubusercontent.com/101080796/224565752-86d0be4e-2ea9-49ff-a333-810e5da57199.png)

 I didn't say I was using it in NZ timezone sorry. The why is beyond me

**Comment by bws200** [comment]
Closing this as it's my issue rather than openair's. Just need to include the timezone as pretty clearly spelled out in the documentation 😊 Thanks for the efforts maintaining it

```r
library(openair)
library(tidyverse)

df_daily <- read.csv("daily.csv") |> 
  mutate(date = ymd(date, tz = "Etc/GMT+12"))

summaryPlot(df_daily)
```

![image](https://github.com/davidcarslaw/openair/assets/101080796/49ec6dee-9b74-4e26-9827-cb69c3a76262)
