### ISSUE TITLE
trajCluster frequency (%) legend

### ISSUE THREAD

**Issue by JulioCM** [davidcarslaw/openair#33]
Not a bug. But it would be very nice if trajCluster could have the option of showing the frequencies of each cluster as the Hysplit GUI does.

**Comment by davidcarslaw** [comment]
Yes - good idea. I will do that shortly...

**Comment by lyggd** [comment]
Hi David,
I just want to follow up that if you added this option to ```trajCluster ```. It will be very helpful.
Thank you very much.

**Comment by davidcarslaw** [comment]
`trajCluster` should now add the percentage of total trajectories to each cluster. It will do this by default. Just let me know if there is a problem.

**Comment by lyggd** [comment]
David,
I update my 'openair'  package by 
`require(devtools)
install_github('davidcarslaw/openair')` The code worked on last Friday, but it does not work today agaion. I can not see the percentage of total trajectories to each cluster.
Would you check it for me ?
Happy Chinese new year !
Yi

**Comment by JulioCM** [comment]
Great, many thanks David

**Comment by lyggd** [comment]
Sometimes if you do seasonal plots, the number of percentage will overlap, which is hard to read.
If there any way to solve this problem ?
Thanks
![cluster seaonal_map_o3](https://cloud.githubusercontent.com/assets/12972221/13158302/93a10aa0-d649-11e5-8bc7-66543e346e52.png)

**Comment by davidcarslaw** [comment]
I did fix the decimal places - should only be one now. Also, try setting `xlim` and `ylim` to zoom in more to the map, which should improve clarity. It is quite hard to sort label placement automatically...

**Comment by lyggd** [comment]
Great ! Thanks a lot, David

**Comment by JulioCM** [comment]
only problem, how can I change the points size?

Many thanks

**Comment by davidcarslaw** [comment]
Do you mean the size of the font labels? You can change the overall size of fonts in openair function e.g.

````
trajCluster(traj, fontsize = 10)
````
Hopefully that will do what you want. I could add an option to specifically control the label size but I don't want too many options...

**Comment by JulioCM** [comment]
Many thanks David. I'am able to change the fontsize and the width of the lines (lwd) and it helps but I was hoping to also change the size of the dots (the ones that appear when you use npoints).
