### ISSUE TITLE
[Question]: When importing data to open air what format should the date be in to run the time variation function? 

### ISSUE THREAD

**Issue by georgiamurphy17** [davidcarslaw/openair#337]
Please ask your question about `openair`. This could be about how to properly use `openair` functions, interpret plots, or something else entirely.

Before you submit your issue, it may be useful to check through the [openair book](https://bookdown.org/david_carslaw/openair/) just to make sure your question hasn't already been answered!

Feel free to delete these instructions before you submit your issue.

------------------------------------------------------------------------

Your question, with example code/[reprex](https://www.tidyverse.org/help/#reprex%3E) if appropriate.

**Comment by jack-davison** [comment]
Hi Georgia,

You need to make sure R understands that your date column is called `date` and is in the proper date(time) format.

``` r
library(openair)

class(mydata$date)
#> [1] "POSIXct" "POSIXt"
timeVariation(mydata)
```

![](https://i.imgur.com/QYmTPzQ.png)

The `{lubridate}` package is useful for properly formatting dates as dates / date-times.

``` r

## how do I format my date properly?
char_date <- "31/05/2020 10:00"
class(char_date)
#> [1] "character"
dttm_date <- lubridate::dmy_hm(char_date)
class(dttm_date)
#> [1] "POSIXct" "POSIXt"
```

<sup>Created on 2023-03-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

If you have some specific data you're interested in working with, feel free to provide some data. You may find the `dput()` function useful for this, or you can attach a small csv file here. See our guide for [sharing data](https://bookdown.org/david_carslaw/openair/sections/appendices/appendix-gethelp.html#providing-data).
