### ISSUE TITLE
[Bug]: quickText does not support "no" (nitrogen oxide) as pollutant

### ISSUE THREAD

**Issue by mooibroekd** [davidcarslaw/openair#343]
Currently the function `quickText` does not support the pollutant "NO". As the replacement currently is probably to greedy, some coding needs to be done to prevent unneeded replacement.

Perhaps we can also look at a easy way to expand the openair list of replacements with our own.

**Comment by jack-davison** [comment]
Morning Dennis,

I've just patched the development version of openair to auto-capitalise a solitary "no".

It shouldn't capitalise the string "no" when it is inside of other words (e.g., "NOwhere" or "aNOther")

It'd be a challenge to add user-specified conversions, but I'll think on it.

```r
library(ggplot2)
ggplot(mydata, aes(x = date, y = no)) + 
  geom_line() +
  labs(y = quickText("no conc (ug/m3) (nothing nowhere know another)"))
```
![image](https://github.com/davidcarslaw/openair/assets/45171616/313f04d6-b0fe-46fc-9d0e-e5ec4b38e9ff)

**Comment by mooibroekd** [comment]
Thanks Jack, looks good!
