### ISSUE TITLE
[Bug]: timeAverage() in Rv4.3.0 returning NAs for avg.time = "hour" and less, but in Rv4.2.3 returning numeric results

### ISSUE THREAD

**Issue by jardakreuz** [davidcarslaw/openair#345]
Till Rv4.2.3 timeAverage() worked as expected. With an update of R to version 4.3.0 and new installation of required and (not many, 4 in fact) other packages the timeAverage() function does not return numeric values with certain parametres (in 4.3.0 it returns all numeric values when avg.time = "day" and mostly (except first row and some others) NAs when avg.time is set to "hour" or "10 min").
When the same data prepared in Rv4.3.0 are loaded in Rv4.2.3 (i.e. even if created in Rv4.3.0), the timeAverage() function works as expected (returns all numerical values). There is no difference in the content of the data generated by Rv4.2.3 and Rv4.3.0 (checked with arsenal::comparedf()) in Rv4.2.3. The size of RData file created by Rv4.3.0 is 1 byte larger then the same data generated by Rv4.2.3. Also checked the "date" column is correct ("POSIXct" "POSIXt") class both in Rv4.2.3 and Rv4.3.0.
Somehow problematic data are available here:
https://drive.google.com/file/d/1JAZLzaJ0_-4R-31_SoEEIjzZBq1MNkHa/view?usp=sharing, https://drive.google.com/file/d/1Y4BxEm3fazZ4DRbgdEVwoMZEaIwaI2wn/view?usp=sharing
(note about the name of the files: these are data from a real measuring campaign, they are named "Test" just because I would like to know why the function timeAverage() returns different results in different R versions, so I labeled the files as such. In fact I truly appreciate effort and expertise of all of you.)

**Comment by davidcarslaw** [comment]
Thanks for your message. An issue was fixed in openair v 2.17-0 that I think was due to changes in R itself. Could you confirm this problem is still present in that version of openair? 

Thanks
David

**Comment by jardakreuz** [comment]
The problem I had with timeAverage() was solved in openair v 2.17-0. The new numeric results (I checked avg.time = "10 min") are all the same as from Rv4.2.3.
However every day of the measurment there is a missing time signature at 00:00:00 in results from openair v 2.17-0. (i.e. in date column there should be a triplet 2023-03-06 23:50:00 >> 2023-03-07 00:00:00 >> 2023-03-07 00:10:00, but now there is just 2023-03-06 23:50:00 >> 2023-03-07 >> 2023-03-07 00:10:00).

Best regards
Jarda

**Comment by davidcarslaw** [comment]
Strange - I don't get that. I don't think it should matter in practice but I will see if I can recreate this. What I get in R4.3.0 and openair 2.17-0 is:

<img width="662" alt="image" src="https://github.com/davidcarslaw/openair/assets/1236491/124921df-5159-4074-81a9-e1ce596b219f">

**Comment by jardakreuz** [comment]
The incomplete time signature was in the output of write.table() (for comparison of the results I usually use notepad++). In the R console I get the correct output with no missing information. Sorry for confusion and false issue.

I think the problem with timeAverage() is completely solved.

Thanks
Jarda

**Comment by davidcarslaw** [comment]
Great - thanks - closing issue..
