### ISSUE TITLE
[Bug]: summaryPlot does not respect local timezone and forces everything to GMT

### ISSUE THREAD

**Issue by mooibroekd** [davidcarslaw/openair#356]
Offending lines can be found at https://github.com/davidcarslaw/openair/blob/master/R/summaryPlot.R lines 230 and 285.

Possible bug fix: check if TZ is present, leave TZ alone. Otherwise transform character strings or dates without TZ to GMT by default.

``` r
library(openair)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union

# use default data
mydata <- mydata |> 
  selectByDate(year = 2004)

# date is in GMT
mydata$date[1]
#> [1] "2004-01-01 GMT"

# summaryPlot
summaryPlot(mydata)
```

![](https://i.imgur.com/ERDDszN.png)

``` r

# change data to different timezone
mydata$date <- force_tz(mydata$date, tzone="Etc/GMT-1")

# summaryPlot forces datetime into GMT, causing a shift of one hour in the data.
summaryPlot(mydata)
```

![](https://i.imgur.com/AATWjhm.png)

<sup>Created on 2023-07-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mooibroekd** [comment]
@jack-davison Could you be so kind to take a look?

**Comment by jack-davison** [comment]
Hi Dennis, I'll give that a look this afternoon. I believe `summaryPlot()` is a *very* old function, so I imagine David wrote it back when `{openair}` was really focused on a UK audience.

I *think* that all dates have a timezone (if you don't specify it is just UTC), but I expect we can stop `summaryPlot()` from forcing tz altogether and things will still work. I'll have a play and confirm.

**Comment by mooibroekd** [comment]
Hi Jack,

As I wrote earlier it is easy to check if there is a timezone associated with the dates. If not, then assume it is in UTC and perhaps use {cli} to notify the user that this assumption has been made. If it has a timezone, then just use that.

I think this way it has less of an impact. Despite being an old function, we still use it on a regular basis to visually check monthly monitoring data.

**Comment by jack-davison** [comment]
Hi Dennis,

This should have now been fixed in the dev version:

``` r
devtools::load_all()
#> ℹ Loading openair
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> 
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union

mydata <- mydata |> 
  selectByDate(year = 2004)

mydata$date[1]
#> [1] "2004-01-01 GMT"

summaryPlot(mydata)
```

![](https://i.imgur.com/DBR6XFY.png)

``` r

mydata$date <- force_tz(mydata$date, tzone="Etc/GMT-1")

summaryPlot(mydata)
```

![](https://i.imgur.com/6fO7gNP.png)

<sup>Created on 2023-09-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
