### ISSUE TITLE
[Bug]: [trajLevel] Error in vectbl_assign(x[[j]], i, recycled_value[[j]]) : DLL requires the use of native symbols

### ISSUE THREAD

**Issue by wenjia2017** [davidcarslaw/openair#357]
[Bug]: [trajLevel] Error in vectbl_assign(x[[j]], i, recycled_value[[j]]) : DLL requires the use of native symbols

I have an error through the trajLevel function.
Error in vectbl_assign(x[[j]], i, recycled_value[[j]]) : DLL requires the use of native symbols
I had installed the "openair" package version: ‘2.17.0’
I had faced the error a few days ago but It had worked well after some doing (but I don't know what I did). Today I have met this error again.
I attached my data file.
[traj.pm10.csv.zip](https://github.com/davidcarslaw/openair/files/12168839/traj.pm10.csv.zip)
My data and function are here.
head(trajdata)
![image](https://github.com/davidcarslaw/openair/assets/25658755/7278d9fa-741a-48d8-9fab-76fba9794034)
script content:
`
setwd('D:/RDataFolder')
library(openair)
library(tidyverse)
trajdata <- read.csv('trajAnalysis_olmair_t1690342460635_U000008.csv',header = T,sep=',')
trajdata$date <-  ymd_hms(trajdata$date, tz = "GMT")
trajdata$date2 <-  ymd_hms(trajdata$date2, tz = "GMT")
trajdata$hour.inc <- trajdata$hourinc
trajdata$hourinc <- NULL

mydata <- read.csv('trajAnalysisP_olmair_t1690342460521_U000008.csv',header = T,sep=',')
mydata$date <- ymd_hms(mydata$date, tz = "GMT")
trajdata <- left_join(trajdata, mydata, by = "date")

trajLevel(trajdata,pollutant = "PM10", statistic = "pscf",col = "increment",border = NA)

`
Error in vectbl_assign(x[[j]], i, recycled_value[[j]]) : 
  DLL requires the use of native symbols

**Comment by jack-davison** [comment]
Hi,

I'm afraid I cannot recreate your issue.

Searching StackOverflow reveals a recommendation that you update the tibble package (https://stackoverflow.com/questions/76176468/using-janitor-in-r-and-i-dont-understand-the-error-message-from-the-janitor-pac). Could you ensure your packages (not just openair, and especially tibble) are all up to date and give it another go?

Cheers, 
Jack

``` r
library(openair)
library(tidyverse)
trajdata <-
  read.csv(
    'trajAnalysis_olmair_t1690342460635_U000008.csv',
    header = T,
    sep = ','
  )
trajdata$date <- ymd_hms(trajdata$date, tz = "GMT")
trajdata$date2 <- ymd_hms(trajdata$date2, tz = "GMT")
trajdata$hour.inc <- trajdata$hourinc
trajdata$hourinc <- NULL

mydata <-
  read.csv(
    'trajAnalysisP_olmair_t1690342460521_U000008.csv',
    header = T,
    sep = ','
  )
mydata$date <- ymd_hms(mydata$date, tz = "GMT")
trajdata <- left_join(trajdata, mydata, by = "date")

trajLevel(
  trajdata,
  pollutant = "PM10",
  statistic = "pscf",
  col = "increment",
  border = NA
)
```

![](https://i.imgur.com/LT8GO6d.png)

<sup>Created on 2023-07-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by wenjia2017** [comment]
The issue has been resolved after upgrading the package

Make sure you're using tibble>=3.2.0. You can install the latest version by intall.packages('tibble')

**Comment by yuan-circle-long** [comment]
> The issue has been resolved after upgrading the package
> 
> Make sure you're using tibble>=3.2.0. You can install the latest version by intall.packages('tibble')

Thank you very much! I had the same problem and perfrom intall.packages("tibble") solved it.
