### ISSUE TITLE
windRose: how to control PM10 concentration ? 

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#36]
Hello,
In open air manual,  "12 The windRose and pollutionRose functions" section,  FIGURE 12.3 Wind rose for four different levels of PM10 concentration.

Does anyone know how to control the PM10 concentration in those four figures ? For example,  I want to make plots showing the PM10 concentration in "1 to 40", "40 to 75", "75 to 100" and "100 to 801"

Thank you very much.
Yi

**Comment by davidcarslaw** [comment]
You can easily define your own levels using `cut` - which is a general solution that should work with any openair function. This is very useful in a wide range of circumstances and works well with the `type` option in openair. Here is an example. It is up to you what the labels are to use e.g. could be "0 to 40" etc. The `include.lowest` makes sure the lowest level is included. Also, make sure the highest value used in the breaks is higher than the highest value in the data to make sure it is included. Note there is one more break than there are intervals.

```
mydata$intervals <- cut(mydata$pm10, breaks = c(0, 40, 75, 100, 1000), 
                     labels = c("Very low", "Low", "High", "Very High"), 
                     include.lowest = TRUE)
```

Then make a plot:

```
pollutionRose(mydata, pollutant = "pm10", type = "intervals")
```

In `pollutionRose` at least, if you just want one plot but the intervals defined as above, you can just do:

```
pollutionRose(mydata, pollutant = "pm10", breaks = c(0, 40, 75, 100, 801))
```

**Comment by lyggd** [comment]
Hello David,
Thank you very much for your help.
That totally works for me.
Cheers.
Yi
