### ISSUE TITLE
Can't succeed plot calendar plot with my own data

### ISSUE THREAD

**Issue by mkganyago** [davidcarslaw/openair#369]
### Question

Hello, 

I am trying plot a calendar plot bu I am getting: "Error in openair::calendarPlot(selectByDate(MAM_2021), year = 2021, month = 3:5,  : 
  No data to plot - check year chosen"
"In addition: Warning messages:
1: Unknown or uninitialised column: `date`. 
2: tz(): Don't know how to compute timezone for object of class NULL; returning "UTC". This warning will become an error in the next major version of lubridate. 
3: Unknown or uninitialised column: `date`. 
4: tz(): Don't know how to compute timezone for object of class NULL; returning "UTC". This warning will become an error in the next major version of lubridate. "

```{r}
library(openair)
library(tidyverse)

data <- read.table("./VIIRS_MAM_2021a.csv", sep = ",", header=T)
head(data)

MAM_2021 = as_tibble (data %>%
  mutate(Date=mdy_hm(data$ACQ_DATE, tz = "UTC"))%>%
  select(Date, FRP))
head(MAM_2021)

openair::calendarPlot(selectByDate(MAM_2021),
                      year = 2021,
                      month = 3:5,
                      pollutant = "FRP")
[VIIRS_MAM_2021a.csv](https://github.com/davidcarslaw/openair/files/12751855/VIIRS_MAM_2021a.csv)

```
I tried with both openair 2.17-0 and 2.17.0.9024
I appreciate your assistance.

**Comment by jack-davison** [comment]
Hi Mahlatse,

I think your issue is literally just that your "date" column is called "Date" instead; `{openair}` has a few internal rules you need to meet, and one is that the "date" column is lower-case.

Reprex:

``` r
aq_data <- readr::read_csv("https://github.com/davidcarslaw/openair/files/12751855/VIIRS_MAM_2021a.csv")
#> Rows: 10327 Columns: 3
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr (1): ACQ_DATE
#> dbl (2): ACQ_TIME, FRP
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

aq_data$date <- lubridate::mdy_hm(aq_data$ACQ_DATE)

openair::calendarPlot(aq_data, pollutant = "FRP")
```

![](https://i.imgur.com/lsWpGn9.png)

<sup>Created on 2023-09-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Cheers,
Jack

**Comment by mkganyago** [comment]
Hi Jack,

Thank you very much for clarifying.

Regards,
Mahlatse
