### ISSUE TITLE
Ropensci?

### ISSUE THREAD

**Issue by masalmon** [davidcarslaw/openair#37]
Hi,
Thanks for a great package!
I'm wondering whether you might consider trying to get the package to be part of the Ropensci suite? https://ropensci.org/ This would help its being even more visible. 
I am the developper of a package for accessing the OpenAQ API data https://github.com/masalmon/Ropenaq which is currently under review at https://github.com/ropensci/onboarding

**Comment by davidcarslaw** [comment]
Hi - thanks. I think that would be OK. What's involved in making it available? There is a potentially vast number of packages that would fit under ropensci, so how do you prioritize what is available?

**Comment by masalmon** [comment]
Well I am no Ropensci member so I do not know how they prioritize packages. I was actually surprised to see so few open issues on the onboarding repository (I thought they'd get much more submissions). Maybe you can start by asking them whether they think openair would be a good fit? I guess it is, it provides data retrieval and visualisation and could be helpful to many.

Then regarding package code they have policies https://github.com/ropensci/policies#ropensci-policies and packaging guide https://github.com/ropensci/packaging_guide#ropensci-packaging-guide which I think you nearly already respect (use of Roxygenize, continuous integration for instance, good documentation -> with the website and everything your package is really well documented already). 

I have read old reviews of packages on their onboarding repositories and was quite amazed at how they help improve the packages. Having someone read the code is really helpful. They simply need the package to have a good quality level, but as I said with your package being on CRAN and all I think it is already very good.

**Comment by masalmon** [comment]
PS: they reply to onboarding issues within 5 working days.
