### ISSUE TITLE
A question about image saving

### ISSUE THREAD

**Issue by NablaWang** [davidcarslaw/openair#374]
### Question

Hi! Today I'm using openair to make some images, but when I'm trying to use ggsave to save image to my disk, it tells me `Error in UseMethod("grid.draw")` . I also tried using dev.off() to save, but the result is same. I'm looking forward to a way to save image and also able to change the size and dpi. Thank you!

**Comment by jack-davison** [comment]
Hi Nabla,

`{openair}` is a very old package that's still going strong, and therefore predates `{ggplot2}` and does not work with `{ggsave}`. You'll need to go old school! See instructions [here](https://www.stat.berkeley.edu/~s133/saving.html).

example:

```r

library(openair)

# make an openair plot
polarplot <- polarPlot(mydata, "nox")

# open local graphics device
png(
  filename = "openair-plot.png",
  width = 5,
  height = 5,
  units = "in",
  res = 72
)

# plot openair
plot(polarplot)

# turn off graphics device
dev.off()
```
