### ISSUE TITLE
Under the Open air package, is it possible to convert calendar plots, that show air pollution levels over the month, into ics/iCalendar files?

### ISSUE THREAD

**Issue by sanajanaparmar** [davidcarslaw/openair#377]
### Feature request

Under the Open air package, is it possible to convert calendar plots, that show air pollution levels over the month, into ics/iCalendar files?

**Comment by jack-davison** [comment]
Hello!

Could I please ask what your use-case is for this?

Writing ics files using R is not something I've ever done (or, to be honest, seen done!) using R, but a quick Google shows there's at least one R package for doing this: 

https://cran.r-project.org/web/packages/calendar/index.html

Best,
Jack

**Comment by jack-davison** [comment]
I've written up some example code that runs `calendarPlot()`, pulls out the data, and writes the `.ics` files.

This sort of thing is very much out of scope for `{openair}` to do natively, but I hope you'll be able to usefully adapt what I've written below.

```r

# install.packages("calendar")
# install.packages("openair")

library(openair)
library(calendar)

dir.create("caltest")
setwd("caltest")

# make calendar plot
cal_obj <- calendarPlot(mydata, "nox", year = 2000, month = 1)

# get data
cal_data <- cal_obj$data

# drop "missing" values
cal_data <- cal_data[!is.na(cal_data$date), ]

# format dates
cal_data$date <- lubridate::as_datetime(cal_data$date)

# make calendar events
events <-
  purrr::map(
    .x = split(cal_data, cal_data$date),
    .f = ~ calendar::ic_event(
      start_time = .x$date,
      end_time = 24,
      summary = paste0("NOx concentration: ", .x$value)
    )
  )

# save calendar events
purrr::iwalk(.x = events,
             .f = ~ calendar::ic_write(ic = .x, file = paste0(.y, ".ics")))
```

**Comment by sanajanaparmar** [comment]
Hello Jack,

Thank you so much for your quick response. The way I was looking at this was, if people could download the ics file and super impose with their google calendars, then they would have high AQI days on their calendars.

Thank you so much for giving this a go, I really appreciate it.

Warm regards,
Sanjana
