### ISSUE TITLE
importTraj returns an http 403 error

### ISSUE THREAD

**Issue by peterlevy** [davidcarslaw/openair#385]
### Bug description

```importTraj``` returns an http 403 error, saying I don't have permission to access http://met-data.ricardo-aea.com/trajectories/. It returns an empty tibble. I find the same behaviour on my Windows laptop and a linux cluster. Has something changed with the Ricardo server?

### Steps to reproduce

```
traj <- importTraj(site = "london", year = 2009)
Warning messages:
1: In load(con) :
  cannot open URL 'http://met-data.ricardo-aea.com/trajectories/london2009.RData': HTTP status was '403 Forbidden'
2: In value[[3L]](cond) : london2009does not exist - ignoring that one.

traj
# A tibble: 0 × 0
```

### Openair version

```
packageVersion("openair")
[1] ‘2.18.2’
```

**Comment by jack-davison** [comment]
Hi Peter,

Thanks very much for your bug report and reproducible example! I can confirm even within the Ricardo VPN I can recreate your issue - I'll speak to our DevOps people to see what could be going on!

Thanks,
Jack
