### ISSUE TITLE
15 min Local SO2 data

### ISSUE THREAD

**Issue by TrackerSmith** [davidcarslaw/openair#387]
### Question

**Good Morning-I'm trying to pull back 15-min SO2 data for a local monitoring site Killingholme School (KILH).**
kil<-importLocal(site = "kilh",year=2024,pollutant = "so2") returns hourly data.
**If I try and run this for 15 minutes data the following error occurs:**
kil<-importLocal(site = "kilh",year=2024,pollutant = "so2",data_type = "15_min") Error: ! No data returned. Check `site`, `year` and `source`. Run `rlang::last_trace()` to see where the error occurred. > rlang::last_trace() <error/rlang_error> Error: ! No data returned. Check `site`, `year` and `source`. --- Backtrace:     ▆  1. └─openair::importLocal(...)  2.   └─openair::importUKAQ(...) Run rlang::last_trace(drop = FALSE) to see 2 hidden frames. > rlang::last_trace(drop = FALSE) <error/rlang_error> Error: ! No data returned. Check `site`, `year` and `source`. --- Backtrace:     ▆  1. └─openair::importLocal(...)  2.   └─openair::importUKAQ(...)  3.     └─cli::cli_abort(...)  4.       └─rlang::abort(...)
--
The data is available on the North Lincs website https://www.nlincsair.info/Report/AutomaticData but not the UK Air website.
Do you know if it is possible to download 15 minute data from the Local Authority website using openair, please?
Thank you very much for your help with this.

**Comment by davidcarslaw** [comment]
Morning

This should be fixed in the next please (`"15_min"`), but I think `data_type = "15min"` should work if you try that?

**Comment by TrackerSmith** [comment]
This worked perfectly.
Thank you very much for your kind help.

Kind regards,
Tracey Smith.
Technical Officer | Ambient Air Monitoring Team
Environment Agency | Lutra House | Walton Summit | Bamber Bridge | Preston | PR5 8BX
Telephone : 020 3025 1087 | Mobile : 07768 904914
Email : ***@***.******@***.***>

**Comment by davidcarslaw** [comment]
Thanks for letting us know and glad it worked.
