### ISSUE TITLE
timePlot does not work with tbl_df

### ISSUE THREAD

**Issue by masalmon** [davidcarslaw/openair#39]
timePlot does not seem to work with objects of the class tbl_df from the useful dplyr package. 

``` r
library("openair")
library("dplyr")
timePlot(mydata, pollutant="so2")
mydata2 <- dplyr::tbl_df(mydata)
class(mydata2)
timePlot(mydata2, pollutant="so2")
```
The second timePlot call outputs "unknown name".

Why is it so? 

Thanks a lot in advance!

**Comment by masalmon** [comment]
(for now I deal with the issue by transforming my tbl_df tables using as.data.frame)

**Comment by davidcarslaw** [comment]
strange - there should not be any problem with this as tbls from dplyr are fully compatible with data frames. All your code works fine for me. Is it worth checking you have up to date R + packages? Could you try your code in a clean R session also?

**Comment by masalmon** [comment]
Oh thanks, I seem to not to have up-to-date R and I have no admin rights... Well I'll keep converting for a while but write in my code that it's only a problem on my PC, thanks!
