### ISSUE TITLE
trajLevel CheckPrep Error

### ISSUE THREAD

**Issue by sofoniba** [davidcarslaw/openair#390]
### Question

Hi!
I get an error "checkPrep(mydata, vars, type, remove.calm = FALSE) " when using the function trajLevel. 
I attach screenshots.  I read about the problem when the error occurs due to incorrect reading of the date, but in my case the date has POSIXct format .I checked the structure and data type after reading the file, and did not find any errors. Any other functions in openair work without failures using the .csv file. This problem occurred only with trajLevel function.
I attach my code and the file from which I read the data.

[Disser.csv](https://github.com/user-attachments/files/16494634/Disser.csv)

```r
dat <- read.csv("C:/Users/Home/Documents/Old_disser/STATYA/Disser.csv",
                sep=";",header=TRUE,na.strings = "-999.9")
dat$date <- dmy_hm(dat$date)
colnames(dat) <-c("date","wd","ws","co2","ch4","zL")

trajLevel(traj, pollutant = "ch4", 
          statistic = "difference",
          col = c("skyblue", "white", "tomato"), 
          min.bin = 50, 
          border = NA)
```

I would be very grateful for advice on solving this problem
![Screenshot_2](https://github.com/user-attachments/assets/b99c6070-9b31-4426-930e-c07b95efc601)
![Screenshot_3](https://github.com/user-attachments/assets/2c253fc7-885b-492f-a7dc-c054302f8c74)
![структура массива](https://github.com/user-attachments/assets/e8d6fc0a-9eb9-41ff-867f-ccd27f924765)

**Comment by sofoniba** [comment]
@jack-davison , thank you very much for your reply!
It seems I get what the problem is. 
Yes, you're right, I plan to use the ch4 variable based on my observations from my file Disser.csv (dataframe "dat" in R).
Am I right that the variable ch4 (i.e. pollutant) should be part of "traj" dataframe? In your screenshot I see that the dataframe includes pollutants such as o3, no, pm10 and others. 
In that case, how can I get a dataframe that will contain both pollutant and trajectory data? Can I use my ch4 observations and include them from "dat" to "traj" dataframe? 
Or do I need to download trajectories from some version of HYSPLIT with a chemistry block that already contains pollutant data?

**Comment by jack-davison** [comment]
The general order of proceedings are:

1. Run HYSPLIT for a receptor local to your monitoring site.
2. Read that HYSPLIT data into R (e.g., using `read.csv()`)
3. Join the two dataframes together, e.g., using `merge()` or `dplyr::left_join()`

e.g., 

```r
traj <- read.csv("path/to/traj/data.csv")
## import data for North Kensington - you get data from wherever!
kc1 <- importAURN("kc1", year = 2023)
# now merge with trajectory data by 'date'
traj <- left_join(traj, kc1, by = "date")
# run trajplot
trajPlot(traj, pollutant = "no2")
```

There's an example in:

https://bookdown.org/david_carslaw/openair/sections/directional-analysis/trajectory-analysis.html#plotting-trajectories

**Comment by sofoniba** [comment]
@jack-davison , thank you!!! 
The problem was solved.
