### ISSUE TITLE
importTraj function is not working

### ISSUE THREAD

**Issue by yyh289** [davidcarslaw/openair#393]
### Bug description

Now you can't import pre-processed the trajectory data using importTraj. The reason is that it can't access the data through the website http://met-data.ricardo-aea.com. I wonder whether author plans to fix it.

**Comment by schonhose** [comment]
Duplicate of https://github.com/davidcarslaw/openair/issues/385

**Comment by jack-davison** [comment]
Closing as duplicate of #385. We also believe the issue to be fixed.
