### ISSUE TITLE
Few questions about "trajPlot"

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#41]
Hi All,
I am using ```trajPlot``` to make a tracks plot as below 
![rplot04](https://cloud.githubusercontent.com/assets/12972221/12691184/b3f7d3fe-c6a6-11e5-87ec-ac8f31a716e2.png)

with code 
```trajPlot(selectByDate(traj_JLG, start = "01/01/2014", end = "31/12/2014"),
         pollutant = "O3", breaks = c(0, 0.05, 0.07),col = c("green", "blue", "red"), lwd =2,border = NA,lon = "lon", lat = "lat", 
         map = TRUE ,map.fill = F,grid.col = F,  
         map.res = "state", projection="albers", xlim=c(-126,-105), ylim=c(30,41))```

But I would like to modified my plot a little bit but do not know how to do it.

1) I want to set the tracks with concentration < 0.05 in just green, tracks with concentration between 0.05 to 0.07 in blue and tracks with concentration >0.07 in red. In this way, I can highlight the tracks with O3 concentration over 0.07 ppb (new EPA standard).
I tried the code    ```breaks = c(0, 0.05, 0.07),col = c("green", "blue", "red")``` but it is not what I want. I would like to use just 3 colors.

2) I want to add a star in the plot to show my site (lat = 33.5038, lon = -112.0957)  but I can not do it.

3) I would like to add Mexico boundary in the map.

Anyone can tell me how to achieve that ?

I appreciate your help very much.
Thank you very much.

**Comment by davidcarslaw** [comment]
It is possible to do this in a slightly different way. You can group by any factor/character variable and show discrete intervals. First though you need to categorise the data in the way you want. Here's an example:

````
traj <- importTraj(year = 2010)

## make some intervals
traj$intervals <- cut(traj$height, breaks = c(0, 500, 1000, 20000), labels = c("0 to 500", "500 to 1000", ">1000"))

## plot
trajPlot(head(traj, 5000),group = "intervals", col = c("green", "blue", "red"), lwd = 2, key.pos = "top",key.col = 3)
````
I did notice that if the intervals had missing levels then teh map would not plot. Should be fixed on github now...

![capture](https://cloud.githubusercontent.com/assets/1236491/12715927/0f06d922-c8d5-11e5-9223-9f2be017d310.JPG)

**Comment by lyggd** [comment]
Hi David,
Thank you very much. The code now worked for me.
But I still want to know how to change the site on the plot from black dot to star or triangle.  
I appreciate your guidance very much.
Best Regards,
Yi

**Comment by davidcarslaw** [comment]
Currently the only symbol plotted is a black circle. I will have a think about adding other possibilities...
