### ISSUE TITLE
"Arrival time" problem in Hysplit result ?

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#44]
Hi All,
I come across a problem and confuse me a lot:

I run the two year hysplit modeling by:
```
for (i in 2013:2014) {
  procTraj(lat = 33.5038, lon = -112.0957, year = i,
           name = "JLG Supersite2", hours = 120,
           met = "C:/NARR/", out = "M:/HYSPLIT/output/TrajProc/",
           hy.path = "c:/hysplit4/")
}
```
Next I import my hysplit results 
```
traj <- importTraj(site = "JLG Supersite2", year = 2013:2014, 
                       local ='M:/HYSPLIT/output/TrajProc/' )

head(traj)
```
![image](https://cloud.githubusercontent.com/assets/12972221/12984341/7a757ede-d0aa-11e5-8ad3-ff11830c2a6c.png)

I notice the last column "date" only show date (not include hour), The "date"  is arrival time of air mass, which I will link with my site measurement data in next step.
I try several code to fix it but none of it work for me:
```
traj$date3 <- as.POSIXct (traj$date, format ='%Y-%m-%d %H:%M')

traj$date3 <- as.POSIXct (strptime(traj$date, format ='%Y-%m-%d %H:%M'))
```

If you run the example case in Openair Package:
```
traj1 <- importTraj(site = "london", year = 2010)
head(traj1)
```
You will find the "date" column include date and time, which is different with my results.

My questions is 

1) How can I let "date" column showing the time liking "date2" column ? 

2) For the arrival time ("date" column), is it in "GMT" or "local" time zone ?

I appreciate your help very much.
Thanks

**Comment by davidcarslaw** [comment]
It will depend on how the file was produced. Using the code at the back of the openair manual should work fine. What code did you use to create the trajectory files? Note the trajectory name should be a single word i.e. no spaces.

**Comment by lyggd** [comment]
I use the code at the back of the openair manual. But I do not why the "date" column only showing date not date and time.
Also, is the arrival time ("date" column) in "GMT" or "local" time zone?
Thank you very much.

**Comment by davidcarslaw** [comment]
All times to do with hysplit are in UTC (GMT). Please send the file (the RData file) you produce and I will take a look. The code in the manual should definitely produce a date-time (many other people use it).

**Comment by lyggd** [comment]
Thank you very much, David.
Let me re-run all the code. If the problem still there I will send to you.

**Comment by lyggd** [comment]
Hi David, my code and data have been send to you for double check.
I find if the the "date" column start with "00:00:00", then the time will not be showed.
But if the time become "01:00:00", the time will be showed
Thank you very much for your help.
Best Regards,

**Comment by lyggd** [comment]
Hi David,
If you have time, could you check with the code I send to your ?
I just want to make sure I did everything right.
I appreciate your help very much.
Best Regards,
Yi

**Comment by lyggd** [comment]
Hi David,
If you have time, could you check with the code and results I send to your ?
I just want to make sure I did everything right. Because my results looks different from your example.
I appreciate your help very much.
Best Regards,
Yi

**Comment by lyggd** [comment]
Problem solved. Thanks a lot !
Yi

**Comment by pavanaditya369** [comment]
Dear sir
I am having similar problems as listed above
  receptor year month day hour hour.inc    lat    lon height pressure
1        1 2017     2   1    0        0 13.164 80.263   10.0    997.6
2        1 2017     1  31   23       -1 13.183 80.329   10.7    998.3
3        1 2017     1  31   22       -2 13.204 80.409   11.3    999.3
4        1 2017     1  31   21       -3 13.228 80.502   11.5   1000.5
5        1 2017     1  31   20       -4 13.255 80.606   11.4   1002.0
6        1 2017     1  31   19       -5 13.286 80.720   10.9   1003.6
                date2       date
1 2017-02-01 00:00:00 2017-02-01
2 2017-01-31 23:00:00 2017-02-01
3 2017-01-31 22:00:00 2017-02-01
4 2017-01-31 21:00:00 2017-02-01
5 2017-01-31 20:00:00 2017-02-01
6 2017-01-31 19:00:00 2017-02-01
I had run the code for 2017, for 96 hours as mentioned in the Tutorial. 
My questions are:
1) How to link my pollution data with the above data?
2) How to get the time for the last date field?
3) There are only 6 data fields generated for the entire 2017 data. How shall I select the data from my pollution sample?
