### ISSUE TITLE
Size of labels using TimeVariation function

### ISSUE THREAD

**Issue by ClauGro** [davidcarslaw/openair#45]
Good Afternoon,

thanks to David for this really useful package.

I am using the Openair function timeVariation to produce hourly plot of four variables.
a <- timeVariation(rn, pollutant = "Rn",statistic = "mean",
            group="season",ci=T ,cols = c("green","orange","brown","gray"),
            ylab= expression(paste('Rn'^222," ",'(Bq','m'^{-3},')',sep=" ")),
                            cex.names=0.85)
plot(a, subset = "hour")

I want to change the sizes of the labels and the axis titles but cex options seem to not work at all.

Anybody knows how change them?
Thanks
Claudia

**Comment by davidcarslaw** [comment]
Currently it is not possible to directly control the font size of individual components. However, you can supply a `fontsize` argument to any openair function e.g. try `fontsize = 10`. That will scale all fonts in a proportionate way, which might be helpful to you. Also, see section 5.9 of the manual, as you can also control the relative size of fonts when you save a plot using a script...

**Comment by ClauGro** [comment]
Hi David,

I have tried to but actually the sizes do not change, neither in the tiff file:

radon.gic3 <- timeVariation(rn2, pollutant = "Rn_GIC3",statistic = "mean",
            group="season",ci=T ,cols = c("green","orange","brown","gray"),
            ylab= expression(paste('Rn'^222," ",'(Bq','m'^{-3},')',sep=" ")),
                            fontsize = 10)
tiff(filename = "Radon_gic3_day_season_variation.tif",
width = 7, height = 5, units = "in",res=300)
plot(radon.gic3, subset = "hour")
dev.off()

thanks
clau

**Comment by davidcarslaw** [comment]
You need to save sightly differently, try

````
png("first.png", width = 300 * 12, height = 6 * 300, res = 300)
timeVariation(mydata)
dev.off()
````

and (with proportionately bigger text)

````
png("second.png", width = 300 * 8, height = 5 * 300, res = 300)
timeVariation(mydata)
dev.off()
````

**Comment by ClauGro** [comment]
Hi David,

The png files hacve actually different size in the axis, thank you.

However, I did not understand why fontsize command did not work in Rstudio window.

In addition I want only to save the hour subset plot because I need it to mount different variables plots.

Can I just save it as png?

**Comment by davidcarslaw** [comment]
If you just want the hourly plot, do something like:

````
plt <- timeVariation(mydata)
png("hourly.png", width = 300 * 4, height = 3.9 * 300, res = 300)
plot(plt, subset = "hour")
dev.off()
````

I definitely see a difference between these two in RStudio:

````
timeVariation(mydata)
timeVariation(mydata, fontsize = 18)
````

What version of openair are you using?

**Comment by ClauGro** [comment]
1.0

**Comment by ClauGro** [comment]
I am going to upload the new version 

thanks

**Comment by davidcarslaw** [comment]
Ah - right, that is very old! The current version is 1.6 on CRAN. I'm just releasing 1.7 (will take a day or two). You can install directly from github if you follow the instructions here [https://github.com/davidcarslaw/openair](url). There is also an up to date zip file (windows) or gz (source file) you can download and install directly if you can't install from GitHub...best try that.

**Comment by ClauGro** [comment]
Great,

the problem was there.

The uploaded version works properly.

Thanks a lot
Clau
