### ISSUE TITLE
ModStats for wind direction

### ISSUE THREAD

**Issue by JulioCM** [davidcarslaw/openair#46]
I suspect that ModStats is not suitable for polar variables.
If that is the case, would it be possible to have ModStats for wind direction?

**Comment by davidcarslaw** [comment]
You are right - many of the functions used for `modStats` would not work correctly for wind direction. I would need to think about which statistics would be most appropriate for comparing two wind directions. It is possible to graphically compare two wind direction data sets (see Figure 12.8, 12.9).

**Comment by JulioCM** [comment]
Many thanks, I'll take a look
