### ISSUE TITLE
Error in quickText("", auto.text): 4 arguments passed to .Internal(nchar) which requires 3

### ISSUE THREAD

**Issue by craigsagit** [davidcarslaw/openair#47]
Hi David,

I have been using the openair package for a couple of years now, its great by the way! We generate some wind rose plots in R for daily reporting. Recently we have been having some issues with the windRose() function. I run the function on a dataframe of log files using some basic code:

```
`library(openair)

windRose(DataFrame, ws = "WS", wd = "WD", ws.int=1, breaks=6)`
```

Last night when the script ran it failed to generate the wind rose, giving the following error:

`Error in quickText("", auto.text): 4 arguments passed to .Internal(nchar) which requires 3`

Previously when I had seen this error, I installed the latest source code of openair from GitHub and it solved the problem. I tried that this time but had no luck. I was running version 1.7 so I updated to version 1.7-1 and the error was still the same. I removed openair and installed from CRAN again (V 1.7) but still the same. 

I checked my script on another computer which was running the same version of R (R version 3.2.3) but the 1.6.7 version of open air and it generated the wind rose without any error. 

Going back to the original machine, I deleted openair version 1.7 then installed zip file version 1.6.7 of openair from CRAN page [https://cran.r-project.org/web/packages/openair/index.html](url) and the script worked without error after that. 

When I printed nchar to the console window (with all versions of openair that I attempted to use) I got the following output:

`> nchar
function (x, type = "chars", allowNA = FALSE, keepNA = FALSE)
.Internal(nchar(x, type, allowNA, keepNA))
<bytecode: 0x1db8008>
<environment: namespace:base>`

nchar appears to be looking for 4 arguments so I cannot see why the error is being generated. 

I have written DataFrame to a csv file and attached should you need to run the function on the same data.

If you need anything else please let me know. 

Cheers,
Craig.
 
[gitData.zip](https://github.com/davidcarslaw/openair/files/144032/gitData.zip)

**Comment by davidcarslaw** [comment]
Thanks for the report. I can't reproduce the problem. My guess is that it is to do with the date format. In the updated manual I have started to recommend users us the `lubridate` package to format date/times - makes things a bit easier. Try something like:

````
dat <- read.csv("~/Downloads/gitData.csv", header = TRUE)
library(lubridate)
dat$DateTime <- dmy_hms(dat$DateTime)
windRose(dat, ws = "WS", wd = "WD", ws.int = 1, breaks = 6)
````
![rplot](https://cloud.githubusercontent.com/assets/1236491/13278501/dc80fbf8-dac8-11e5-9061-42beb95b1713.png)

**Comment by craigsagit** [comment]
Hi David,

Thanks for the quick response. I will give the lubridate package a go if the problem pops up again. 

I saw that someone else is having a similar issue in the links below:
[https://github.com/HenrikBengtsson/aroma.seq/issues/23]()
[https://github.com/HenrikBengtsson/globals/issues/6]()

Thanks,
Craig.
