### ISSUE TITLE
Error in trajLevel function with map

### ISSUE THREAD

**Issue by ClauGro** [davidcarslaw/openair#48]
Dear David,

openair version 1.0 helped  me to make nice trajectory plot witht the function:
trajLevel(subset(high_be, lat > 30 & lat < 60 & lon >-20 & lon <20),
          pollutant ="Be7", statistic = "frequency", smooth = TRUE,
          col = "increment")
trellis.focus("legend", side="right", clipp.off=TRUE, highlight=FALSE)
grid.text(expression(paste('High'," ",'Be'^7,sep=" ")), 0.07, 0, hjust=0.4, vjust=0.9)
trellis.unfocus()

but
the new version I have downloaded give me an error:

error using packet 1 
object 'wordMapEnv' not found

and it does not display the map under the plot

I distintalled the old package :(

**Comment by davidcarslaw** [comment]
Make sure openair is up to date (version 1.7). It should load the maps package automatically when you load openair. If not try `library(maps)` or `library(mapdata)` if you want high resolution maps with option `map.res = "hires"`. I just tested it and everything seems fine...

````
traj <- importTraj()
trajLevel(traj, xlim = c(-20,20), ylim = c(40,60))
````

![rplot](https://cloud.githubusercontent.com/assets/1236491/13283651/cdb158f2-dae6-11e5-9e3f-ef4aab6bfccf.png)

**Comment by ClauGro** [comment]
hi David,

loading the map library now it works,
however the new package makes a difference with smooth  option.
Actually when smooth= T is does not correctly colour the region with highest trajectories probability.
This region is not coloured at all.



![high_be7_bcn_2000_2014_be7_7d_1500_smooth](https://cloud.githubusercontent.com/assets/17357144/13285123/2661bd5e-daf9-11e5-8895-20fa0560505f.jpg)
![high_be7_bcn_2000_2014_be7_7d_1500__no_smooth](https://cloud.githubusercontent.com/assets/17357144/13285124/266b34f6-daf9-11e5-82fe-00a71c2981b4.jpg)

**Comment by davidcarslaw** [comment]
Thanks. I hadn't realised and not intended that smoothing should work here. The idea was to get these as discrete intervals over individual lat/lon cells. I think the units would need to change if smoothing was involved i.e. a percentage per unit lat/lon. I will think about whether this should be done however but I think my preference is un-smoothed...
