### ISSUE TITLE
Better base maps

### ISSUE THREAD

**Issue by davidcarslaw** [davidcarslaw/openair#5]
The large scale maps used in trajectory plotting are fine for country outlines. The country borders are hopelessly out of date (back to 1904!). Need to find a better source of base maps.

**Comment by jobonaf** [comment]
```{r}
adm0 <- raster::getData('GADM', country='FRA', level=0)
adm1 <- raster::getData('GADM', country='FRA', level=1)
plot(adm1, border="grey")
plot(adm0, add=T)
```

unfortunately, each country separately... ```raster::ccodes()``` may help

**Comment by davidcarslaw** [comment]
Thanks. Can't seem to get that working. 

Note that someone is updating the maps package to Natural Earth 1:50m, v2.0.0 and then will tackle the mapdata package also (higher resolution maps). This is meant to happen next month so I will see if it improves things before taking any action now...

**Comment by JaysonAP** [comment]
Any update on the maps and potential for better base maps?

Specifically I would very much enjoy the ability to include United State county borders on a few of the trajLevel maps.

Thanks

**Comment by lyggd** [comment]
Co-asking,
I am also would like to use a map with United State county border.
Thanks for working on.

**Comment by davidcarslaw** [comment]
Ideally I want to use base maps such as leaflet (see https://rstudio.github.io/leaflet/). That would make it possible to interact with the map e.g. zoom in and out and control the base map used. However, I have not had enough time to try an implement that yet. In the meantime, there is the option `map.res = "state"` which will use existing US state boundaries. It might even be worth supplying a range of shades for the states to help differentiate them. I think something like (at least for a London receptor):

```trajPlot(head(traj, 3000), map.cols = openColours("hue", 10))```
![image](https://cloud.githubusercontent.com/assets/1236491/12442849/6a9a95c8-bf4b-11e5-8eac-e96288970593.png)

The other question about importing air quality data from the USA similar to `importAURN` for the UK would be very useful. I'm surprised no one has written a function or package to do that for the USA? Might be worth checking. If not, where would one go to access US EPA data?

**Comment by JaysonAP** [comment]
There is a package on Github designed to download and import US EPA Air Quality data directly into R:  [raqdm](https://github.com/ebailey78/raqdm)

US EPA has resources that you can download data without login, however accessing the EPA's Data Mart with credentials is the easiest way to download chunks of data.

**Comment by jack-davison** [comment]
Closing stale issue. Feel free to open a new issue with any map/US data related issues.

> Ideally I want to use base maps such as leaflet (see https://rstudio.github.io/leaflet/). That would make it possible to interact with the map e.g. zoom in and out and control the base map used. 

Also noting that the quoted has been achieved through [openairmaps](https://github.com/davidcarslaw/openairmaps).
