### ISSUE TITLE
summaryPlot not displaying time series properly

### ISSUE THREAD

**Issue by NateByers** [davidcarslaw/openair#50]
Hello Dr Carslaw, 

I ran into an issue with the `summaryPlot()` function yesterday while giving a tutorial on openair. Here’s a link to the material I was using: [http://rpubs.com/NateByers/Openair](http://rpubs.com/NateByers/Openair). During the training, the students installed the latest version of openair and they could not get the `summaryPlot()` function to display the data correctly using the code at the beginning of the tutorial. I discovered that I made the tutorial materials using an older version of openair, and when I updated openair I also could not get the `summaryPlot()` function to work properly.

If you run the code with the latest version of openair that is on CRAN you should be able to see the difference between the output you get and the output I published to RPubs. I’m using data from a package I made that’s on GitHub.

`devtools::install_github(“NateByers/region5air”)`

Thanks for working on this project! It's an extremely useful package.

Cheers

**Comment by davidcarslaw** [comment]
Thanks for your message. Having just run it on your data (thanks) I think it looks correct in the most recent version of openair and wrong in an earlier version (the data capture calculations were wrong). Is that the problem you are referring to?
