### ISSUE TITLE
cluster analysis on back traj

### ISSUE THREAD

**Issue by lcrilleyl** [davidcarslaw/openair#55]
HI
I have been using the trajCluster function on the Weybourne data (imported with importTraj) and am experiencing some problems so thought I would let you know. 

I have been using this code from the manual to start with:

clust <- trajCluster(traj, method = "Angle", n.cluster= 7, col = "Set2", map.cols = openColours("Paired", 10))

but for some reason this not returning a data frame (in R studio it is listed under values) and so when I try to do anything with the 'clust' I get the following error:

> trajPlot(clust, group = "cluster")
Can't find the variable(s) date lat lon hour.inc height cluster 
Error in checkPrep(mydata, vars, type, remove.calm = FALSE) : 

I have tried this on my colleagues computer and the code worked fine. the only difference we can see is that I have the most recent version of openair (1.7.3) installed whereas my colleague has 1.7.

Thanks
Leigh

**Comment by davidcarslaw** [comment]
Yes, thanks I need to update the manual and help. The function now returns two data frames. The first (data) is what you want, the second (results) are the data that go into producing the cluster lines. Try:

    trajPlot(clust$data, group = "cluster")

I will update the manual shortly. Thanks for the report.
