### ISSUE TITLE
trendlevel

### ISSUE THREAD

**Issue by DAQLV** [davidcarslaw/openair#57]
Hi David,
I created a trendlevel plot for the ozone season (April thru Sep), and I noticed the month sequence is wrong.  Any way to fix this?
Jean-Paul
![trendlevel](https://cloud.githubusercontent.com/assets/13488179/13541063/004917b2-e20f-11e5-875b-8ccfa67bd9fc.jpg)

**Comment by davidcarslaw** [comment]
I can't seem to reproduce this in the most recent version of openair. The month order is correct with:

````
dat <- selectByDate(mydata, month = 4:9)
trendLevel(dat, x = "month", y = "wd")
````

You might need to send me some data if the problem persists with the most recent version.

**Comment by DAQLV** [comment]
Hi David,
Here is my code and the data:

dat<- import("q:/data.csv", header = TRUE, na.strings=c("NA","NoData"))
trendLevel(dat, pollutant = "o3", y = "wd", border = "white", cols = "jet",annotate="ws")

I do have the latest version of openair installed.
Cheers,
Jean-Paul

**Comment by davidcarslaw** [comment]
Thanks Jen-Paul. Any chance you can send the data too?

David

On 7 March 2016 at 14:38, DAQLV <notifications@github.com> wrote:

> Hi David,
> Here is my code and the data:
>
> dat<- import("q:/data.csv", header = TRUE, na.strings=c("NA","NoData"))
> trendLevel(dat, pollutant = "o3", y = "wd", border = "white", cols =
> "jet",annotate="ws")
>
> I do have the latest version of openair installed.
> Cheers,
> Jean-Paul
>
> From: David Carslaw [mailto:notifications@github.com]
> Sent: Monday, March 07, 2016 12:20 AM
> To: davidcarslaw/openair
> Cc: Jean-Paul Huys
> Subject: Re: [openair] trendlevel (#57)
>
>
> I can't seem to reproduce this in the most recent version of openair. The
> month order is correct with:
>
> dat <- selectByDate(mydata, month = 4:9)
>
> trendLevel(dat, x = "month", y = "wd")
>
> You might need to send me some data if the problem persists with the most
> recent version.
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/davidcarslaw/openair/issues/57#issuecomment-193150480>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidcarslaw/openair/issues/57#issuecomment-193274609>
> .
>



-- 
__________________________________
Dr David Carslaw
Wolfson Atmospheric Chemistry Laboratories
Department of Chemistry
University of York
Heslington
York, YO10 5DD
email: david.carslaw@york.ac.uk

**Comment by DAQLV** [comment]
I attached it with the previous email, but here it is again.
Jean-Paul

**Comment by davidcarslaw** [comment]
Ah, missed that sorry! Will take a look....

David

On 7 March 2016 at 14:45, DAQLV <notifications@github.com> wrote:

> I attached it with the previous email, but here it is again.
> Jean-Paul
>
> From: David Carslaw [mailto:notifications@github.com]
> Sent: Monday, March 07, 2016 6:44 AM
> To: davidcarslaw/openair
> Cc: Jean-Paul Huys
> Subject: Re: [openair] trendlevel (#57)
>
> Thanks Jen-Paul. Any chance you can send the data too?
>
> David
>
> On 7 March 2016 at 14:38, DAQLV <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> > Hi David,
> > Here is my code and the data:
> >
> > dat<- import("q:/data.csv", header = TRUE, na.strings=c("NA","NoData"))
> > trendLevel(dat, pollutant = "o3", y = "wd", border = "white", cols =
> > "jet",annotate="ws")
> >
> > I do have the latest version of openair installed.
> > Cheers,
> > Jean-Paul
> >
> > From: David Carslaw [mailto:notifications@github.com]<mailto:[mailto:
> notifications@github.com]>
> > Sent: Monday, March 07, 2016 12:20 AM
> > To: davidcarslaw/openair
> > Cc: Jean-Paul Huys
> > Subject: Re: [openair] trendlevel (#57)
> >
> >
> > I can't seem to reproduce this in the most recent version of openair.
> The
> > month order is correct with:
> >
> > dat <- selectByDate(mydata, month = 4:9)
> >
> > trendLevel(dat, x = "month", y = "wd")
> >
> > You might need to send me some data if the problem persists with the
> most
> > recent version.
> >
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/davidcarslaw/openair/issues/57#issuecomment-193150480>.
>
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/davidcarslaw/openair/issues/57#issuecomment-193274609>
> > .
> >
>
>
>
> --
> __________________________________
> Dr David Carslaw
> Wolfson Atmospheric Chemistry Laboratories
> Department of Chemistry
> University of York
> Heslington
> York, YO10 5DD
> email: david.carslaw@york.ac.uk<mailto:david.carslaw@york.ac.uk>
>
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/davidcarslaw/openair/issues/57#issuecomment-193277425>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidcarslaw/openair/issues/57#issuecomment-193278053>
> .
>



-- 
__________________________________
Dr David Carslaw
Wolfson Atmospheric Chemistry Laboratories
Department of Chemistry
University of York
Heslington
York, YO10 5DD
email: david.carslaw@york.ac.uk

**Comment by davidcarslaw** [comment]
Hi Jean-Paul

The attachment does not seem to be there?

David

On 7 March 2016 at 14:45, DAQLV <notifications@github.com> wrote:

> I attached it with the previous email, but here it is again.
> Jean-Paul
>
> From: David Carslaw [mailto:notifications@github.com]
> Sent: Monday, March 07, 2016 6:44 AM
> To: davidcarslaw/openair
> Cc: Jean-Paul Huys
> Subject: Re: [openair] trendlevel (#57)
>
> Thanks Jen-Paul. Any chance you can send the data too?
>
> David
>
> On 7 March 2016 at 14:38, DAQLV <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> > Hi David,
> > Here is my code and the data:
> >
> > dat<- import("q:/data.csv", header = TRUE, na.strings=c("NA","NoData"))
> > trendLevel(dat, pollutant = "o3", y = "wd", border = "white", cols =
> > "jet",annotate="ws")
> >
> > I do have the latest version of openair installed.
> > Cheers,
> > Jean-Paul
> >
> > From: David Carslaw [mailto:notifications@github.com]<mailto:[mailto:
> notifications@github.com]>
> > Sent: Monday, March 07, 2016 12:20 AM
> > To: davidcarslaw/openair
> > Cc: Jean-Paul Huys
> > Subject: Re: [openair] trendlevel (#57)
> >
> >
> > I can't seem to reproduce this in the most recent version of openair.
> The
> > month order is correct with:
> >
> > dat <- selectByDate(mydata, month = 4:9)
> >
> > trendLevel(dat, x = "month", y = "wd")
> >
> > You might need to send me some data if the problem persists with the
> most
> > recent version.
> >
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/davidcarslaw/openair/issues/57#issuecomment-193150480>.
>
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/davidcarslaw/openair/issues/57#issuecomment-193274609>
> > .
> >
>
>
>
> --
> __________________________________
> Dr David Carslaw
> Wolfson Atmospheric Chemistry Laboratories
> Department of Chemistry
> University of York
> Heslington
> York, YO10 5DD
> email: david.carslaw@york.ac.uk<mailto:david.carslaw@york.ac.uk>
>
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/davidcarslaw/openair/issues/57#issuecomment-193277425>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidcarslaw/openair/issues/57#issuecomment-193278053>
> .
>



-- 
__________________________________
Dr David Carslaw
Wolfson Atmospheric Chemistry Laboratories
Department of Chemistry
University of York
Heslington
York, YO10 5DD
email: david.carslaw@york.ac.uk

**Comment by davidcarslaw** [comment]
OK, thanks for the data. The problem is that your data already contains a column `month`. When openair sees an existing column it will use it directly and not interfere with it. The openair types based on time use the `date` field to calculate the components - so it can control what is done. So, best thing to do is drop your month column:

    trendLevel(subset(dat, select = -month), pollutant = "o3", y  = "wd")

That should work OK.

**Comment by DAQLV** [comment]
David,
You are right (as always….) it is perfect now.
Cheers,
Jean-PAul

**Comment by davidcarslaw** [comment]
Note that the order of the months is determined by its levels. So you can set them and plot directly:

````
levels(dat$month)
[1] "Apr" "Aug" "Jul" "Jun" "May" "Sep"
# set order
levels(dat$month) <- c("Apr", "May", "Jun", "Jul", "Aug", "Sep")
trendLevel(dat, pollutant = "o3", y  = "wd")
````
