### ISSUE TITLE
Linear regression for each group in scatterPlot()?

### ISSUE THREAD

**Issue by e-larry** [davidcarslaw/openair#58]
When plotting two groups of data in the same panel of a scatter plot, in addition to distinguishing groups using different colours and shapes, I would also like to add a regression line to each group, and show the linear equations and r2. However, linear = TRUE seems to be suppressed by enabling the group argument?

**Comment by davidcarslaw** [comment]
`scatterPlot` was recently updated to do this - or at least I think it should do what you want. You will need to install the GitHub version. Here is an example from the updated manual:

````
library(reshape2)
library(dplyr)
# select the variables of interest
subdat <- select(mydata, date, nox, pm10, pm25)
# calculate weekly averages
subdat <- timeAverage(subdat, avg.time = "week")
# reshape so we have two variable columns
subdat <- melt(subdat, id.vars = c("date", "nox"))

scatterPlot(subdat, x = "nox", y = "value", group = "variable",
pch = 21:22, cex = 1.6, fill = c("dodgerblue", "tomato"),
col = "white",
linear = TRUE,
xlab = "nox (ppb)",
ylab = "PM concentration (ug/m3)")
````

![rplot](https://cloud.githubusercontent.com/assets/1236491/13702026/96b79966-e783-11e5-9567-e38438788442.png)

**Comment by e-larry** [comment]
Thanks very much! I updated to the Github version and it worked.

I found that the `fill = c("dodgerblue", "tomato")` argument in your example code was necessary to show the two equations; otherwise only the first equation was shown.

**Comment by lyggd** [comment]
Hi David,
I have a following question related this issue:
I would like to get the similar figure  but calculate the linear regression and R^2 between PM2.5 vs O3 and PM10 vs NOx. Would should I do with the code ?
Is there any way I can modify the size of the linear equations and r2 ?
Thanks  a lot.
Yi

**Comment by davidcarslaw** [comment]
I think you would need to plot these two plots separately as they share a common x-axis. The only other thing you could think about is using `type` where `type` would distinguish between collections of pollutants in some way. It is currently not possible to adjust the size of the font directly - you can set `fontsize` though that will change the relative size of all fonts used e.g. try th option `fontsize = 20`.
