### ISSUE TITLE
choose first day of the week in calendarPlot

### ISSUE THREAD

**Issue by jobonaf** [davidcarslaw/openair#60]
in order to choose the first day of the week for `calendarPlot`, you could add a parameter `w.shift` and modify row 192 as follows:
```r
weekday.abb <- substr(format(ISOdate(2000, 1, 2:8), "%A"), 1, 1)[((6:12) + w.shift)%%7+1]
```
and 266 as follows:
```r
pad.start <- (as.numeric(format(mydata$date[1], "%w")) - w.shift) %% 7 + 1
```

**Comment by davidcarslaw** [comment]
Thanks! Will take a look

**Comment by davidcarslaw** [comment]
Seems to work fine - now added, thanks.
