### ISSUE TITLE
Trajectory

### ISSUE THREAD

**Issue by umeshdumka** [davidcarslaw/openair#63]
Dear Sir,
I want to generate the hourly airmass back trajectory for the year 2013. In order to this I am using the procTraj.R, add.met.R, read.files.R and run.R. In order to generate the hourly trajectory (i.e 24 airmass back trajectory for a day), how I can run these codes. Where I have to change in the code as it is 3 hour temporal resolutions.  Please let me know your valuable suggestions...

Regards

**Comment by davidcarslaw** [comment]
I think you just need to change these lines:

````
start <- paste(year, "-01-01", sep = "")
end <- paste(year, "-12-31 18:00", sep = "")
dates <- seq(as.POSIXct(start, "GMT"), as.POSIXct(end, "GMT"), by = "3 hour")
````

to 

````
start <- paste(year, "-01-01", sep = "")
end <- paste(year, "-12-31 23:00", sep = "")
dates <- seq(as.POSIXct(start, "GMT"), as.POSIXct(end, "GMT"), by = "hour")
````

Make sure you can run the base code without error first to make sure it runs OK on your system.
However, I don't think there is much point running the trajectories every hour as the resolution of the model won't be good enough. You might be better running every three hours (the default)...

**Comment by umeshdumka** [comment]
Dear Prof. David,
Thanks for your quick reply.
Shall I change this line also in the code:

for (i in 1:3)

to

for (i in 1:1)

Also Please let me know how I can resolve the error.


Regards
Umesh

On Tue, Apr 26, 2016 at 1:09 PM, David Carslaw <notifications@github.com>
wrote:

> I think you just need to change these lines:
>
> start <- paste(year, "-01-01", sep = "")
> end <- paste(year, "-12-31 18:00", sep = "")
> dates <- seq(as.POSIXct(start, "GMT"), as.POSIXct(end, "GMT"), by = "3 hour")
>
> to
>
> start <- paste(year, "-01-01", sep = "")
> end <- paste(year, "-12-31 23:00", sep = "")
> dates <- seq(as.POSIXct(start, "GMT"), as.POSIXct(end, "GMT"), by = "hour")
>
> Make sure you can run the base code without error first to make sure it
> runs OK on your system.
> However, I don't think there is much point running the trajectories every
> hour as the resolution of the model won't be good enough. You might be
> better running every three hours (the default)...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/davidcarslaw/openair/issues/63#issuecomment-214655370>
>



-- 

*************************************************************
Dr. Umesh Chandra Dumka
Scientist-D,

Aryabhatta Research Institute of Observational Sciences (ARIES)
Manora Peak, Nainital - 263 002, India
Ph.:+91-5942-270793;  Fax:+91-5942-233439 Mo.:+91-9897559451
Email: dumka@ <http://goog_690473241>aries.res.in <http://goog_690473241>;
ucdumka@gmail.com; umesh.dumka@yahoo.co.in
*USE LESS PAPER, CUT LESS TREES, SAVE PLANET EARTH*

**Comment by umeshdumka** [comment]
Thanks David,
Shall I change this line also: for (i in 1:3) to 

for (i in 1:1)

Also Please let me know How I can resolve this error:

Error in `$<-.data.frame`(`*tmp*`, "date", value = c(1420070400, 1420070400,  : replacement has 493311 rows, data has 493268

Thanks

**Comment by umeshdumka** [comment]
Thanks David,
Shall I change this line also: for (i in 1:3) to

for (i in 1:1)

Also Please let me know How I can resolve this error:

Error in $<-.data.frame(*tmp*, "date", value = c(1420070400, 1420070400, : replacement has 493311 rows, data has 493268

Thanks

**Comment by davidcarslaw** [comment]
No you should not change that line - it makes sure the met data are available for the current, past and next month. I am not sure why you get that error. Can you run the code in its default mode i.e. every 3 hours?

**Comment by umeshdumka** [comment]
Thanks David,
If I am running this code for hours =120 it is running properly. If I change the hours=168 then it is giving the error. Please let me know what is the problem with this.

regards

**Comment by jack-davison** [comment]
This is very stale (7 years), and I can't seem to find the code in David's comment so I'm closing this. It seems like the run HYSPLIT gist has been updated several times since this issue was raised also.

Instructions: https://bookdown.org/david_carslaw/openair/sections/appendices/appendix-hysplit.html

Gist: https://gist.github.com/davidcarslaw/c67e33a04ff6e1be0cd7357796e4bdf5

Feel free to try the updated code and if your problem is persisting, reopen another issue and we can take a fresh look.

Cheers,
Jack
