### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by umeshdumka** [davidcarslaw/openair#64]
Hi David and JaysonAP, 
I find black trajectory functions is very helpful. I would like to generate the trajectory for my location but after running the code it is
giving the following error

Error in `$<-.data.frame`(`*tmp*`, "date", value = c(1420070400, 1420070400,  : replacement has 493311 rows, data has 493268

Please let me know how to resolve this error. 

In addition to this I want to generate the trajectory in hourly basis then please let me know where I have to change in the code "procTraj"

Thank you very much.

**Comment by jack-davison** [comment]
Closing this issue as it hasn't been touched in many years, but feel free to reopen with a [reproducible example](https://www.tidyverse.org/help/#reprex%3E) if you are still having issues. Cheers!
