### ISSUE TITLE
Add a marker in maps

### ISSUE THREAD

**Issue by morganous** [davidcarslaw/openair#68]
Hello,
I am using the CWT model from the trajLevel function. It works well, but I was wondering if there is a way to add some markers on the map, in order to use them as geographical landmark (eg a city).
I tried to do that using trellis.last.object() + layer(lpolygon ect...) function as described in the manual, but is does not work.

Would you have an idea, on how could I manage to do that?
Thanks a lot for your help,

Morgan Lopez

**Comment by lyggd** [comment]
Co-ask.

**Comment by morganous** [comment]
Hello all,
I finally found out how to do it.
Insert the following lines after the trajLevel function, using the wanted projection:

`tmp <- mapproject(x = lat, y = lon, projection = projection, parameters = parameters, orientation = orientation)`
`c <- trellis.last.object() + layer(lpoints(tmp$x, tmp$y, pch=13, cex=13, col="red"))`
`print(c)`

Morgan
