### ISSUE TITLE
smooth = TRUE issue in trajLevel

### ISSUE THREAD

**Issue by awisher** [davidcarslaw/openair#7]
**openair version 1.1-5**

Using the option **smooth = TRUE** option in trajLevel as in the example

    trajLevel(mytrajdata, border = NA, smooth = TRUE)

gives the error

    Error in cut.default(mydata[, z], breaks, label = FALSE) : 
      'x' must be numeric

trajLevel without the **smooth = TRUE** option works properly.

**Comment by davidcarslaw** [comment]
OK, thanks. I will have a look.

**Comment by davidcarslaw** [comment]
Should now be fixed. But note that the default frequency plot is not intended to be smoothed - it has it's own dedicated scale. So better to do:

`trajLevel(mytrajdata, border = NA)`

I have also fixed other trajectory plot functions caused by a move to `dplyr` - should speed them up too.

**Comment by awisher** [comment]
Thanks for looking into this.
