### ISSUE TITLE
WindRose by Season

### ISSUE THREAD

**Issue by ralfweisse** [davidcarslaw/openair#70]
When plotting windroses per season I found that all months in winter (DJF) are from the same year;
that is, the rose e.g. for 1981 is produced from January 1981, February 1981 and December 1981. 
I would suggest adding an option that the rose is produced for succeeding months; that is, in the example above, for December 1981, January 1982, and February 1982. Maybe I missed it and there is already a way to do this but I failed to figure out. Any help would be appreciated.

**Comment by davidcarslaw** [comment]
Hi - yes, this is indeed how openair works for `type = "season"`. For most plots I don't think it will matter i.e. we want a split by months that correspond to a particular season, regardless of which year they are in. Is it that you are only plotting one year of data? Where the months in a season are considered in order is for time averages and trends e.g. `TheilSen`. In this case if you want trends by season, winter (northern hemisphere) will straddle two years e.g. Dec 2014, Jan 2015 and Feb 2015. You can see this in:

````
TheilSen(mydata, type = season)
````

and (maybe better):

````
TheilSen(mydata, type = season, avg.time = "season")
````

Does that make sense - or is there some refinement needed?

**Comment by ralfweisse** [comment]
Hi, thanks for the quick response. The reason I am asking is that I want to see if a particular winter season (storm period) was special in terms of windroses when compared to other years. In this case a storm season would be from e.g. Dec 2014 to Feb 2015. I was therefore interested in straddling the two years into one DJF season to compare the individual storm seasons visually by

`windRose(mydata, type=c("year","season"))`

but realized that this didn't give the expected results. It would be nice to have an option to change the behaviour. I am not sure if TheilSen might be a workaround for the moment but I will try and let you know.

**Comment by davidcarslaw** [comment]
I see. Need to think about how to handle this. Should December 2015 belong to the winter of 2016 for example? Perhaps it would be useful to have a new `type` option such as "seasonyear", which would behave a bit like "monthyear" i.e. plot every year-month combination but in this case would plot every year-season combination by grouping the month in a season as you suggest.

**Comment by ralfweisse** [comment]
Hi, this would be great. At the moment I use a workaround in which I first (in a loop over years) split the data into DJF seasons by, for example,
 
`mydata.sub <- subset(mydata, format(date,"%Y-%m-%d") < "1981-03-01" & format(date,"%Y-%m-%d")>"1980-11-30")`

subsequently store the results of WindRose using

`result <- windRose(mydata.sub)`

and then do the plotting by

`plot(result, split=c(px,py,nx,ny), more=T)`

where nx*ny is the number of years I analyze in the loop and px and py determine the panel where the actual year goes into. Not very fancy, but for the moment it works.

**Comment by davidcarslaw** [comment]
I should be able to add the functionality to do this early next week...

**Comment by davidcarslaw** [comment]
I have now added a new `type` to openair "seasonyear" (or "yearseason"). From the help file from `cutData`:

> "seasonyear (or "yearseason") will split the data into year-season intervals, keeping the months of a season together. For example, December 2010 is considered as part of winter 2011 (with January and February 2011). This makes it easier to consider contiguous seasons. In contrast, type = "season" will just split the data into four seasons regardless of the year.

An example - select a period of interest and plot a wind rose:

    windRose(selectByDate(mydata, start = "1/12/2000", end = "30/11/2001"),type = "yearseason")

![image](https://cloud.githubusercontent.com/assets/1236491/15465254/9c4d312a-20cb-11e6-93fb-65ff7d20ec3e.png)

You can either install the latest package from GitHub or follow links to the pre-made packages as described [here](https://github.com/davidcarslaw/openair)

**Comment by lyggd** [comment]
Cool ! Thank you very much for updating !
Yi

**Comment by ralfweisse** [comment]
Great and thank you very much for the quick response. It's much appreciated.

**Comment by adibratul** [comment]
I would like to do the windrose of 4  month(march to June ) as it considered as a season in my country. how to do that? In openair type="season" calculate three months but here in my country season is consist almost 4 months. how to make  4 windrose plot of 4 season considering 4 months in each season? 

Thanks in advance.
