### ISSUE TITLE
modStats() not calculating NMB due to typo.

### ISSUE THREAD

**Issue by e-larry** [davidcarslaw/openair#71]
Hi David,

We noticed that the modStats() in the latest version of openair (v1.8-2) did not include NMB in the output. My colleague then found a potential typo in the source code ("MMB" instead of "NMB" in the if() determining whether to include this statistics). I have since tried various quick-fixes for this problem, but none seemed to work. I tried redefining the function by simply correcting the typo, but the function required the openair context. I then tried

`assignInNamespace("modStats", mymodStats, ns = "openair")`

However, it did not work either.

Could you please advise how we could quickly fix this problem before you release a new version?

Many thanks.

**Comment by davidcarslaw** [comment]
Thanks. Yes, there was a typo, which should have been fixed in the pre-release version (i.e. install from GitHub)....
