### ISSUE TITLE
 trajLevel : Error in sc * colorcut : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by ClauGro** [davidcarslaw/openair#72]
Dear David,

I have used the backtrajectories dataframe several times to make nice plots with:
trajLevel(subset(trajectory_gic3_radon.df, lat > 30 & lat <55 & lon > -20 & lon <10),
          lon.inc=0.7,lat.inc=0.7,method = "hexbin",smooth=T,
          type = "season", col = "increment",origin=T,
          xbin = 100,xlim= c(-15,6), ylim = c(35,45))

The problem is than I am now trying to improve the plot, using the same dataframe, but i got an error and i did not find any information in the web.

The error is: Error in sc \* colorcut : non-numeric argument to binary operator

thanks
clau

**Comment by jack-davison** [comment]
Closing stale issue (7 years). If your issue persists, feel free to open a new issue, including a [reproducible example](https://www.tidyverse.org/help/#reprex%3E).
