### ISSUE TITLE
TrajLevel function and bar Limits

### ISSUE THREAD

**Issue by ClauGro** [davidcarslaw/openair#73]
Hi David,

could you tell me if there is any way to set the limits of the colour bar in the trajlevel function?
I have tried with limits and at but they did not work.

Thanks
Clau

**Comment by angothelene** [comment]
Hello - Did you find a way to do that? I have the same issue.
Thanks!

**Comment by jack-davison** [comment]
Hi both,

This can be achieved as follows:

``` r
openair::trajLevel(openairmaps::traj_data, statistic = "cwt")
```

![](https://i.imgur.com/0TRbwbN.png)

``` r

openair::trajLevel(openairmaps::traj_data, statistic = "cwt", limits = c(0, 1))
```

![](https://i.imgur.com/MbJWCUL.png)

``` r
Ȁ
#> Error in eval(expr, envir, enclos): object 'Ȁ' not found
```

<sup>Created on 2023-03-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
