### ISSUE TITLE
selectByDate "day" option not working for numeric days

### ISSUE THREAD

**Issue by khowe86** [davidcarslaw/openair#75]
Hi David,

I noticed that within the last month or so the selectByDate function no longer works when using numeric days. For example, I used to be able to 
`selectByDate(mydata,month="may",day=c(11,14,18))` 

It looks like this function was updated a month ago to incorporate the lubridate library, but this library is not loaded as part of the openair package. The selectByDate function works once I load this library separately. Was this the intended behavior?

Thanks,
Kyle

**Comment by davidcarslaw** [comment]
Thanks for the report. Should be fixed now.
