### ISSUE TITLE
Several back-trajectories with the same arrival date

### ISSUE THREAD

**Issue by davide-p** [davidcarslaw/openair#76]
I have calculated several back-trajectories using LAGRANTO, and formatted the output so that every field is present (as if they were generated using `importTraj`). However, when I use the other `openair` functions (such as `trajPlot` or `trajLevel`), I encounter a problem since I have several trajectories with the same `date` field, since they were generated with a different starting height or position (+- 1 degree). I.e., I have 12 different trajectories each day with the same `date` field. 
How can I consider these trajectories as if they are different?
Here below is shown a rough example of what happens when I try plotting the first two trajectories (which have a different starting height) on a specific day.
![trj_example](https://cloud.githubusercontent.com/assets/20336069/16649186/01f3e340-4438-11e6-93a4-f6b34752865f.png)

**Comment by jack-davison** [comment]
Appreciate this is a very stale issue (7 years), but this can be achieved with the `group` argument.

``` r
# create dummy data
traj <- openair::importTraj(year = 2000) |>
  dplyr::mutate(group = "grp1")

traj2 <- openair::importTraj(year = 2001) |>
  dplyr::mutate(group = "grp2")

traj2$date <- lubridate::`year<-`(traj2$date, 2000)

traj_all <- dplyr::bind_rows(traj, traj2)

traj_data <- openair::selectByDate(traj_all, year = 2000, month = 1, day = 1:5)

# plots
openair::trajPlot(traj_data)
```

![](https://i.imgur.com/09OWsAX.png)

``` r

openair::trajPlot(traj_data, group = "group")
```

![](https://i.imgur.com/Kdy4xSV.png)

<sup>Created on 2023-02-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
