### ISSUE TITLE
kernelExceed function bug

### ISSUE THREAD

**Issue by Hungmiau** [davidcarslaw/openair#77]
When I am using the function kernelExceed,there is a bug.
`kernelExceed(dbtest,pollutant = 'PM10',type='weekday',by='all',limit = 0.21)`
**dbtest** is my dataset which contains date PM10 ws wd and so on
![z_rkm ng0 m5u ybqndb f](https://cloud.githubusercontent.com/assets/13795193/16797762/8e5f85d6-491b-11e6-84c0-b9e990cfc61d.png)
**limit** 0.21 in the dbtest$PM10 there is actually 2 different hours of which value is above 0.21
but the output is 
![z 5e 6l yr hrb a xmj](https://cloud.githubusercontent.com/assets/13795193/16797821/c871c6d0-491b-11e6-8948-edb2ee857a4a.png)
which represents there are 2 plus 2 equals 4 hours of which value is above 0.21?

**Comment by jack-davison** [comment]
Closing this issue as `kernelExceed()` is a legacy function that is no longer supported by `openair` as of version 2.13.

If you would like to continue to use `kernelExceed()`, the raw code can be found here to adapt for your purposes: https://github.com/davidcarslaw/openair/blob/bfc0dae36e5683cf7d95aff8e2b52a0bfb56335e/R/kernelExceed.R

Best,
Jack
