### ISSUE TITLE
Remove the number of percentage on WindRose.

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#78]
Hi David,
 Do you know how to turn off the number like "5%,10%" on Windrose function？
I made some plots(attached) but think it will looks better if I can turn those number off.

> windRose(Site.Met,type = "year", layout = c(3, 2),
         paddle= F,main = paste0(Site,'(May-August)'))

If you have other suggestions on how to improve this plots, please feel free to let me know.
Thank you very much.
Yi
![rplot02](https://cloud.githubusercontent.com/assets/12972221/16849930/96fe3566-49b1-11e6-816b-92c5cdb6ddda.jpeg)

**Comment by davidcarslaw** [comment]
I think the easiest thing to do is set the the option `grid.line` to something like 10; so try:

`windRose(Site.Met,type = "year", layout = c(3, 2),
paddle= F,main = paste0(Site,'(May-August)'), grid.line = 10)`

**Comment by lyggd** [comment]
That's great! I find if we set grid.line = 50, we can remove the % number.
Thank you very much, David !
Yi
