### ISSUE TITLE
Cannot find ProcTraj function

### ISSUE THREAD

**Issue by coolshovan** [davidcarslaw/openair#81]
Hi i am getting an error while trying to execute the hysplit trajectories as:
could not find function "procTraj" while running trajectory plots

**Comment by jack-davison** [comment]
Closing as `procTraj()` doesn't appear to be exported by `openair`, used internally within `openair`, or a part of the [hysplit gist]("https://gist.github.com/davidcarslaw/c67e33a04ff6e1be0cd7357796e4bdf5").

Feel free to provide a [reproducible example](https://www.tidyverse.org/help/) if you'd like further support.

Cheers!
