### ISSUE TITLE
No base map in .eps format

### ISSUE THREAD

**Issue by PolPob** [davidcarslaw/openair#82]
Hi David,
Hope you are doing well. I equated back trajectory on Dhaka using the platform of openair. I plotted the trajectories with world base map. But whenever I saved the figure in .eps format, I missed the background world map. In other format like png the problem didn't exist. I couldn't understand the problem.

Md. Masud Rana
Dhaka

**Comment by jack-davison** [comment]
This is a very old issue, but just to mention that the way around this is to turn off map transparency, as EPS does not support this. Example code, plus viewing resulting file in an online EPS viewer.

```r
setEPS()
postscript("whatever.eps")
openair::trajPlot(openairmaps::traj_data[1:100, ], map.alpha = 1)
dev.off()
```

![image](https://user-images.githubusercontent.com/45171616/222968919-ecaf0165-a482-4d4a-b6e1-578dca0991a7.png)
