### ISSUE TITLE
How to fit legends in the plot ?

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#83]
Hello David,
I used open-air to make this plot. But I just get one question for you. 
Do you know how to move and fit the legends maybe in the top blank space of the plot?
Thank you very much.
Yi
The code I used was :
```
timePlot(Ozone_site,  avg.time = "month",group = TRUE,
         lwd = 4, lty = 1,pollutant = c("22ND & CRAYCROFT", "TANGERINE", "FAIRGROUNDS", "CHILDREN'S PARK", 
                       "SAGUARO PARK","GREEN VALLEY ","ROSE ELEMENTARY","COACHLINE"),
         ylim=c(0,0.08),ylab = "O3 concentration (ppm)")
![rplot](https://cloud.githubusercontent.com/assets/12972221/18182209/d30e560e-7043-11e6-9ddb-a4619e80d1b1.jpeg)
```

![rplot](https://cloud.githubusercontent.com/assets/12972221/18182243/f93747f0-7043-11e6-8995-dd1715b7faba.jpeg)

**Comment by davidcarslaw** [comment]
The easiest thing to do here is use the `key.columns` option. Something like:

```
timePlot(mydata, pollutant = c("nox", "no2", "o3"), avg.time = "month", key.columns = 2)
```

Hopefully that will do what you want...

**Comment by davidcarslaw** [comment]
Actually, I see that `timePlot` does not have a `key.position` option that some other functions do. I will add this tomorrow when I'm back at work.

**Comment by lyggd** [comment]
Thank you very much, David !
Yi

**Comment by davidcarslaw** [comment]
I have modified the code to include `key.position`, so try setting `key.position = "top"`.

I have also modified the way the main title is controlled. So to have it red and larger you can do things like that below. I will need to change other openair functions to do the same. However, this will ignore auto.text formatting e.g. subscripts on pollutants.

```
timePlot(mydata, pollutant = c("nox", "no2", "o3"), avg.time = "month", 
key.columns = 2, main = list(label = "My plot title", cex = 2, col = "red"))
```

![image](https://cloud.githubusercontent.com/assets/1236491/18195666/a9f0e5ba-70e4-11e6-8985-f1b4e04e940d.png)

**Comment by davidcarslaw** [comment]
Although you can do:

```
timePlot(mydata, pollutant = c("nox", "no2", "o3"), avg.time = "month", 
key.columns = 2, main = list(label = quickText("My plot of nox, no2 and o3"), cex = 2, col = "red"))
```

![image](https://cloud.githubusercontent.com/assets/1236491/18195744/42a37a16-70e5-11e6-9dd3-f9738cb0ca1f.png)

**Comment by mjb302** [comment]
Hi David,

I am using the split function to create a 3 column 4 row plot of multiple time variation subplots (a-d) i.e. 

print(a, split = c(1, 1, 3, 4), subset = "hour")
print(a, split = c(2, 1, 3, 4), subset = "month", newpage = FALSE)
print(a, split = c(3, 1, 3, 4), subset = "day", newpage = FALSE)
print(b, split = c(1, 2, 3, 4), subset = "hour", newpage = FALSE)
print(b, split = c(2, 2, 3, 4), subset = "month", newpage = FALSE)
print(b, split = c(3, 2, 3, 4), subset = "day", newpage = FALSE)
print(c, split = c(1, 3, 3, 4), subset = "hour", newpage = FALSE)
print(c, split = c(2, 3, 3, 4), subset = "month", newpage = FALSE)
print(c, split = c(3, 3, 3, 4), subset = "day", newpage = FALSE)
print(d, split = c(1, 4, 3, 4), subset = "hour", newpage = FALSE)
print(d, split = c(2, 4, 3, 4), subset = "month", newpage = FALSE)
print(d, split = c(3, 4, 3, 4), subset = "day", newpage = FALSE)

However the legends are printing over each other - This does not appear to be helped by setting the key value to True or False.

Any suggestions?

Thanks in advance

Matt
