### ISSUE TITLE
Set main text color and font in calendarPlot function 

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#84]
Hi David,
One more question for you: Do you know how to set the main text in `calendarPlot` function ?

For example, I made a figure as attached. But I would like to set main text "O3 at Saguaro National Park in 2013" in red with Font  4. 
I googled and try to use `col.main="red", font.main=4` but it did not work for me.

Thanks a lot
Yi 

`calendarPlot(O3SP, pollutant = "O3", annotate = "value", 
             lim =70,year = Y,statistic = "max",
             cols = "Purples", col.lim = c("black", "orange"),
             layout = c(4, 3),key.header = "O3 Con(ppb)",
             main= paste("O3 at Saguaro National Park in",Y,sep=" " ),
             col.main="red", font.main=4)

![rplot01](https://cloud.githubusercontent.com/assets/12972221/18188548/ed0f74f6-7067-11e6-8b3c-a92aa5f41828.jpeg)

**Comment by huyi1985** [comment]
I encountered the same problem.

**Comment by jack-davison** [comment]
Good morning,

This can be achieved as follows:

``` r
library(openair)

calendarPlot(
  mydata,
  year = 2003,
  main = "My special title",
  par.settings = list(par.main.text = list(col = "red"))
)
```

![](https://i.imgur.com/KOhV652.png)

<sup>Created on 2023-03-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
