### ISSUE TITLE
How to Rotate axis labels 

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#87]
Hi David,

I used timePlot () to make this plot. 
 Do you know how to rotate x-axis labels in the plot and let the x-axis labels showing every month as  format in "yyyy/mm"? 

I tried some code without luck, including "date.break".

Could you teach me how to do it ?

 Thank you very much.
 Yi
 The code I used was :
`timePlot(DPSPM10, avg.time = "day",data.thresh = 75,date.break= 20,
         pollutant = c("Douglas_PM10", "PAUL_PM10"),
         ylab = "PM 10 concentration (ug/m^3)",
         ref.y = list(h = 150, lty = 5,col="blue"))`

![rplot](https://cloud.githubusercontent.com/assets/12972221/18976031/87d11498-8663-11e6-9b22-e7034dbc557e.jpeg)

**Comment by davidcarslaw** [comment]
It's not directly possible to do this but you can supply a date format and date breaks that should give a lot of flexibility. For example, the `date.format` option can be used to split the date over two lines. The `\n` is the way to start a new line:

`timePlot(mydata, avg.time = "day", date.format = "%b\n%Y")`

**Comment by lyggd** [comment]
Hi David,
It works great! Thank you so much!
