### ISSUE TITLE
Add Regression Line 

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#88]
Hi David,

I use hourly PM10 data at two sites to make a daily scatter plot (attached).
`scatterPlot(PM10_2013,avg.time = "day",data.thresh = 75,
            
            x = "Douglas", y = "PaulSpur")
![rplot](https://cloud.githubusercontent.com/assets/12972221/19048327/beb677ce-895a-11e6-8c11-f719748c8ce9.jpeg)
`

But I also would like to do a regression analysis and add  regression equation on this plot.
I checked the open air manual but did not find any section talking about this.

Would you like to show me how to do that when you have time ?
It will be great if open air could have this options.

Thanks a lot !

**Comment by davidcarslaw** [comment]
Use the option `linear = TRUE`. There are also a few examples of usage in the manual - have a look at the one available through the GitHub site.
