### ISSUE TITLE
procTraj function for multiple receptor

### ISSUE THREAD

**Issue by PolPob** [davidcarslaw/openair#89]
Hi David,

We are really grateful to you for Openair and its manual. We have managed to create and run procTraj function for single receptor according to the codes given in the manual. However, for comparative study, we need to create a single procTraj function for 3 different receptors within the same country. We tried by inputting lats and lons of the receptors, like lat=c(x1,x2,x3), lon=c(y1,y2,y3), but model didn't run. 

Would you please suggest us if it is possible by simple change in the codes given in the manual?

Thanks
Masud

**Comment by jack-davison** [comment]
Closing as `procTraj()` doesn't appear to be exported by `openair`, used internally within `openair`, or a part of the [hysplit gist]("https://gist.github.com/davidcarslaw/c67e33a04ff6e1be0cd7357796e4bdf5").

Feel free to provide a [reproducible example](https://www.tidyverse.org/help/) if you'd like further support.

Cheers!
