### ISSUE TITLE
timePlot function smooth argument

### ISSUE THREAD

**Issue by DenisAShah** [davidcarslaw/openair#9]
smooth=TRUE does not output a smooth through the data :
timePlot(selectByDate(mydata, year = 1999), pollutant = "nox", smooth = TRUE, ci = FALSE)

R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
openair_1.5

**Comment by davidcarslaw** [comment]
`timePlot` needs some attention, but get rid of `ci = FALSE`...e.g.

     timePlot(selectByDate(mydata, year = 1999), pollutant = "nox", smooth = TRUE, avg.time = "day")
