### ISSUE TITLE
PercentileRose Issue 

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#91]
Hi 
I would like to use `percentileRose` to analysis my PM10 data.
My PM10 data was shown as below:

![capture](https://cloud.githubusercontent.com/assets/12972221/19778616/71022f06-9c32-11e6-8b5f-aec5f0b6b8ec.JPG)

Then I use the code as 
`percentileRose(PSPM10, wd= "WD_PAUL", pollutant = "PM10_PAUL",
               percentile = 95, method = "cpf",
               col = "darkorange", key.position = "right", smooth = TRUE)
`
But I get the error message 
> Error in `[.data.frame`(results.grid, , wd) : undefined columns selected

I tried several ways but still get this problem. Is there anyone know how to solve it ?
Thanks a lot
Yi

**Comment by davidcarslaw** [comment]
Thanks for the report. This is because of a bug not recognising wind directions that are not called `wd`. Should be fixed now.
