### ISSUE TITLE
Windflow problem in scatterPlot function

### ISSUE THREAD

**Issue by lyggd** [davidcarslaw/openair#92]
Hi David,
I have another problem of scatterPlot function.
I use the following code to make two figures, respectively.
`scatterPlot(selectByDate(DLPM10, 
            start = "2013-04-08",
            end = "2013-04-08"),
            x = "date", wd= "WD_DOUGLAS",
            ws= "WS_DOUGLAS",y = "PM10_DOUGLAS", z = "WS_DOUGLAS",
            col = "increment", ylim= c(0,1000),
            limits = c(0,10),
            windflow = list(scale = 0.05),
            key.footer = "WS(m/s)", ylab = "PM10(ug/m^3)", 
            main = "PM10 at Douglas (2013-04-08)")`
![rplot](https://cloud.githubusercontent.com/assets/12972221/19788053/10d666aa-9c5b-11e6-8c71-7ef16387d9c3.jpeg)

`scatterPlot(selectByDate(PSPM10, 
            start = "2013-04-08", 
            end = "2013-04-08"),
            x = "date", wd= "WD_PAUL",ws= "WS_PAUL",
            y = "PM10_PAUL", z = "WS_PAUL",
            col = "increment", ylim= c(0,1000),
            limits = c(0,10),
            windflow = list(scale = 0.05),
            key.footer = "WS(m/s)", ylab = "PM10(ug/m^3)",
            main = "PM10 at Paul Spur (2013-04-08)")`
![rplot01](https://cloud.githubusercontent.com/assets/12972221/19788080/3bffd802-9c5b-11e6-97bf-d49df42828bf.jpeg)

Even I save the two figures in the same size, the length of arrow in the second figure is still longer than the first one. But the actually wind speed are very close, indicating by the colors of the dots. 

Would you give me more instructions on how to set length of arrow  ? 

Thank you very much.
Yi

**Comment by davidcarslaw** [comment]
The length of the arrow is only a relative indication of wind speed. It is scaled relative to the plot dimensions. I would expect that for two data sets with very similar wind speeds the arrows would also be a very similar length. If you send the example data I can check it. Ideally these plots should have a scale for the arrows themselves...

**Comment by lyggd** [comment]
Hi David,
The data have been sent to you, please check this problem when you have time.
Thanks
Yi

**Comment by jack-davison** [comment]
Closing stale issue. For anyone searching, your best bet is probably to combine your plots into one by using the "type" argument.

Note that I don't have access to your specific data, but feel free to reopen the issue, post it here and we can have a look, if you are still having issues.

``` r
dat <- openair::importAURN(c("my1", "kc1"), year = 2020)

openair::scatterPlot(
  dat,
  type = "site",
  x = "date",
  y = "no2",
  z = "ws",
  col = "increment",
  windflow = list(scale = 0.05),
  key.footer = "ws", 
  key.position = "bottom",
  ylab = "NO2 (ug/m3)",
  main = "NO2 in London", 
  avg.time = "week"
)
```

![](https://i.imgur.com/5nY5VHU.png)

<sup>Created on 2023-02-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
