### ISSUE TITLE
[Feature Request]: Choose calm wind threshold on `windRose()`

### ISSUE THREAD

**Issue by JulioCM** [davidcarslaw/openair#93]
Is it possible to choose the threshold value for calms? For example, if I would like to show as calms all the hours that are below a value of 0.5 m/s,

**Comment by davidcarslaw** [comment]
The easiest way to do this would be to set all wind speeds <= 0.5 m/s to zero; something like:

```
id <- which(mydata$ws <= 0.5)
mydata$ws[id] <- 0
```

Strictly speaking though it could introduce some bias as it will assume a wind speed of 0.5 m/s and below is actually zero...

**Comment by JulioCM** [comment]
Many thanks for the answer David. But that's exactly the point for not doing that.

**Comment by davidcarslaw** [comment]
So, what you would like is for wind speeds <= 0.5 m/s to be considered as calms but to have the actual values used in the derivation of the mean ws? Compared with the 'fix' above this refinement would only affect the mean ws shown (which would be a bit higher) - right? It might be useful to have an option `calm` that allows users to set the value.

**Comment by JulioCM** [comment]
In the example, the east wind frecuencies changed.


![original](https://cloud.githubusercontent.com/assets/16103745/19816679/a881e2ae-9d1e-11e6-8404-a25959185363.jpg)
![filtercalm](https://cloud.githubusercontent.com/assets/16103745/19816682/aa60632a-9d1e-11e6-8c3d-d378b8efd496.jpg)

**Comment by JulioCM** [comment]
mean wind speed stays the same

**Comment by davidcarslaw** [comment]
But that would be expected because calms by definition cannot have a wind direction associated with them?

**Comment by JulioCM** [comment]
You are right. Many anemometers don't measure wind direcction accuretaly at wind speeds lower than 0.5 m/s

Thanks

**Comment by maxbre** [comment]
I would suggest that a 'calm' option to allow users to set the threshold wind speed would be much useful (i.e. affecting the wd plot but not the ws mean by leaving its actual value).
thanks

**Comment by jack-davison** [comment]
Fixed as of https://github.com/davidcarslaw/openair/commit/f13525880cc1e90e5367e74fb1073aea06d62a29.
