### ISSUE TITLE
timeplot tzone graph does not shift

### ISSUE THREAD

**Issue by Westonfrontier** [davidcarslaw/openair#94]
Greetings,

R version 3.3.1
openair_1.8-6

I am having trouble plotting timeseries of data that has a timezone.
I have data in GMT which i import as gmt and as local standard time (lst). The data is for Abu Dhabi, so the timezone is GMT+4. As shown below, I import as tzone="Etc/GMT-4".

<code>
omaa_2016_utc <- import("OMAA_mash_clean_timestamp_no_duplicates.csv",date.format="%Y-%m-%d %H:%M:%S")
omaa_2016_lst <- import("OMAA_mash_clean_timestamp_no_duplicates.csv",date.format="%Y-%m-%d %H:%M:%S",tzone="Etc/GMT-4")
</code>

However, the timePlot of temperature shows the peak temperature at the same hour in each plot. I have checked the userguide for extra arguments when calling timeplot. Am I missing something here? I need the graph to be in LST.
As you can see from the final plot, my LST data now shifts -4 hours instead of +4 hours. Any assistance would be appreciated.

<code>
timePlot(selectByDate(omaa_2016_utc,start="17/9/2016",end="20/9/2016"),pollutant="T",date.pad=TRUE,lwd=3)
</code>
![t_utc](https://cloud.githubusercontent.com/assets/9318199/19835457/ccd3c162-9ea0-11e6-8a75-0619f7051bb6.png)

<code>
timePlot(selectByDate(omaa_2016_lst,start="17/9/2016",end="20/9/2016"),pollutant="T",date.pad=TRUE,lwd=3)
</code>
![t_lst](https://cloud.githubusercontent.com/assets/9318199/19835463/db25a834-9ea0-11e6-985a-77c3d03a80ff.png)

<code>
data <- merge(omaa_2016_utc,omaa_2016_lst,by="date")
names(data)[names(data) == 'T.x'] <- 'T utc'
names(data)[names(data) == 'T.y'] <- 'T lst
timePlot(selectByDate(data,start="17/9/2016",end="20/9/2016"),pollutant=c("T utc","T lst"),date.pad=TRUE,lwd=3,group=TRUE,date.breaks=14)
</code>
LST now shifts left!
![t_utc_vs_lst](https://cloud.githubusercontent.com/assets/9318199/19835464/e96f26d6-9ea0-11e6-8bf2-e118dcbc7e9e.png)

**Comment by davidcarslaw** [comment]
Hi

The formatting of time zones in R when using the "Etc/GMT" form are a bit counterintuitive. See section 9 of the openair manual (link on main github page for openair). For your location the time zone should be expressed as **"Etc/GMT+4"**. Hopefully that will work for you.

**Comment by Westonfrontier** [comment]
Hi David

Thanks for the reply.  I was following the manual when assigning "GMT-4" for Abu Dhabi. Has this now changed and is opposite (GMT+4)? But let's assume I use GMT+4 for now. Next questions is;

Do you have any comment on the graphs? All timePlot graphs show the peak at Sep 18 12:00, regardless of the timezone I use as input to tzone. It only changes if I merge data. I.e. Is there an option in timePlot that allows the x axis label to be LST instead of GMT? 

Thanks and regards
Michael

**Comment by davidcarslaw** [comment]
Apologies, you are quite right; it should be Etc/GMT-4. I tend to make sure I work in GMT for everything because time zones can be a pain  - especially when manipulating data (which can drop time zone attributes). 

A way of checking the time zone is to look at the attributes. Have a look at `attr(omaa_2016_utc$date, "tzone")` and `attr(data$date, "tzone")` are they both "GMT"?

You can also set the time zone attribute like: 

`attr(data$date, "tzone") <- "GMT"`

Feel free to send some data I can take a look at if things are still confusing...

**Comment by jack-davison** [comment]
Closing stale issue (7 years). If this issue is persisting, feel free to reopen the issue containing a [reproducible example](https://www.tidyverse.org/help/#reprex).
