### ISSUE TITLE
Decimal places in equations in scatterPlot

### ISSUE THREAD

**Issue by MohoWu** [davidcarslaw/openair#95]
Is there a way to specify the number of decimal places for slope, intercept and R2 in the equations calculated in scatterPlot? Sometimes when the slope is 1.0 it will just show 1 and often it is preferable to have 2 decimal places.

**Comment by jack-davison** [comment]
Just tweaked `scatterPlot()` to use 2 d.p. consistently.

```r
data.frame(x = 1:100, y = 1:100) |> scatterPlot("x", "y", linear = T)
```
![image](https://github.com/davidcarslaw/openair/assets/45171616/d7396692-495d-49f8-bf3a-0d8cdcd4f435)
