### ISSUE TITLE
support angle argument in percentileRose

### ISSUE THREAD

**Issue by tverbeke** [davidcarslaw/openair#97]
`pollutionRose` supports an `angle` argument; would it make sense to also allow specifying such an `angle` for `percentileRose`?

**Comment by davidcarslaw** [comment]
I would be interested to know what the usage case would be for this i.e. do you see merit in angles <10 or > 10 degrees? It should be easy enough to implement but I'm curious what extra it might show...

**Comment by tverbeke** [comment]
Hi @davidcarslaw, Many thanks for your reaction. The data is scarce and the purpose is to be able to define wider angles. Otherwise the plots may display bizarre gaps between wind directions. Thanks again!

**Comment by davidcarslaw** [comment]
OK, I see. I have made some changes. If you are happy to install the github version, then you should be able to do:

`percentileRose(mydata, angle = 45)`

![image](https://cloud.githubusercontent.com/assets/1236491/20835368/27e286d2-b892-11e6-9f76-203c1848b373.png)

**Comment by tverbeke** [comment]
This looks perfect! Many thanks for the blazingly fast response!
