### ISSUE TITLE
scatterPlot: Adjusting axis tick interval

### ISSUE THREAD

**Issue by josephko91** [davidcarslaw/openair#98]
Dear @davidcarslaw 
I am new with openair, and fairly new with R. I cannot for the life of me figure out how to manually adjust the x-axis tick marks. For sake of example, I have x = date and y = CBL. I want the x-axis tick to be spaced out for every single day, instead of the default - which is currently showing as every 7 days. I've tried passing the scatterPlot to a variable, then calling the plot, and then using axis() to try to manipulate the plot; but I end up getting an error "plot,new has not been called yet". 

Can you please help or direct me to the right resources? It's hard to get help since this function is under this specific package. Thanks!

**Comment by MohoWu** [comment]
openair plots graphs using lattice package. Try searching questions with "lattice" at the end. Here's a discussion that may solve your problems: http://stackoverflow.com/questions/17584248/exact-axis-ticks-and-labels-in-r-lattice-xyplot

**Comment by jack-davison** [comment]
I'm going to close this stale issue (8 years).

If this issue still persists, please feel free to re-open this issue.

If producing a scatter plot, you could look to use `{ggplot2}`, which allows for fine control over plot features:

``` r
library(openair)
library(ggplot2)

plt <-
  ggplot(mydata, aes(x = nox, y = o3)) +
  geom_point() +
  labs(x = openair::quickText("NOx (ug/m3)"),
       y = openair::quickText("O3 (ug/m3)")) +
  theme_bw(base_size = 14)

# every 100
plt + scale_x_continuous(breaks = seq(0, 1200, 100))
#> Warning: Removed 4114 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/pM8NMJE.png)

``` r

# every 300
plt + scale_x_continuous(breaks = seq(0, 1200, 300))
#> Warning: Removed 4114 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/HmkxLBB.png)

``` r

# let {scales} pick roughly 6 nice breaks
plt + scale_x_continuous(breaks = scales::pretty_breaks(n = 6))
#> Warning: Removed 4114 rows containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/VVEHrJt.png)

<sup>Created on 2024-09-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Cheers,
Jack
